### ISSUE TITLE
Exception: TypeDecodingFailed "time format invalid for TimeUTC : cannot convert string

### ISSUE THREAD

**Issue by habbler** [snoyberg/http-client#102]
I get the following behavior on a Windows 7 machine
test5 :: IO Int
test5 = withManager $ \mgr -> return 2

> test5
*** Exception: TypeDecodingFailed "time format invalid for TimeUTC : cannot convert string 0007181000Z"

How can I find out which certificate the error occurs in? (All the certificates on the machine look ok).
I have not found the code path where withManager carries out certificate verification.

Rene.

**Comment by snoyberg** [comment]
Which module are you importing `withManager` from?

@vincenthz Is this a TLS exception?

**Comment by habbler** [comment]
Network.HTTP.Conduit

**Comment by snoyberg** [comment]
This appears to be a bug in the certificate package, please reopen there.
