### ISSUE TITLE
302 redirect, Location header is different host

### ISSUE THREAD

**Issue by johnpmayer** [snoyberg/http-client#103]
Trying to download a zip ball from github, somewhere along the line there is a 302 from github.com to codeload.github.com. My browser (chrome) is able to resolve this series of redirects (observed in developer tools)

By running in a cabal repl I can dump the Response Headers and find the Location header of the final target file in a 302 redirect

("Location","https://codeload.github.com/elm-lang/core/legacy.zip/1.1.0")

However, observing the access logs of my proxy server (squid, 10.0.0.216:3128) there is never a connection attempt to codeload.github.com. Thus I believe that the redirect logic rewriting the subsequent request based on the Location header is broken.

Here's the repro

``` shell
136     mkdir http-client-test
137     cd http-client-test/
138     cabal sandbox init
139     cabal update
140     cabal install http-client-0.4.7 http-client-tls
141     vi GitHubZip.hs
```

``` Haskell
{-# LANGUAGE OverloadedStrings #-}
import Network
import Network.HTTP.Client
import Network.HTTP.Client.TLS

run i =
  do
    let url = "http://github.com/elm-lang/core/zipball/1.1.0/"
    let settings = tlsManagerSettings
    withSocketsDo $ withManager settings $ \man -> do
      let req = url
               { proxy = Just $ Proxy "10.0.0.216" 3128
               , redirectCount = i
               }
      httpLbs req man >>= print
```

``` shell
142     cabal repl

Prelude> :l GitHubZip.hs
*Main> run 0 -- StatusCodeException 301 (expected)
*Main> run 1 -- TooManyRedirects 302 (expected)
*Main> run 2 -- TooManyRedirects 301 (expected)
*Main> run 3 -- StatusCodeException 404 (not expected!)
```

**Comment by snoyberg** [comment]
Good catch. The problem was that the *proxy's* host/port was being used for looking up the connection, not the destination host/port. I've pushed a commit that addresses that, can you confirm that it fixes your issue?

**Comment by johnpmayer** [comment]
Awesome, yes I confirmed that this fixes the issue in at least one of my
environments, probably good.

**Comment by snoyberg** [comment]
Thanks, I've released this to Hackage.

**Comment by evancz** [comment]
Awesome, thanks for figuring this out and fixing so quick!
