### ISSUE TITLE
Invalid status line "0" in keter

### ISSUE THREAD

**Issue by snoyberg** [snoyberg/http-client#108]
Moving issue to appropriate repo from:

https://github.com/snoyberg/keter/issues/75#issuecomment-77004887

Next step: minimal reproducing test case. Likely need a highly concurrent app sharing a single HTTP manager.

**Comment by snoyberg** [comment]
Pinging @jgreve-github @creichert

**Comment by snoyberg** [comment]
@jgreve-github Could you try running this on your dev machine and your server to see if it reproduces the bug (it does *not* on my machine, for the record):

```haskell
{-# LANGUAGE OverloadedStrings #-}
import           Blaze.ByteString.Builder (fromByteString)
import           Control.Applicative      (pure, (*>))
import           Control.Concurrent       (threadDelay)
import           Control.Concurrent.Async (Concurrently (..), race)
import           Control.Concurrent.MVar  (newEmptyMVar, putMVar, takeMVar)
import           Control.Monad            (replicateM_, when)
import qualified Data.ByteString          as S
import qualified Network.HTTP.Client      as HC
import           Network.HTTP.Types       (status200)
import qualified Network.Wai              as W
import qualified Network.Wai.Handler.Warp as W

chunked200 :: W.Application
chunked200 req send = send $ W.responseStream status200 [] $ \chunk flush ->
    replicateM_ 10 $ do
        chunk $ fromByteString "Hello World!"
        flush
        threadDelay 10000

withChunked200 :: IO a -> IO a
withChunked200 x = do
    baton <- newEmptyMVar
    eres <- race (server baton) (takeMVar baton >> x)
    either undefined return eres
  where
    server baton = W.runSettings
        (W.setBeforeMainLoop (putMVar baton ()) W.defaultSettings)
        chunked200

main :: IO ()
main = withChunked200 $ do
    man <- HC.newManager HC.defaultManagerSettings
    let req = "http://127.0.0.1:3000"
    runConcurrently $
        let go 0 = pure ()
            go i = Concurrently flush *> Concurrently unflushed *> go (i - 1)
            flush = single True
            unflushed = single False
            single toFlush = replicateM_ 100 $ HC.withResponse req man $ \res -> do
                let loop = do
                        bs <- HC.brRead $ HC.responseBody res
                        when (not $ S.null bs) loop
                when toFlush loop
         in go (10 :: Int)
```

**Comment by jgreve-github** [comment]
@snoyberg, I will give it a try as soon as I'm back home from work and have access to the local dev server. phreeknet.de has no haskell dev environment :)

**Comment by creichert** [comment]
I'm a little lost on how you determined this was a hardware issue :). I'll keep watching in case I can be of help.

**Comment by snoyberg** [comment]
It seems like race condition behavior. I don't mean it's a hardware
dependent bug, but that the timing of different hardware has different
chances of triggering the behavior.

**Comment by jgreve-github** [comment]
@snoyberg, is this of any help?
    
    jg@atomic:~/keter$ nano Test.hs
    jg@atomic:~/keter$ ghc -o test Test.hs 
    [1 of 1] Compiling Main             ( Test.hs, Test.o )
    Linking test ...
    jg@atomic:~/keter$ ./test 
    jg@atomic:~/keter$

**Comment by snoyberg** [comment]
Yes and no. It means my program did not reproduce the bug. This will
require more research it seems. Next step will probably be to ask you to
run a custom version of keter using a tweaked http-client to output more
debug information.

**Comment by jgreve-github** [comment]
No problem; everything is set up on the dev machine already to use the git repo for building keter since the testing of your pessimization-branch :)

**Comment by snoyberg** [comment]
I take it back completely: there's no http-client bug at all, this is a pure warp bug. This can be demonstrated by the output on an empty file of:

```
GET / HTTP/1.1

HTTP/1.1 416 Requested Range Not Satisfiable
Transfer-Encoding: chunked
Content-Length: 0
Accept-Ranges: bytes
Date: Sun, 08 Mar 2015 06:45:55 GMT
Server: Warp/3.0.9.2

0
```

Scratch what I said about it being a race condition... that's *somewhat* true in the sense that where the error popped up is timing specific, but the bug is reliably reproduced (now that I know what to look for).
