### ISSUE TITLE
Is there a way to automatically set `secure`?

### ISSUE THREAD

**Issue by seagreen** [snoyberg/http-client#112]
If so I haven't been able to find it yet. I doesn't take much more code for me to check whether my URLs start with `http` or `https`, but it would be nice to have this handled at the library level (especially for `simpleHttp` which I imagine a lot of people will use without reading far into the docs).

**Comment by snoyberg** [comment]
I'm unclear on what the request is here, can you clarify?

**Comment by seagreen** [comment]
Of course, sorry to be unclear.

I was wondering if the library has a way to automatically set the `secure` field of a `Request` to True or False by detecting whether the URL used to construct the request starts with "http" or "https".

I just answered my own question though -- it definitely does. `parseURL` calls `setURI`, which [takes care of this](https://github.com/snoyberg/http-client/blob/master/http-client/Network/HTTP/Client/Request.hs#L127).

Thanks for the great library, and feel free to close this issue.

**Comment by snoyberg** [comment]
Cool, glad it's doing what you need.
