### ISSUE TITLE
bad SignatureRSA for dhparams

### ISSUE THREAD

**Issue by markwithers** [snoyberg/http-client#113]
When I attempt the following code

    simpleHttp "https://api.guildwars2.com/v2/build"

I get the following exception

    *** Exception: TlsException (HandshakeFailed (Error_Protocol ("bad SignatureRSA for dhparams",True,HandshakeFailure)))

I have no problems fetching the json response in a browser, or with equivalent NodeJs code

**Comment by snoyberg** [comment]
Could you please follow the debugging guidelines at:

https://github.com/vincenthz/hs-tls#tls-issues

Pinging @vincenthz

**Comment by markwithers** [comment]
Of course

I pulled tls-debug from cabal, and tried 

    tls-simpleclient "api.guildwars2.com" 443

and got some html detailing a 403 forbidden error

I tried

    tls-retrievecertificate --chain --verify "api.guildwars2.com" 443

and got

    connecting to api.guildwars2.com on port 443 ...
    tls-retrievecertificate: HandshakeFailed (Error_Protocol ("bad SignatureRSA for dhparams",True,HandshakeFailure

**Comment by snoyberg** [comment]
Looks like this was resolved upstream.
