### ISSUE TITLE
Confusion with updateCookieJar

### ISSUE THREAD

**Issue by bos** [snoyberg/http-client#117]
I am seeing some behaviour that is confusing me in my use of `updateCookieJar`.

[Here's the offending code](https://github.com/bos/wreq/blob/b53cddabd5612de11b3439f5e19aadf4eb768998/Network/Wreq/Session.hs#L142) (annotated with types):

```haskell
runWith :: Session -> Run Body -> Run Body
runWith Session{..} act (Req _ req) = do
  cj <- readIORef seshCookies -- CookieJar
  let req' = req & Lens.cookieJar ?~ cj -- plop the CookieJar into the request
  resp <- act (Req (Right seshManager) req')
  now <- getCurrentTime
  atomicModifyIORef seshCookies $ HTTP.updateCookieJar resp req' now
```

When `cj` begins empty, it seems that `updateCookieJar` always *leaves* it empty, even in a case where I'm hitting an endpoint that most definitely sends back a `Set-Cookie` header, [as in this test](https://github.com/bos/wreq/blob/b53cddabd5612de11b3439f5e19aadf4eb768998/tests/UnitTests.hs#L265):

* The first `get` yields a `Set-Cookie` response, which I can see if I inspect the result instead of ignoring it. (There's quite a bit of indirection in the `Session` internals, but basically `runWith` is always called to handle any request – and should be handling the cookies.)

* By the time the second `get` begins, the cookie jar is already empty – but it should have a cookie in it after the first.

To double check, I bodged together a hand-hacked `runWith` that contains a bunch of print statements.

Notice:

* Empty cookie jar before request.
* Response cookie jar contains a cookie.
* The result of `updateCookieJar` is empty (!?!?).

```haskell
runWith :: Session -> Run Body -> Run Body
runWith Session{..} act (Req _ req) = do
  cj <- readIORef seshCookies

  print ("before", cj)
  -- PRINTS ("before",CJ {expose = []})

  let req' = req & Lens.cookieJar ?~ cj
  resp <- act (Req (Right seshManager) req')

  print ("resp cj", resp ^? responseCookieJar)
  -- PRINTS ("resp cj",Just (CJ {expose = [Cookie {cookie_name = "foo", cookie_value = "bar",
  -- cookie_expiry_time = 3014-08-13 00:00:00 UTC, cookie_domain = "localhost", cookie_path = "/",
  -- cookie_creation_time = 2015-04-12 03:44:36.547835 UTC,
  -- cookie_last_access_time = 2015-04-12 03:44:36.547861 UTC, cookie_persistent = False,
  -- cookie_host_only = True, cookie_secure_only = False, cookie_http_only = False}]}))

  now <- getCurrentTime

  print ("mod", fst (HTTP.updateCookieJar resp req' now cj))
  -- PRINTS ("mod",CJ {expose = []})

  x <- atomicModifyIORef seshCookies $ HTTP.updateCookieJar resp req' now
  cj1 <- readIORef seshCookies

  print ("after", cj1)
  -- PRINTS ("after",CJ {expose = []})

  return x
```

Can you shed any light on whether I'm using `updateCookieJar` incorrectly, or if it's got a bug, or ... what?

**Comment by bos** [comment]
Actually, it occurs to me that I should explain what I'm trying to do, because maybe that's the source of the problem.

I have a `Session` type that stores a `CookieJar`, which I want to use persistently across multiple requests. It's possible that multiple threads could use this session concurrently, in which case I'd like the `CookieJar` to remain consistent.

I hoped that `updateCookieJar` combined with `atomicModifyIORef` was the right combination of ways to manage possibly concurrent uses of the cookie jar – but now I see that I'm failing in even the single-threaded case.

**Comment by bos** [comment]
[This is the workaround](https://github.com/bos/wreq/commit/29da1914aa93ca57a64c1fb3ab13461c59543cc0) I have for now, which frankly looks totally wrong to me – but it makes that specific test pass :-(

**Comment by snoyberg** [comment]
I actually haven't worked with the cookie jar code myself, but I believe the problem is that you're trying to bypass http-client's built-in cookie handling support, without telling http-client not to use that support. Can you try setting `cookieJar` to `Nothing` in the `Request` and see if that resolves things?

**Comment by snoyberg** [comment]
Based on lack of response, guessing that this is working. Closing, if the issue is not resolved based on my comments, please reopen.

**Comment by jwaldmann** [comment]
I have a similar use case.

What exactly is "http-client's built-in cookie handling support" that you are referring to? Will it manage the cookie jar (as a browser would)? 

And how do I enable it? You're saying `cookieJar=Nothing` but according to docs, then `no cookie handling will take place` http://hackage.haskell.org/package/http-client-0.4.18/docs/Network-HTTP-Client.html#v:cookieJar which sounds like the opposite of what I want.

**Comment by snoyberg** [comment]
I didn't write any of the cookie handling code and so am not familiar with
the details of it. But I believe the information here is consistent: Bryan
wanted to handle the cookie manipulation more directly, and therefore I
recommended disabling the automatic support present in http-client.
