### ISSUE TITLE
simpleHTTP of Network.HTTP.Conduit performing slowly for get requests

### ISSUE THREAD

**Issue by abhipras** [snoyberg/http-client#118]
For simple `GET` requests, simpleHTTP is performing way more slowly than its alternatives in other languages(e.g. Ruby, Go).

```haskell
import Data.ByteString
import Network.HTTP.Conduit

main = do
	response <- simpleHttp "https://github.com/trending?l=haskell"
	return ()
```

Compiled to a binary named as Testhttp, it took 6 minutes 42 secs to complete 100 api requests whereas the ruby alternative just takes 153 secs for 100 api calls using `Net::HTTP.get(URI.parse("https://github.com/trending?l=ruby"))`
```bash
time for NUM in `seq 1 1 100`; do ./Testhttp; done
real    6m42.839s
user    0m12.115s
sys 0m2.652s
```
I need to make only one request and not multiple in my code and so it doesn't perform similar to the simplest alternatives in other languages.
I have also posted a [Stackoverflow question](http://stackoverflow.com/questions/29778484/haskell-simplehttp-of-network-http-conduit-performing-slowly-for-get-requests) regarding this.

**Comment by snoyberg** [comment]
There are far too many variables at play here to do a proper test. For example: version of Ruby compared to, full Ruby code, same issues with Go, the RTS overhead being incurred during startup, overhead on the github side, overhead in the network layer, etc. I don't have enough evidence here to know that there really is any performance problem. With these kinds of situations, I'd normally recommend a test against a local web server to demonstrate the problem.

**Comment by abhipras** [comment]
I started Elasticsearch server on my host and benchmarked both Ruby and Haskell versions of code
Ruby version
```bash
ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin12.0]
```
```haskell
{-# LANGUAGE OverloadedStrings #-}

import Network.HTTP.Conduit
import Data.ByteString
import Control.Monad
import Criterion.Main

main = defaultMain [
    	bench "performGetRequests" $ nfIO (simpleHttp "http://localhost:9200")
  	]
```
These are the stats returned by `Criterion`
```bash
./Testhttp 
benchmarking performGetRequests
time                 40.72 ms   (39.59 ms .. 41.62 ms)
                     0.998 R²   (0.994 R² .. 0.999 R²)
mean                 40.14 ms   (39.67 ms .. 40.67 ms)
std dev              981.5 μs   (738.2 μs .. 1.374 ms)
```

```ruby
require 'net/http'
require 'benchmark'
Benchmark.realtime{100.times{Net::HTTP.get(URI.parse("http://localhost:9200/"))}}
```

These are the stats for the ruby code
```bash
time ruby test.rb 

real	0m0.243s
user	0m0.154s
sys	0m0.032s
```

I'm not sure as to what is the problem but it's performing pretty slowly for a single request.

**Comment by snoyberg** [comment]
I'm not familiar with Ruby's HTTP library. Is it doing the same thing as `simpleHttp`, in particular reading the entire response body into memory? Remember that simpleHttp is specifically *not* intended to be a performance-sensitive function, and that the rest of the module provides more efficient ways of doing things.

**Comment by abhipras** [comment]
@snoyberg Internally I'd have to explore a bit to know what's going around Ruby's `Net::HTTP`. What are the alternatives to `simpleHttpRequest` if I have to do a single internal API call for a request received? Shall I keep a persistent connection between the remote server and the client even after the completion of a request?

**Comment by abhipras** [comment]
@snoyberg I also did benchmarking in Go using `testing` package and found results similar to the Ruby version.

**Comment by snoyberg** [comment]
Here are the results I get comparing Ruby and Haskell:

```haskell
{-# LANGUAGE OverloadedStrings #-}
import Network.HTTP.Client
import Control.Monad

main :: IO ()
main = do
    man <- newManager defaultManagerSettings
    let req = "http://localhost:3000"
    replicateM_ 100 $ withResponse req man $ brConsume . responseBody
```

```ruby
require 'net/http'
100.times{Net::HTTP.get(URI.parse("http://localhost:3000/"))}
```

```
vagrant@vagrant-ubuntu-trusty-64:~/Desktop$ time ruby req.rb

real    0m0.146s
user    0m0.081s
sys     0m0.053s
vagrant@vagrant-ubuntu-trusty-64:~/Desktop$ cabal exec -- ghc -O2 -threaded req.hs && time ./req

real    0m0.045s
user    0m0.000s
sys     0m0.060s
vagrant@vagrant-ubuntu-trusty-64:~/Desktop$ time cabal exec -- runghc req.hs

real    0m0.510s
user    0m0.324s
sys     0m0.217s
```

**Comment by abhipras** [comment]
@snoyberg `simpleHTTP` indeed seems to be the culprit. Thanks for the example. I corrected my haskell code and verified the results which indeed match with your results. This doesn't seem to be the case with HTTPS Apis though. Can you show the results for `https` APIs?

The ruby code still wins easily for HTTPS calls. The haskell code is shown below.
```haskell
{-# LANGUAGE OverloadedStrings #-}
import Network.HTTP.Client
import Network.HTTP.Client.TLS
import Control.Monad

main :: IO ()
main = do
	req <- parseUrl "https://reddit.com"
	_resp <- withManager tlsManagerSettings (httpLbs req)
	return ()
```

Please correct me if I'm wrong but the above code performs rather poorly against Ruby

**Comment by snoyberg** [comment]
It doesn't surprise me too terribly that the TLS implementation isn't as fast. If desired, you could try using http-client-openssl instead.

Given that there doesn't appear to be a performance issue with http-client, I'm going to close this issue.
