### ISSUE TITLE
Support for user:pass in URLs

### ISSUE THREAD

**Issue by michaelneale** [snoyberg/http-client#120]
as per: https://www.ietf.org/rfc/rfc1738.txt

a valid URL could be: http://foo:bar@mysite.com

however parseUrl will not accept this as a valid URL. Ideally it would and automatically set the basic auth header in the Request returned.

**Comment by snoyberg** [comment]
No objection. Would you be interested in sending a PR for this feature?

**Comment by michaelneale** [comment]
I'll certainly take a look..

**Comment by davidsiefert** [comment]
@michaelneale hey if you haven't had a chance to look into this yet, @karun012 and myself are taking a stab at it.

**Comment by michaelneale** [comment]
Hi David - go ahead. I had it in my todo but as I found another way around
my specific problem it stayed on the todo ;).


If you don't get time in the next week let me know and I will take a look
again.

**Comment by davidsiefert** [comment]
@karun012 and I took a stab at it, committed to a fork.  Still need to clean-up stuff so some early feedback would be helpful. https://github.com/davidsiefert/http-client/commit/b23d66ef001c68fb5cbdea6fb9ca5a1521af1e9e

**Comment by davidsiefert** [comment]
encoded username/password per feedback.  a little tiny bit of cleanup too. https://github.com/snoyberg/http-client/commit/b23d66ef001c68fb5cbdea6fb9ca5a1521af1e9e

**Comment by snoyberg** [comment]
It would probably be easier to track and discuss this in a pull request, even if it's not quite ready for merge.

**Comment by bkaes** [comment]
#124 has been accepted, shouldn't this be closed?

**Comment by michaelneale** [comment]
Yes.
