### ISSUE TITLE
IRI support?

### ISSUE THREAD

**Issue by ppelleti** [snoyberg/http-client#121]
It appears that http-client supports IRIs, for the most part.  For example,

```haskell
import Network.HTTP.Client
import qualified Data.ByteString.Lazy as L

main = withManager defaultManagerSettings $ \mgr -> do
  req <- parseUrl "http://www.w3.org/International/articles/idn-and-iri/JP納豆/引き割り納豆.html"
  resp <- httpLbs req mgr
  L.putStr $ responseBody resp
```

prints out

```xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ja">
<head>
<title>Hikiwari Natto test page</title>
</head>
<body>

<h1>引き割り納豆</h1>

<p><img src="hikiwari.jpg" alt="hikiwari natto"/></p>

</body>
</html>
```

However, if there are non-ascii characters in the host name, it percent-encodes them, rather than using IDNA.  For example,

```haskell
import Network.HTTP.Client
import qualified Data.ByteString.Lazy as L

main = withManager defaultManagerSettings $ \mgr -> do
  req <- parseUrl "http://点心和烤鸭.w3.mag.keio.ac.jp"
  resp <- httpLbs req mgr
  L.putStr $ responseBody resp
```

prints out

```
iri-test: FailedConnectionException2 "%E7%82%B9%E5%BF%83%E5%92%8C%E7%83%A4%E9%B8%AD.w3.mag.keio.ac.jp" 80 False getAddrInfo: does not exist (nodename nor servname provided, or not known)
```

rather than the expected:

```html
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>点心和烤鸭.w3.mag.keio.ac.jp</title>
</head>
<body>
<p>点心和烤鸭.w3.mag.keio.ac.jp</p>
</body>
</html>
```

Is this a bug, or is parseUrl not meant to support IRIs?

**Comment by snoyberg** [comment]
I think both are true: this is not ideal behavior, but `parseUrl` was never written originally to support IRIs. Making this worse, the `network-uri` package doesn't seem to support IRIs either. I'd definitely accept a patch to try and address this situation, but I don't have ideas myself on how best to approach it, as I have no experience with IRIs.

**Comment by ppelleti** [comment]
I can't claim experience with IRIs, either, but I have read through [RFC 3987](https://tools.ietf.org/html/rfc3987).

Someone else has already asked the IRI question for the `network-uri` package, in haskell/network-uri#16, so it would probably be good to coordinate between the two.

It appears that the `escapeURIString isAllowedInURI` that parseUrl currently does:

https://github.com/snoyberg/http-client/blob/f851a8e48dbae9db3c40090f294af2d4ae51fa5b/http-client/Network/HTTP/Client/Request.hs#L82

already implements the algorithm for converting IRIs to URIs:

http://tools.ietf.org/html/rfc3987#section-3.1

The RFC goes on to say:

    Systems accepting IRIs MAY convert the ireg-name component of an IRI
    as follows (before step 2 above) for schemes known to use domain
    names in ireg-name, if the scheme definition does not allow
    percent-encoding for ireg-name:

But in order for the hostname lookup to succeed, it seems that this `MAY` is a necessity for HTTP IRIs.

The good news is that I've already written some code to handle this:

```haskell
import Control.Monad (forM)
import Control.Monad.Catch (MonadThrow, throwM)
import Network.HTTP.Client (HttpException (..), Request (..), getUri)
import qualified Data.ByteString.Char8 as B8
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Network.URI as U
import qualified Text.IDNA as I

idnaReq :: MonadThrow m => Request -> m Request
idnaReq req = do
    let unicode = T.pack $ U.unEscapeString $ B8.unpack $ host req
    labs <- forM (T.splitOn "." unicode) $ \label ->
      maybe (badness label) return $ I.toASCII True True label
    let newHost = T.intercalate "." labs
    return req { host = T.encodeUtf8 newHost }
  where badness label =
          let uri = show $ getUri req
              msg = "Invalid IDN label: " ++ T.unpack label
          in throwM $ InvalidUrlException uri msg
```

The bad news is that my code (which is essentially just glue) has a dependency on the [`idna`](http://hackage.haskell.org/package/idna) package, which is a fairly large dependency.  In particular, `idna` indirectly depends on [`text-icu`](http://hackage.haskell.org/package/text-icu), which means that there is an additional C library dependency of [ICU](http://site.icu-project.org/), besides the Haskell dependencies.

So, I don't know if `http-client` or `network-uri` would be willing to take on such a large dependency.  Perhaps the functionality for handling IRIs should go into a separate package, so the dependency is only incurred if the user wants this functionality?

There are some alternatives to using the `idna` package, but they all incur a dependency on a C library, too.  The fundamental problem is that the IDNA algorithm requires Unicode normalization, and as far as I can tell, there is no pure-Haskell library for Unicode normalization.

As of version 4.6, ICU already has a [full implementation of IDNA](http://icu-project.org/apiref/icu4c/uidna_8h.html).  Given that the `idna` package depends on ICU anyway, it might make more sense to just use ICU's IDNA functions.  In particular, the `idna` package implements IDNA2003, while ICU implements [TR46](http://www.unicode.org/reports/tr46/), which (as I understand it) is a profile of IDNA2008.

An alternative implementation is GNU libidn.  A Haskell binding already exists in the [`gnuidn`](http://hackage.haskell.org/package/gnuidn) package.  However, that binding is GPL licensed, even though the underlying C library is LGPL.

And on Windows, there's the [`IdnToAcii`](https://msdn.microsoft.com/en-us/library/windows/desktop/dd318149(v=vs.85).aspx) function.  But again, it seems to only support IDNA2003, not IDNA2008.

(Since this isn't my area of expertise, I don't know how important it is to support IDNA2008 versus IDNA2003.)

**Comment by snoyberg** [comment]
The dependency issue is an unfortunate one. My recommendation would be to put this code in a separate package, and have a link in the http-client documentation to point to it, with the explanation of the dependency keeping the code out of http-client itself. Sound reasonable?
