### ISSUE TITLE
Non 2xx responses while benchmarking with wrk

### ISSUE THREAD

**Issue by abhipras** [snoyberg/http-client#122]
I have a `Scotty` api server set up which uses `http-client` to fetch results from a remote url to serve requests. When benchmarked with `wrk` it gives lots of non 200(500) status code responses. 

To check that the remote web server was not the issue, I set up another Scotty api server serving dummy responses on the same host.

Code for dummy API server capable of handling high rps
```haskell
{-# LANGUAGE OverloadedStrings #-}


import Web.Scotty

import Network.Wai.Middleware.RequestLogger 

import Control.Monad
import Data.Text
import Control.Monad.Trans
import Data.ByteString
import Network.HTTP.Types (status302)
import Data.Time.Clock
import Data.Text.Lazy.Encoding (decodeUtf8)
import Control.Concurrent
import Network.HTTP.Conduit
import Network.Connection (TLSSettings (..))
import Network.HTTP.Client
import Network
main = do 
  scotty 4001 $ do
	middleware logStdoutDev
	get "/dummy_api" $ do
		text $ "dummy response"
```

Code for the server calling dummy server and serving responses
```haskell
{-# LANGUAGE OverloadedStrings #-}


import Web.Scotty

import Network.Wai.Middleware.RequestLogger 

import Control.Monad
import Control.Monad.Trans
import qualified Data.Text.Internal.Lazy as LT
import Data.ByteString
import Network.HTTP.Types (status302)
import Data.Time.Clock
import Data.Text.Lazy.Encoding (decodeUtf8)
import Control.Concurrent
import qualified Data.ByteString.Lazy as LB
import Network.HTTP.Conduit
import Network.Connection (TLSSettings (..))
import Network.HTTP.Client
import Network


main = do 
  let man = newManager defaultManagerSettings 
  scotty 3000 $ do
	middleware logStdoutDev

	get "/filters" $ do
		response <- liftIO $! (testGet man)
		json $ decodeUtf8 (LB.fromChunks response)

testGet :: IO Manager -> IO [B.ByteString]
testGet manager = do
	request <- parseUrl "http://localhost:4001/dummy_api"
	man <- manager
	let req = request { method = "GET", responseTimeout = Nothing, redirectCount = 0}
	a <- withResponse req man $ brConsume . responseBody
	return $! a
```

It works fine normally and gives 200 status code responses but benchmarking with `wrk` results is lots of 500 responses if `http-client` is involved. 

```bash
wrk -t30 -c100 -d30s "http://localhost:3000/filters"
Running 30s test @ http://localhost:3000/filters
  30 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    47.21ms  106.94ms   1.21s    97.14%
    Req/Sec    95.91     22.44   180.00     76.34%
  77449 requests in 30.08s, 24.59MB read
  Socket errors: connect 0, read 0, write 0, timeout 104
  Non-2xx or 3xx responses: 76041
Requests/sec:   2574.40
Transfer/sec:    837.10KB

```
The dummy api server doesn't give any non 200 responses when benchmarked with `wrk` which led me to conclude that there appears to be some issue with `http-client` related to timeout.

**Comment by snoyberg** [comment]
I can't proceed based on the information provided here. As it stands, there's a repro using a separate library built on top of http-client, but no repro for http-client itself. This also doesn't contain any information on what the 500 error itself is.

**Comment by abhipras** [comment]
Can you help me repro this problem using http-client? Given the bug which occurs in high concurrency scenarios I couldn't figure out a way to repro this problem using only this library.
Also everything works fine when http-client part of code is removed.
I am trying to catch exceptions currently. I will update the code accordingly. Any kind of help is heartily appreciated.

**Comment by snoyberg** [comment]
One method would be to modify the wrk codebase to log the 500 error responses. Another would be to use http-client in a high concurrency setup. A third would be to modify the web server to log what it's sending as a 500 response.

**Comment by abhijitiitr** [comment]
I was able to catch the error and all the errors contain a single message

FailedConnectionException2 "localhost" 4001 False getAddrInfo: does not exist (nodename nor servname provided, or not known)

**Comment by snoyberg** [comment]
That's usually from running out of file descriptors. Can you check what
your limits are?

**Comment by abhijitiitr** [comment]
ulimit -n returns 256. Is it too low?

**Comment by snoyberg** [comment]
Depends on how many connections you want to have. But for my usage, that's
about two orders of magnitude too low.

**Comment by abhijitiitr** [comment]
ulimit -n 10240 brought huge improvement is non 200 responses but didn't eliminate them. Also the throughput decreased drastically. Ideally I think it should have been a part of the `http-conduit` library to handle the cases when the server runs out of file descriptors. 

Lots of errors also belong to `NoResponseDataReceived` category. How can I fix these errors?

**Comment by snoyberg** [comment]
> Also the throughput decreased drastically

That's not really surprising. It takes a lot less time to get a "no file descriptors" available error from the OS than to perform a request

> Ideally I think it should have been a part of the `http-conduit` library to handle the cases when the server runs out of file descriptors.

How would that work?

> Lots of errors also belong to `NoResponseDataReceived` category. How can I fix these errors?

I don't know, you haven't provided any details.

**Comment by abhijitiitr** [comment]
`NoResponseDataReceived` is constructor of `HttpException`. I couldn't get any more info.

I think this issue can be closed.

**Comment by abhijitiitr** [comment]
Thanks a lot for all the help you have provided. I'm a newbie to Haskell and I could imagine the trouble you took to answer silly queries of mine.

Lastly, I just want to wander around the issue and request you to answer this [question](http://stackoverflow.com/questions/30611005/haskell-scotty-low-throughput-in-network-i-o?noredirect=1#comment49298322_30611005). I apologize for any kind of mistake I might have made.

**Comment by snoyberg** [comment]
If http-client is not returning 500s when run against a different server, I'm not sure what support I can provide. Perhaps you should speak with the Scotty team?

**Comment by abhijitiitr** [comment]
Can you state the server where `http-client` performs normally?

**Comment by abhijitiitr** [comment]
@snoyberg I finally was able to find the issue. The first line after the definition of `main` block 
```haskell
let man = newManager defaultManagerSettings 
```

was the culprit. I changed it to

```haskell
man <- newManager defaultSettings
```
 and the non 200 response and the extremely high memory usage issue were gone.

However I can't find a reason why that line was culprit. Can you provide one please?

**Comment by snoyberg** [comment]
No, I have no idea.
