### ISSUE TITLE
withManager's use of runResourceT makes it needlessly painful to work with non-ResourceT monads

### ISSUE THREAD

**Issue by merijn** [snoyberg/http-client#125]
I was trying to hack together a quick and dirty webscraper and ended up using Concurrently from async as my base monad. I initially used simpleHttp, but decided to move to a "better" implementation using http/httpLbs, unfortunately I ran into problems with withManager. It insist on a  function `Manager -> ResourceT m a`, because it uses `runResourceT`, but i don't see any compelling why it requires that? People who have a ResourceT can easily compose with runResourceT. By using runResourceT internally it becomes impossible to use withManager with monads like Concurrently (since there is no MonadIO/MonadBaseControl m IO instance for Concurrently, which runResourceT requires).

**Comment by snoyberg** [comment]
I agree, it's there for legacy reasons with how the function used to work.
We should probably just deprecate withManager, as using newManager is
perfectly safe. You interested in sending a pull request for that?
