### ISSUE TITLE
system proxy prevents specifying a port with http-client?

### ISSUE THREAD

**Issue by mmaz** [snoyberg/http-client#127]
Hi! To preface, my apologies if (from my networking inexperience) the following is actually a non-issue, or simply should be reported to a different project. I'm getting strange `FailedConnectionException2` exceptions when a system proxy is set. On OS X 10.10 Yosemite, I installed [`wreq`](http://hackage.haskell.org/package/wreq) using `lts-2.15` with stack. Network requests resolve *correctly* for requests on different ports, like 3000, when I **do not** have a system proxy configured (on my home machine):

```bash
$ stack ghci
Prelude> :m Network.Wreq
Prelude Network.Wreq> get "http://localhost:3000"
```
And if I don't have a server running, I get a sensible exception:

```
*** Exception: FailedConnectionException2 "localhost" 3000 False connect: does not exist (Connection refused
```

where port 3000 is given as parameter 2 of `FailedConnectionException2`. But under nearly the same conditions (the only difference being OSX 10.9 Mavericks on my work laptop), when I do have a system proxy set (`Apple → System Preferences → Network → $ACTIVE_INTERFACE → Advanced... → Proxies tab → Automatic Proxy Configuration → http://..../proxy.pac` ) on my network interface, requests using `http-client` do **not** resolve (strangely, as if they all try only port 80). So, even when I explicitly disable all my environment variables in my bash shell, like so:

```bash
$ http_proxy= https_proxy= HTTP_PROXY= HTTPS_PROXY= no_proxy= NO_PROXY= stack ghci
Prelude> :m Network.Wreq
Prelude Network.Wreq> get "http://localhost:3000"
```
I get the following incorrect exception: 

```
*** Exception: FailedConnectionException2 "localhost" 80 False connect: does not exist (Connection refused
```
where the exception is unexpectedly mentioning port **80** instead of 3000, even if

```
$ curl -v --noproxy localhost http://localhost:3000/
```

successfully resolves a locally hosted directory (with either `warp` or the traditional `python -m SimpleHTTPServer 3000`).

Any suggestions? If it helps to mention, my code which successfully ran last year (depending on `wreq == 0.2.0.0` in the cabal file) has stopped working on my system after recompiling, so I assume it's with the underlying dependency on `http-client` (`wreq-0.2.0.0` does not have any upper version-bound on `http-client` from what I see on hackage). Many thanks!

**Comment by snoyberg** [comment]
Can you try `unset http_proxy` and the like instead? If the works, we should probably tweak http-client to ignore empty strings for these environment variables.

**Comment by mmaz** [comment]
`unset` with `http_proxy` works! Thanks, I hadn't considered trying that. As a fix, should the case for `Just ""` be equivalent to the case for `Nothing` [here](https://github.com/snoyberg/http-client/blob/76bf188cea7703531fb6020d905914538f57f1bb/http-client/Network/HTTP/Client/Manager.hs#L488)? Is support for `no_proxy` also worth consideration?

**Comment by snoyberg** [comment]
Yes, that's what I'm thinking. I've never heard of `no_proxy` before, do you have a reference for it somewhere?

**Comment by snoyberg** [comment]
And am I to take it from your question that you're planning on sending a PR for modifying the `http_proxy` behavior?

**Comment by mmaz** [comment]
Yes, I would be happy to submit a PR for adding the case statement this evening (I hope the delay is not a bother)! 

Regarding the other question, [`no_proxy`/`NO_PROXY`](http://www.gnu.org/software/emacs/manual/html_node/url/Proxies.html) is not very common, but commandline tools do sometimes respect it in order to support corporate development environments; for instance `pub` for Google Dart. The [related issue](https://github.com/dart-lang/sdk/issues/15161#issuecomment-108404465) in Dart also notes that IPv4 and IPv6 syntaxes should both be respected. Thoughts?

**Comment by snoyberg** [comment]
The delay is not a problem at all.

I don't feel strongly about no_proxy. If it can be implemented easily
without breaking the current API, I'm OK with it.

**Comment by mmaz** [comment]
Thanks again for the advice; I limited the PR to only adding empty-string support for `http_proxy=` and I'll await your feedback on it. For now, I won't plan on submitting a (separate) PR to add support for `no_proxy` unless others +1 the request here or in a new issue.
