### ISSUE TITLE
Use uriUserInfo to communicate with the proxy

### ISSUE THREAD

**Issue by bkaes** [snoyberg/http-client#129]
The current [implementation of `envHelper`](https://github.com/snoyberg/http-client/blob/dc981b9fde57d77ccecf0171a96fb92c5cb5712f/http-client/Network/HTTP/Client/Manager.hs#L503-504) doesn't allow any user info in `http[s]_proxy`:

                auth <- U.uriAuthority uri
                guard $ null $ U.uriUserInfo auth

This has been addressed in two StackOverflow questions (see [1] and [2]) and affects both `http-conduit` and `stack`:

> Http.Conduit results in an exception with the error:

>      *** Exception: InvalidProxyEnvironmentVariable "http_proxy" "http://user:pass@proxy:port/"

> I'm trying to use stack behind a corporate proxy. Issuing the stack new command returns:

>     InvalidProxyEnvironmentVariable "http_proxy" "http://username:password@host:port/"

 [1]: http://stackoverflow.com/q/31138915/1139697 "Haskell Network.HTTP.Conduit Exception: InvalidProxyEnvironmentVariable “http_proxy”"
 [2]: http://stackoverflow.com/q/31135606/1139697 "Using commercialhaskell/stack with a proxy"

**Comment by snoyberg** [comment]
I'm about to get on a plane (or a train, to get a plane... you get the idea), so I can't dive into this right now. However, I think this isn't just the parsing of `http_proxy`, but rather the implementation of proxying does not allow for authentication currently. I'm not aware of the details necessary to make that work, it will require research. For others reading this:

* Pull requests definitely welcome
* If someone can add in necessary information on what's involved in authenticating to a proxy server, that would be great

**Comment by bkaes** [comment]
[RFC 2617] sec 3.6 suggest that one needs to set the Proxy-Authorization header as described in [RFC 2616]:

> ### 14.34 Proxy-Authorization

> The `Proxy-Authorization` request-header field allows the client to identify itself (or its user) to a proxy which requires authentication. The `Proxy-Authorization` field value consists of credentials containing the authentication information of the user agent for the proxy and/or realm of the resource being requested.

>     Proxy-Authorization     = "Proxy-Authorization" ":" credentials
> The HTTP access authentication process is described in "HTTP Authentication: Basic and Digest Access Authentication" \[rem: rfc2617\] . Unlike Authorization, the `Proxy-Authorization` header field applies only to the next outbound proxy that demanded authentication using the `Proxy-Authenticate` field. When multiple proxies are used in a chain, the `Proxy-Authorization` header field is consumed by the first outbound proxy that was expecting to receive credentials. A proxy MAY relay the credentials from the client request to the next proxy if that is the mechanism by which the proxies cooperatively authenticate a given request.

Hope that helps.

> I'm about to get on a plane (or a train, to get a plane... you get the idea), so I can't dive into this right now. 

No worries, I just saw your comment on StackOverflow ("This is worth opening as an http-client issue") and had a some time to spare.

 [RFC 2617]: https://tools.ietf.org/html/rfc2617#page-19
 [RFC 2616]: https://tools.ietf.org/html/rfc2616#section-14.34 "HTTP/1.1 sec"

**Comment by snoyberg** [comment]
Thanks for the very helpful comment, thank you :)

**Comment by snoyberg** [comment]
Turns out I'm simultaneously more and less dumb than I thought I was:

* More dumb: we already have a `applyBasicProxyAuth` function in http-client
* Less dumb: the environment variable interface is flexible enough to support authentication without any breaking changes

I've pushed some changes for this, but don't want to release until someone else has tested (and when I know I won't be AFK for 36 hours straight over the Atlantic).

**Comment by snoyberg** [comment]
OK, this is now released to Hackage. Thanks again for reporting!
