### ISSUE TITLE
FailedConnectionException

### ISSUE THREAD

**Issue by hawkish** [snoyberg/http-client#131]
I sometimes get a FailedConnectionException running a series of request using http-conduit. Upgrading http-conduit to latest version doesn't seem to help. 

I'm currently using Debian Jessie, but as far as I can tell OS X Yosemite doesn't have the same issue.

There is an example of the code here: https://github.com/hawkish/platescraping. Just run main.

This user seems to have had a similar issue http://stackoverflow.com/questions/20017484/http-conduit-frequent-connection-failures

**Comment by snoyberg** [comment]
Can you see if changing the timeout value makes a difference?

**Comment by hawkish** [comment]
Actually increasing the timeout to 1 minute seems to have solved the issue. At least now I'm not getting any FailedConnectionExceptions. Any idea of why the requests are *that* slow? When I test the same steps in a browser the response seems to be quicker.

**Comment by snoyberg** [comment]
If you're hitting the server with a lot of requests, they may be throttling you.

**Comment by hawkish** [comment]
Yeah. That might be it. It can't be me not using the runResourceT, can it?

**Comment by snoyberg** [comment]
Not any way I can see it being related. Any opposition to closing this issue then?

**Comment by hawkish** [comment]
No. You can close it. And thank you for http-conduit by the way. I think it is one of the nicest APIs for this kind of job.

**Comment by snoyberg** [comment]
Thanks!
