### ISSUE TITLE
Proxy authentication does not work for HTTPS.

### ISSUE THREAD

**Issue by vasiliyl** [snoyberg/http-client#132]
When connecting to HTTPS via proxy `Proxy-Authorization` header is not sent.
Proxy authentication for HTTPS should work the same way as for HTTP.

I'm behind the proxy with authentication right now, `https_proxy` environment variable is set to `http://user:pass@proxy:3128`, and here is what I get with stack: 

    $ stack build        
    Downloading nightly-2015-06-12 build plan ...ProxyConnectException "raw.githubusercontent.com" 443 (Left "StatusHeaders (Status {statusCode = 407, statusMessage = \"Proxy Authentication Required\"}) <...some more headers...>

Here is dump of stack's request:

    CONNECT raw.githubusercontent.com:443 HTTP/1.1

Here is dump of request done with curl which works fine:

    CONNECT raw.githubusercontent.com:443 HTTP/1.1\r\n
    Host: raw.githubusercontent.com:443\r\n
    Proxy-Authorization: Basic dXNlcjpwYXNz\r\n
    User-Agent: curl/7.42.1\r\n
    Proxy-Connection: Keep-Alive\r\n

**Comment by snoyberg** [comment]
I'm not well set up to test this. Would you be able to take a stab at this? The change should be pretty trivial, just modify the `CONNECT` call in Network.HTTP.Client.Manager to respect the `proxy-authentication` header in `requestHeaders`.

**Comment by vasiliyl** [comment]
I created merge request #133, it works for me. The code is trivial, but I'm new to haskell, please comment if there is a better solution.

**Comment by snoyberg** [comment]
Merged to master, closing as resolved. If there are still issues, please report. Thanks for the PR!
