### ISSUE TITLE
Environment variables case-insensitive under Windows

### ISSUE THREAD

**Issue by varosi** [snoyberg/http-client#135]
In Windows "HTTPS_PROXY", "https_proxy" and "HTTPS_proxy" are the same and it doesn't distinguish differences. The same is for file names, too.

It will be great if under Windows http-client is case-insensitive to env. variables, too. That way will be even more compatible with different set of possible configurations.

**Comment by snoyberg** [comment]
I just pushed a commit that should implement this, can you test master?
