### ISSUE TITLE
Don't use withManager in the examples

### ISSUE THREAD

**Issue by ndmitchell** [snoyberg/http-client#136]
You still use withManager in the docs at the top of Network.HTTP.Conduit, despite it being deprecated. Avoid recommending users to use it.

**Comment by snoyberg** [comment]
Good call, implemented in 32b02a7

**Comment by redneb** [comment]
There are two more references: in `http-client/README.md` and in the module documentation at the top in `Network/HTTP/Client.hs`.

**Comment by snoyberg** [comment]
I'm not going to be at a computer for a bit. Would you mind sending a pull
request on those?
