### ISSUE TITLE
Do something like withManager

### ISSUE THREAD

**Issue by ndmitchell** [snoyberg/http-client#137]
It seems a little weird that you have a creation function (newManager) and a closing function (closeManager), but no function that lets me do something using the `with` pattern. I'm not sure I get why `withManager` has to die? Is `closeManager` no longer necessary? If not, `withManager` seems like it has value, even if @merijn might not want to be using it in his example.

From #125 originally.

**Comment by snoyberg** [comment]
That's a good point: we should deprecate `closeManager` too. The point is that the lifetime of the `Manager` is handled automatically, and manually closing things out is not necessary. This is similar to how in [resource-pool](http://haddock.stackage.org/nightly-2015-07-19/resource-pool-0.2.3.2/Data-Pool.html), you can create a pool but not destroy one.

**Comment by ndmitchell** [comment]
That's fine then - I suggest doing it immediately and making clear in the docs. Perhaps rewrite `withManager` to not call `closeManager`, since one way of fixing deprecated warnings is to inline the function that is deprecated and refactor from there (that's what I always do).

**Comment by snoyberg** [comment]
Agreed, that makes sense. Mind looking at 32b02a7 before I release?

**Comment by ndmitchell** [comment]
I've made a bunch of line notes.

**Comment by ndmitchell** [comment]
All looks good now. Still conceptually weird to see you suggesting people rely on the GC for resource finalisation :)

**Comment by snoyberg** [comment]
True, it is quite different from what I typically recommend. If you look at the internals of how this all works, it will make a lot more sense: the manager puts itself to sleep when unused, wakes up when used again, and when all references disappear, is garbage collected. You *can* manually kill it early, but that's more likely to trigger a bug than anything else.

Alright, releasing the new version.
