### ISSUE TITLE
Support for NO_PROXY environment variable

### ISSUE THREAD

**Issue by hgiddens** [snoyberg/http-client#140]
As @mmaz mentioned in #127, `NO_PROXY` is supported by various tools to avoid involving the proxy for a selection of hosts. For example, in the environment I'm using http-client in, external services are only accessible via the proxy, whereas internal services are only accessible directly. Currently I'm working around this explicitly, but direct support for the `NO_PROXY` environment variable would mean that everything Just Works™.

Other tools that support the variable include:
* [Emacs](http://www.gnu.org/software/emacs/manual/html_node/url/Proxies.html) (as @mmaz mentioned)
* [Wget](http://www.gnu.org/software/wget/manual/html_node/Proxies.html)
* [cURL](http://curl.haxx.se/docs/manual.html)
* [Python](https://docs.python.org/2/library/urllib.html)

Other systems typically support the same functionality, although not necessarily via environment variables or with the same syntax. For example, [Java sports a `http.nonProxyHosts` system property](https://docs.oracle.com/javase/8/docs/api/java/net/doc-files/net-properties.html).

If you're ok with the idea I'll have a go at an implementation.

**Comment by snoyberg** [comment]
I am not familiar with the environment variable, but have no objection.
Pull request certainly welcome. Please try to include a link to relevant
specs in the comments.

**Comment by snoyberg** [comment]
Merged in #145, closing. Thanks!
