### ISSUE TITLE
how to print the actual request?

### ISSUE THREAD

**Issue by jwaldmann** [snoyberg/http-client#142]
what is the recommended way to print the actual request (bytestream) that is being sent, for debugging?
 
I can `print req` but then I don't see the cookies that are being sent (because they are computed by the manager?)

I would wireshark it but in my case it's https. I cannot just use some other (http) replacement server
because there is some session state that I cannot reproduce easily.

**Comment by snoyberg** [comment]
You can use managerTlsConnection to put in a proxy function that outputs
all data being sent to stdout as well as sending it to the server. I'm not
at my computer, so I can't give a code example of doing it, but I believe
this has been discussed on the mailing list before.

**Comment by ondrap** [comment]
I ended up using mitmproxy to find out a problem, seems to work nicely.
