### ISSUE TITLE
withManager is deprecated

### ISSUE THREAD

**Issue by ndmitchell** [snoyberg/http-client#144]
See http://hackage.haskell.org/package/http-client-0.4.18.1/docs/Network-HTTP-Client-MultipartFormData.html, which still encourages withManager.

**Comment by ndmitchell** [comment]
But it's a bit weird for http-client to give examples that require http-conduit. I must say, the conduit/client split seems a little confused - any chance of reducing it to one package with everything?

**Comment by ndmitchell** [comment]
I just got bitten by the fact that both conduit and client expose httpLbs, but with different types, so end up conflicting. Annoyance!

**Comment by snoyberg** [comment]
I'd love to merge them. People make my life absolutely miserable any time I
do anything like that though, because everyone's paranoid of
one-extra-dependency. The splits going to stay the way it is.

**Comment by ndmitchell** [comment]
Perhaps rename one http-client and one http-client-internal? The client vs conduit naming doesn't make it immediately obvious which is the on top one. And ideally make it that the _only_ reason to ever use http-client-internal is less dependencies? At the moment multipart is in http-client-internal only.

**Comment by snoyberg** [comment]
Ain't gonna happen, it's going to be a massive pain, break people's code, and will have people complaining afterwards "how dare you make http-client have a conduit dependency, that's so prejudiced!"

**Comment by ndmitchell** [comment]
If you do want to keep the separation (which it seems others want you to do at least!) then I suggest:

* The exports for http-client and examples be standalone. I see use of newManaher but can't obviously see that in http-client. 
* You reexport everything useful from http-conduit so people can use it without directly calling client. Multipart stuff was what bit me.

**Comment by snoyberg** [comment]
I think this is addressed by the new Network.HTTP.Simple module, which is pointed to by all relevant modules and READMEs.

**Comment by snoyberg** [comment]
Also relevant: https://github.com/commercialhaskell/jump/pull/10
