### ISSUE TITLE
support socks5 proxy specification via http_proxy variable

### ISSUE THREAD

**Issue by ibukanov** [snoyberg/http-client#153]
Curl and other libraries allow to specify socks5 proxy using [http_proxy variable](http://curl.haxx.se/docs/manpage.html#PROXY), like in:

```
socks5://host:port
socks5h://host:port
```

where the latter form forces DNS resolution over SOCKS protocol. It would be nice for http-client to support this. This way I could use programs compiled with http-client together with `ssh -D`.

**Comment by snoyberg** [comment]
I have no objection to such a feature, and it should be relatively easy to add to the existing environment variable parsing code. Want to take a crack at a PR?

**Comment by ibukanov** [comment]
My Haskell experience is too newbie for PT . In fact I was hit by that when tried to use Elm tools behind a firewall...

**Comment by RobertFischer** [comment]
@snoyberg -- I'm happy to take a swing at this. Can you give me a quick pointer so that I am moving in the right direction?

**Comment by RobertFischer** [comment]
(I believe this is the underlying issue for Stack not accepting my sock5 proxy, which is why I am motivated to fix it.)

**Comment by snoyberg** [comment]
Check out envHelper in https://github.com/snoyberg/http-client/blob/master/http-client/Network/HTTP/Client/Manager.hs

**Comment by RobertFischer** [comment]
PR submitted: https://github.com/snoyberg/http-client/pull/262

**Comment by snoyberg** [comment]
PR merged, thanks!

**Comment by kirelagin** [comment]
For any future readers who get as confused as I was: the tldr; is that after a couple of other changes the current situation is that `socks5://` in `http_proxy` works, but only with `newTlsManager` from `http-client-tls` (and _not_ with the simple manager from `http-client`).
