### ISSUE TITLE
ProxyConnectException constructor

### ISSUE THREAD

**Issue by jcristovao** [snoyberg/http-client#154]
Hi,
The type of the `HttpException` `ProxyConnectException` constructor is:

    ProxyConnectException ByteString Int (Either ByteString HttpException)	-- host/port

However, in the code only the Left side is ever used:

    sh@(StatusHeaders status _ _) <- parseStatusHeaders conn Nothing Nothing
    unless (status == status200) $
        throwIO $ ProxyConnectException ultHost ultPort $ Left $ S8.pack $ show sh

Wouldn't it actually be much more useful (and 'patern-matchable') to instead use `Right`?

    sh@(StatusHeaders status _ _) <- parseStatusHeaders conn Nothing Nothing
    unless (status == status200) $
        throwIO $ ProxyConnectException ultHost ultPort $ Right $ StatusCodeException status [] (CJ [])

Or even drop the Either all-togheter and just include an encapsulated HttpException?

**Comment by snoyberg** [comment]
I'd say to leave the types unchanged for the moment, at least until the next major version bump. Changing the code to use `Right` instead of `Left` seems like a good change, mind sending a PR?

**Comment by jcristovao** [comment]
PR sent, thanks!

**Comment by snoyberg** [comment]
Thanks!
