### ISSUE TITLE
Case insensitive cookie domain

### ISSUE THREAD

**Issue by ondrap** [snoyberg/http-client#158]
I'm implementing some service with 'so-called' enterprise CAS authentication... anyway, the process goes through several 302-type redirects and cookie settings on the way. Some of the URLs in the Location are uppercase (great Windows systems...), so the `domain` part of the `Cookie` ends up being uppercase. When I next issue another statement to the lowercase domain, the cookie is not sent. Shouldn't the cookies (or the `domainMatches`) be case insensitive on the domain name? IMO DNS names generally should be treated as ASCII case insensitive.

On a related note: when some redirects happen during a request, is there a way to extract the last request that lead to the response?

**Comment by snoyberg** [comment]
Check out withReaponseHistory for getting intermediate requests.

I agree, domain name handling should be case insensitive. I haven't touched
that code myself, but I doubt that should be too difficult to change.
Interested in taking a stab at a PR?

**Comment by ondrap** [comment]
Ok, I will try to make one. It seems to me the best way would be changing the type to `cookieDomain :: CI ByteString` from case-insensitive.  Is that OK or would you rather not change the type?

**Comment by snoyberg** [comment]
I'd rather avoid a breaking change

**Comment by snoyberg** [comment]
PR merged, thanks!
