### ISSUE TITLE
http-client & http-client-tls: Simple way to add a CA certificate?

### ISSUE THREAD

**Issue by MaxDaten** [snoyberg/http-client#164]
Hi,

first of all, thanks for this set of libraries. I'm not sure if this is the correct repository or if I should post this request into the `tls` package. But the `tls` package seems to me to be more low level, but my request is a more a high level one.

For an API request, i need to add an custom created CA certificate to the request. With curl it's simple: `curl --cacert path/to/ca.cert https://example.com`. For the `http-client` I found [this](http://stackoverflow.com/questions/25833305/accepting-specific-certificate-with-http-client-tls-or-tls) on SO. But to be honest: this seems not very practical for me.

I stared couple of minutes onto `ClientParams` (which is without a `Default` implementation intentionally?) and `ClientHook` but I'm still not sure how to add one certificate. Both constructors seem to be very near to the implementation, they are not really simple or high level. But maybe I missed a simple way? The ideal way would be an curl equivalent. I think, doing security right should be simple as possible.

I'm looking forward to any advice, and willing to help. Thanks.

**Comment by snoyberg** [comment]
Sorry, I'm not familiar enough with the tls package to know how to do this.
All I know is that it's possible to completely disable CA checks.

**Comment by MaxDaten** [comment]
Okay thanks anyway. Yes, currently I disabled the CA check as an intermediate solution. Maybe I will figure it out how to do it correctly and can contribute a simple access to this or the `tls` package.

**Comment by jprider63** [comment]
For future reference, it looks like you should be able to specify a CA by constructing a `TLSSettings` and passing it into `mkManagerSettings`. You can find an example of this [here](https://github.com/glguy/irc-core/blob/master/driver/Connection.hs#L67).
