### ISSUE TITLE
TlsExceptionHostPort (HandshakeFailed (Error_Packet_unexpected "Alert [(AlertLevel_Fatal,BadRecordMac)]" " expected: change cipher"))

### ISSUE THREAD

**Issue by glasserc** [snoyberg/http-client#165]
[This gist](https://gist.github.com/glasserc/3f867fb9538d64fcd63d) reproduces a failure I saw using the [twitter-conduit](https://hackage.haskell.org/package/twitter-conduit) library with the [parallel-io](https://hackage.haskell.org/package/parallel-io) library. Depending on the value chosen for `numThreads`, I either get success, or a variety of interesting error messages, such as (with n=250):

```
many-tls: TlsExceptionHostPort (HandshakeFailed (Error_Packet_unexpected "Alert [(AlertLevel_Fatal,BadRecordMac)]" " expected: change cipher")) "www.google.com" 443
```

With n=1000:

```
many-tls: FailedConnectionException2 "www.google.com" 443 True <socket: 432>: hPutBuf: resource vanished (Broken pipe)
many-tls: TlsExceptionHostPort (HandshakeFailed Error_EOF) "www.google.com" 443
```

I'm concerned that I'm hitting some kind of race condition where the TLS negotiation on multiple connections to the same server is happening in two different threads. Have you ever seen this? Is there a better way to do what I'm trying to do? I've tried replacing the `withResponse` call to an `httpLbs` call and the errors persist, although maybe in different proportions.

**Comment by snoyberg** [comment]
Can you follow the debugging steps listed on the tls package's Github page?

**Comment by glasserc** [comment]
Thanks, that was extremely helpful. Doing `for x in `seq 1 250`; do .cabal-sandbox/bin/tls-retrievecertificate  --verify --chain www.google.com 443 > google-$x.txt & done` generated a few of these:

```
tls-retrievecertificate: HandshakeFailed (Error_Packet_unexpected "Alert [(AlertLevel_Fatal,BadRecordMac)]" " expected: change cipher")
```

I'm not sure what exactly to make of this error but it's clearly not related to the http-client libraries.

**Comment by ianbamforth** [comment]
@glasserc - did you ever resolve your issue?  Seeing similar thing here.

**Comment by glasserc** [comment]
See https://github.com/vincenthz/hs-tls/issues/124. At work we just manually pin the TLS library to the 1.2.x series, which seems not to have this problem.
