### ISSUE TITLE
Get a misleading FailedConnectionException2 when CA certificates are not correctly installed

### ISSUE THREAD

**Issue by abailly** [snoyberg/http-client#167]
I am using http-client through wreq and ran into issue https://github.com/bos/wreq/issues/5 : Wreq fails to connect to remote host because it cannot find CA certificates. I run wreq inside a minimal docker container based on https://github.com/fpco/haskell-scratch. 

The problem is that wreq reports a `FailedConnectionException2` with an error message suggesting it cannot resolve the host's name, which is misleading.

**Comment by snoyberg** [comment]
What makes you believe this is a certificate issue? The comments over there (and my own experience) lead me to believe this is due to a missing protocols file, and therefore http-client not knowing how to make a TCP connection.

**Comment by abailly** [comment]
Because the protocols file are there: I have added them myself with https://github.com/fpco/haskell-scratch/commit/b495bcf0f8fad3e869280f47bff160f7636c6c89 
But I may be wrong for another reason I overlooked. I will try to provide a minimal test case later on today.

**Comment by snoyberg** [comment]
There was no follow-up on this issue, closing. If the issue persists and there's a minimal test case, please reopen.
