### ISSUE TITLE
connectionReadLine seems wrong, or it is used incorrectly, perhaps resulting in a poor error message.

### ISSUE THREAD

**Issue by christian-marie** [snoyberg/http-client#168]
I want to work out what's going on here before attempting to fix anything.

Whilst using http-client with some long-running chunked encoding GET requests, I started seeing IncompleteHeaders exceptions at a point in time when I expected headers to have long since been received.

Digging further, I came upon this in Connection.hs: 
https://github.com/snoyberg/http-client/blob/bfb355d25b209bf94a26b9cb7b60e6bca4a46b36/http-client/Network/HTTP/Client/Connection.hs#L27

```haskell
connectionReadLine :: Connection -> IO ByteString
connectionReadLine conn = do
    bs <- connectionRead conn
    when (S.null bs) $ throwIO IncompleteHeaders
    connectionReadLineWith conn bs
```

Now, in Body.hs, connectionReadLine is used like so:
https://github.com/snoyberg/http-client/blob/bfb355d25b209bf94a26b9cb7b60e6bca4a46b36/http-client/Network/HTTP/Client/Body.hs#L182

```haskell
    requireNewline = do
        bs <- connectionReadLine conn
        unless (S.null bs) $ throwIO InvalidChunkHeaders
```

Does it make sense to you why this appears to work in practice? I'm a little confused by it and have either missed something, or something is broken.

**Comment by christian-marie** [comment]
Hmmn, I'm going to temporarily close this whilst I read through and understand connectionReadLineWith, which I missed.

**Comment by goertzenator** [comment]
I just ran into this when dealing with a long running chunked endpoint that times out after an hour.  I agree with @christian-marie 's assessment, and will add that it doesn't matter what `connectionReadLineWith` does as the issue has manifested by then.

Please reopen this issue; I'd like to do a PR.
