### ISSUE TITLE
withResponseHistory: recv: invalid argument (Bad file descriptor)

### ISSUE THREAD

**Issue by dzhus** [snoyberg/http-client#169]
I'm experiencing the following issue with http-client-0.4.24, on Mac OS X 10.10.5 and Ubuntu 14.04.

```haskell
import Prelude
import Network.HTTP.Client

followUrl' :: Manager
           -> String
           -> IO String
followUrl' mgr url = do
    req <- parseUrl url
    withResponseHistory req mgr $ \hr ->
        return $ show $ getUri $ hrFinalRequest hr
```

This fails with `Bad file descriptor` error for URLs which produce 404s:
```
λ> newManager defaultManagerSettings >>= (\m -> parseUrl "http://www.nytimes.com/2015/12/11/" >>= \r -> httpLbs r m)
*** Exception: StatusCodeException (Status {statusCode = 404, statusMessage = "Not Found"}) [("Server","Apache"),("X-App-Name","error"),...
λ> newManager defaultManagerSettings >>= (`followUrl'` "http://www.nytimes.com/2015/12/11/")
*** Exception: recv: invalid argument (Bad file descriptor)
```

Any ideas?

**Comment by snoyberg** [comment]
Some initial information:

1. I can reproduce the problem
2. This doesn't seem to be a general problem with 404 responses, but rather specific to nytimes.com

**Comment by snoyberg** [comment]
I've pushed a commit to master which should address the problem, can you give it a shot?

**Comment by dzhus** [comment]
Thank you Michael, I think you've fixed it – the bug does not occur anymore.

Another URLs I've seen it happen with: 
- `http://dw.com/p/1HLgB?tw`
- `http://eonli.ne/1NProGo`
- `http://martha.ms/6011BTtHJ`
- `http://ss1.us/a/J09vNDCu`
- `http://uk.reuters.com/article/idUKKBN0TT18820151210`

**Comment by snoyberg** [comment]
Cool, thanks for confirming. Uploaded to Hackage and closing.

**Comment by Yuras** [comment]
Just saw it in the changelog on hackage. I think here we have bigger issue: we are trying to read from already closed socket, which is unsafe.

According to [docs](http://hackage.haskell.org/package/network-2.6.2.1/docs/Network-Socket.html#v:close), any operation on closed socket will fail, but it is [not always the case](https://github.com/haskell/network/issues/169). In this particular case, `recv` may return data from an arbitrary connection which reused the same `FD`. It is horrible and almost impossible to debug. You may argue that it is unlikely, but I saw it in [practice](https://github.com/jaspervdj/websockets/issues/75#issuecomment-106800960).

The solution could be to check status before reading from or writing to socket.

**Comment by snoyberg** [comment]
This is news to me, I was under the impression that the calls in network would prevent this via their usage of `MVar`, but I suppose not. Would you be able to either:

1. Open up a new issue about this, or (better yet)
2. Send a PR to do the checking that you describe?
