### ISSUE TITLE
https_proxy env. variable with protocol is not supported

### ISSUE THREAD

**Issue by varosi** [snoyberg/http-client#175]
http-client-tls-0.2.2 on Windows 8.1 and CentOS 6.x

If I have "https_proxy" environment variable with protocol "https" in it then it throws me exception:
InvalidProxyEnvironmentVariable "https_proxy" "https://10.0.0.1:1111"

If I remove protocol as "10.0.0.1:1111" everything works. By default CentOS is using protocols in proxy env. variable. 

I saw similar issue (#129) fixed in 0.4.15, but yet it is not fixing this problem fully for some reason.

**Comment by snoyberg** [comment]
This seems like correct behavior. http-client does not support connecting to proxy servers over SSL connections. Can you try setting `https_proxy` to `http://10.0.0.1:1111`?

**Comment by varosi** [comment]
Sorry, the issue should be for http-client-tls. I'm actually using "Network.Wreq" from wreq library which is using http-client and http-client-tls accordingly.

**Comment by varosi** [comment]
Ops, http-client-tls is in this same repo.

**Comment by varosi** [comment]
with https_proxy=http://10.0.0.1:1111 (without 's') it is working. But it should work with "https" as well.

**Comment by snoyberg** [comment]
Why do you say it should work with https? Is your proxy server expecting connections over an SSL-secured connection?

**Comment by varosi** [comment]
Yes, our company proxy server accept both non-SSL and SSL connections. We could have even separate ports depending on the protocol.

**Comment by snoyberg** [comment]
And http-client does not support talking to proxy servers over SSL, which
is why the value you've provided isn't accepted.

**Comment by varosi** [comment]
Yes, I know that http-proxy library doesn't support it, but http-client-tls does support it. This issue is actually for http-client-tls that is dependency of "wreq" library that I actually use.

**Comment by snoyberg** [comment]
Alright, please send a PR if you're certain this is working the way you expect it to. I don't have a setup to check your claims.

**Comment by varosi** [comment]
I'll test whatever you need here. 
What is "PR"?

**Comment by snoyberg** [comment]
Pull request

**Comment by varosi** [comment]
In future I will try to learn how this project work and create a patch for that issue. I hope that someone faster than me could fix it sooner.

**Comment by snoyberg** [comment]
HTTPS proxies are working as expected for now, as described above. Closing.

**Comment by MatthewRalston** [comment]
FWIW, I still have this issue with stack 1.5.1 and ghci 2.0.0.2. First I get an invalid proxy variable error if my proxy setup (specifically only the https_proxy variable) is present in the environment, and when I remove it, I get a timeout error against s3 for haddock.stackage.com/snapshots.json when running `stack setup`.


```bash
>stack --version
Version 1.5.1, Git revision 600c1f01435a10d127938709556c1682ecfd694e (4861 commits) x86_64 hpack-0.17.1
>stack setup
Writing implicit global project config file to: /home/matt/.stack/global-project/stack.yaml
Note: You can change the snapshot via the resolver field there.
HttpExceptionContentWrapper {unHttpExceptionContentWrapper = InvalidProxyEnvironmentVariable "https_proxy" "https://proxy-server.example.com:1234"}
>export https_proxy=
>stack setup
Writing implicit global project config file to: /home/ralstonm/.stack/global-project/stack.yaml
Note: You can change the snapshot via the resolver field there.
HttpExceptionRequest Request {
  host                 = "s3.amazonaws.com"
  port                 = 443
  secure               = True
  requestHeaders       = []
  path                 = "/haddock.stackage.org/snapshots.json"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 ConnectionTimeout
>export https_proxy=$HTTPS_PROXY
>wget https://s3.amazonaws.com/haddock.stackage.org/snapshots.json
Resolving proxy-server.example.com... 1.9.8.8, 1.9.8.8
Connecting to proxy-server.example.com|1.9.8.8|:1234... connected.
Proxy request sent, awaiting response... 200 OK
Length: 235 [application/json]
Saving to: “snapshots.json”

100%[===============================================================================================================================================================================================>] 235         --.-K/s   in 0s

2017-09-26 10:45:15 (1.67 MB/s) - “snapshots.json” saved [235/235]
```

**Comment by m5** [comment]
> HTTPS proxies are working as expected for now, as described above. Closing.

To confirm: You mean HTTPS proxies are not currently expected to work, correct? 

My use case is a proxy that requires authentication credentials which I'd like to send over HTTPS.

**Comment by snoyberg** [comment]
Yes, that's what I meant. PRs welcome to improve the situation in the library if desired.
