### ISSUE TITLE
managerModifyRequest cannot override Request.checkStatus

### ISSUE THREAD

**Issue by nikomi** [snoyberg/http-client#176]
We are trying to use ```Network.HTTP.Client.Manager.managerModifyRequest``` to modify all requests coming into the manager. This works well for ```getConnectionWrapper``` but doesn't work for ```checkStatus```.

Looking at the sources we found that ```responseOpen``` calls ```httpRaw``` which calls ```managerModifyRequest``` - but this modification is lost when ```httpRaw``` ends, and ```responseOpen``` then calls ```checkStatus``` from the original request.

Do you see any chance to make an override of ```checkStatus``` work, e.g. by having ```httpRaw``` return the modified request to ```responseOpen```?

**Comment by nikomi** [comment]
I'm aware that ```httpRaw``` is an externally visible API function and should not change, therefore I'd probably do something like this:

* rename ```httpRaw``` to httpRaw'``` and let it return a tuple ```(res, req)``` incl. the modified request
* add a new function ```httpRaw = fmap fst httpRaw'``` (sample is missing parameters)
* let ```responseOpen``` use ```checkStatus``` from the modified request now returned by ```httpRaw```

I'm pretty sure you can solve this yourself, just wanted to spare you the time in case you don't want to :-)

BTW: in case you are wondering - we want to implement a circuit breaker, (almost) transparently usable by our Manager clients.

**Comment by snoyberg** [comment]
I think changing the behavior of `httpRaw` in this case is acceptable for two reasons:

1. It's exposed from an Internal module, so relying on it having specific functionality is expected to be dangerous
2. It looks to me like you're simply fixing a bug, in that the current behavior is wrong

I'd accept a pull request that makes this change. Even better would be an added test case as well demonstrating the currently problematic behavior.

Thanks!

**Comment by snoyberg** [comment]
Resolved via PR #179, thanks!
