### ISSUE TITLE
Working with cookies on client and server side

### ISSUE THREAD

**Issue by abailly** [snoyberg/http-client#181]
Hello,

I am encountering an issue while working with cookies that are supposed to be passed from a server context to a client context, e.g. a cookie that is sent by a client to a server and that should be resend by the server while itself doing an HTTP request to another server. 

* On the client side (I use wreq), we have a `Cookie` type that can only be created as part of a request/response exchange and which is part of a `CookieJar`,
* On the server side we have a WAI `Request` object which knows nothing about cookies, so we use `Web.Cookie` module which defines a `SetCookie` type which can be parsed from a Bytestring.

 It seems to me both worlds are incompatible but maybe I am missing something? Is there a simple way to pass those cookies across clients and servers somewhat transparently?

**Comment by snoyberg** [comment]
I don't actually understand this request. Can you clarify what isn't working for you?

**Comment by abailly** [comment]
Apologies for the noise, this question is probably more relevant to ask on SO.
