### ISSUE TITLE
TlsExceptionHostPort (HandshakeFailed (Error_Protocol ("expecting server hello, got alert : [(AlertLevel_Fatal,HandshakeFailure)]",True,HandshakeFailure)))

### ISSUE THREAD

**Issue by nineonine** [snoyberg/http-client#182]
Im trying to establish secured connection with https://www.discogs.com 

here is my code

```
{-# LANGUAGE OverloadedStrings #-}

module Main where

import Data.ByteString.Lazy (ByteString)
import Network.HTTP.Client
import Network.HTTP.Client.TLS

discogstls :: String -> IO ByteString
discogstls s = do
    initReq <- parseUrl s
    man <- newManager tlsManagerSettings
    let req = initReq { requestHeaders = [("User-Agent","dummytesting")] } 
    resp <- httpLbs req man
    return $ responseBody resp
```

then I'm testing it in ghci and getting an error
```
λ: discogstls "https://api.discogs.com/users/chemik_ck?token=LeOmytEjqpOGESAqxfbVuazqjJkUMSZAEyFtIjSm"
*** Exception: TlsExceptionHostPort (HandshakeFailed (Error_Protocol ("expecting server hello, got alert : [(AlertLevel_Fatal,HandshakeFailure)]",True,HandshakeFailure))) "api.discogs.com" 443
```

[according to discogs.com API documentation, I can send token either in URL params or in headers](https://www.discogs.com/developers/#page:authentication) - i tried both - nothing worked.

Then I googled [that issue](https://github.com/vincenthz/hs-tls/issues/108) related to some troubles with tls package. However, after that I used some tls debugging tools (tls-simpleclient from hs-tls) and I had no problems establishing connection with the host.

I tried everything - I updated all the necessary packages and nothing helped.

There was the same issue but , it was openSSL related and [according to that thread](https://www.discogs.com/forum/thread/702628) Discogs switched to tls completely.

Am I doing something wrong ?

thanks

**Comment by nineonine** [comment]
this is definitely something discogs specific and not related to this library. closing it

**Comment by nineonine** [comment]
I tried it with Wreq and got the same Exception
`*** Exception: TlsExceptionHostPort (HandshakeFailed (Error_Protocol ("expecting server hello, got alert : [(AlertLevel_Fatal,HandshakeFailure)]",True,HandshakeFailure))) "api.discogs.com" 443`
**Interesting to notice: **
I got that Exception first time I tried to do authorised request (passing token as Url param) however doing unauthorised requests was possible ! (and I used `defaultManagerSettings` for that, not  `tlsManagerSettings`. After I updated `http-client, http-client-tls, tls` , it became impossible to request anything (using defaultManagerSettings stopped working as well).

**Comment by nineonine** [comment]
should I address this issue in `tls` library ? maybe @vincenthz could help ? ^_^

**Comment by nineonine** [comment]
all good now . This was my first experience with cabal hell :)

**Comment by eikeon** [comment]
@nineonine What what the issue... think I'm in that same cabal hell now

**Comment by nineonine** [comment]
in my case this scenario worked

`ghc-pkg list`

There were 2 versions of tls listed there. I unregistered the older package

`ghc-pkg unregister --force <necessary package>`

**Comment by eikeon** [comment]
@nineonine Thank you. ( In my case it looks like I need to install an older version for now: https://github.com/vincenthz/hs-tls/issues/145#issuecomment-218035708 )
