### ISSUE TITLE
Using ALPN with TLS clients

### ISSUE THREAD

**Issue by nikomi** [snoyberg/http-client#187]
Hi,

I have a question regarding the use of ALPN on the client side.

I assume the client uses one of the `ClientHooks` in `TLSSettings` - namely `onSuggestALPN` - to add the list of requested protocols to the `ClientHello` message.

The server then selects one of these protocols - using this package the server would probably use `onALPNClientSuggest` from the `ServerHooks` - to be returned in the `ServerHello` message.

But then I'm stuck - I simply can't find a way for the client to detect which protocol the server selected (assuming the server has to select exactly one protocol or refuse the connection if it cannot).

What am I missing?

**Comment by snoyberg** [comment]
Perhaps this would better be asked on the `connection` or `tls` issue trackers? I don't think most people monitoring this issue tracker will have that information.

**Comment by nikomi** [comment]
Sorry, did not notice I'm wrong here... just followed the link in the package w/o thinking that far...

Could you please point me to the proper issue tracker(s)?

**Comment by snoyberg** [comment]
You're correct in that http-client-tls exposes some of the TLSSettings stuff, but it's all defined in https://github.com/vincenthz/hs-connection. I just don't have much knowledge of how to use ALPN as you're describing.

**Comment by nikomi** [comment]
Ah, I see - thx for the pointer!
