### ISSUE TITLE
Question about use of ResourceT in `http`

### ISSUE THREAD

**Issue by erantapaa** [snoyberg/http-client#194]
I have a question about how `ResourceT` is used in the `http` function (defined in `Network.HTTP.Conduit`). I see that `release key` is added as a cleanup handler both to the conduit (i.e. `addCleanup`) as well as being the finalizer to the `ResumableSource`, and I'm wondering what the rationale for that is. Are there cases where one may get called without the other getting called?

https://github.com/snoyberg/http-client/blob/master/http-conduit/Network/HTTP/Conduit.hs#L332-347

**Comment by snoyberg** [comment]
Having it in the ResumableSource means that it will get released as soon as
the source is fully exhausted. Having it in the ResourceT cleanup
guarantees it will be cleaned up even if the source isn't exhausted and/or
an exception is thrown.
