### ISSUE TITLE
Redirects will be followed in httpRaw' when reusing a dead connection

### ISSUE THREAD

**Issue by bitonic** [snoyberg/http-client#195]
I haven't verified this because it'd be a bit lengthy and you probably know immediately if I'm right or wrong.

`httpRaw'` calls `responseOpen` if the connection is reused and dead: https://github.com/snoyberg/http-client/blob/master/http-client/Network/HTTP/Client/Core.hs#L116 . `responseOpen` follows redirects.

**Comment by snoyberg** [comment]
I think you're right. Changing it to call httpRaw' instead would probably
fix it. I just left the house, but set a build to run and test that theory.

**Comment by snoyberg** [comment]
@bitonic would you mind checking out 9594e84?

**Comment by bitonic** [comment]
Looks good, I'd like to verify the bug and fix if there is a quick way to do so. Usually it's pretty annoying to simulate dead connections, do you already have such tooling in place?

**Comment by snoyberg** [comment]
No, I'd just include some code in the manager that arbitrarily kills connections.

**Comment by bitonic** [comment]
OK, I think that's too much effort for what is imo a pretty obvious fix. If you think it's necessary to verify it, let me know.

**Comment by snoyberg** [comment]
There are some wreq test failure with this patch. Then again, there are wreq test failures _without_ it, but this changes which tests failures. I'll investigate this more later before releasing.

**Comment by snoyberg** [comment]
Releasing a new version of http-client with these changes
