### ISSUE TITLE
What is the purpose of HasHttpManager？

### ISSUE THREAD

**Issue by winterland1989** [snoyberg/http-client#198]
today i want to declare my monad stack (a customized Reader) a instance to it，but i realize HasHttpManager is not parametrized by any monad, so what's the purpose of this class?

**Comment by snoyberg** [comment]
It's intended to be combined with `MonadReader`. See the [Network.HTTP.Client.Conduit](http://haddock.stackage.org/lts-5.17/http-conduit-2.1.10.1/Network-HTTP-Client-Conduit.html) API to see how it's used.

**Comment by winterland1989** [comment]
i see, thanks!
