### ISSUE TITLE
TLS Exception

### ISSUE THREAD

**Issue by rhvall** [snoyberg/http-client#199]
Hello!!

I have been developing an app using http-client-tls for the E-Trade API, however I was not able to establish a connection to the service, always with this exception:

`*** Exception: FailedConnectionException2 "us.etrade.com" 443 True <socket: 17>: hPutBuf: resource vanished (Broken pipe)`

I have made some google research to find a possible solution, but nothing really worked, even I found this here: 

http://stackoverflow.com/questions/27329793/broken-pipe-when-connecting-to-azure-datamarket-using-http-client-tls

https://github.com/vincenthz/hs-tls/issues/104

http://codereview.stackexchange.com/questions/8828/simple-tcp-client-memory-issues

In order to reproduce this issue, here is an small script that can be ran in GHCi:

> import Network.HTTP.Client.TLS as HTTPS
> import Network.HTTP.Client as HTTP
> import Data.Maybe as Mb
> mgr <- newManager tlsManagerSettings
> let req = fromJust $ parseUrl "http://us.etrade.com"
> rsp <- httpLbs req mgr

I am using http-client-tls-0.2.4, with MacOS 10.11.4, stack 1.0.4.3, ghci 7.10.3

I will keep investigating this issue.

**Comment by snoyberg** [comment]
That domain name fails for me as well, when just using the browser on my
phone. Are you sure it's correct?

**Comment by rhvall** [comment]
I used the following domains and all of them fail in some way or another:

https://us.etrade.com/home
https://us.etrade.com
https://etws.etrade.com
https://etws.etrade.com/oauth/access_token

Neither works, but also when I tried using PostMan, they all worked, specially the last, which is my target URL to get a OAuth Token to Etrade.

Although, I have tested about 30 different https webpages and I have not seen the same issue with them, I am starting to think that ETrade does not comply with the TLS protocol completely and that's why I am seeing this error. 

Derived from that, is there a way for me to debug http-client-tls to see a verbose explanation where and how it is breaking??

Thanks!!

**Comment by rhvall** [comment]
I have just found out the problem was only happening when I was running GHCi from stack, like:
`stack ghci`
If I run just GHCi, the same script I placed above runs flawlessly, I am so surprised that I am considering hardly to get rid of stack all together as I thought it was going to help me prototype faster but instead I have spend many hours trying to figure out this along other issues.

In any case, this issue could be closed.

I will try to debug the issue and discover why it was breaking at some point, but it would be helpful if someone points out how to debug effectively in Haskell, as I am not sure how to do it, specially coming from languages like Java or Objective C.

Thanks!!

**Comment by snoyberg** [comment]
It's possible that you have two different versions of tls installed, there's not enough information here, and the original bug report seems completely unrelated. There are debug instructions available on the TLS package's README.

**Comment by rhvall** [comment]
I checked and they are the same version of http-client-tls, for some reason, only when I ran `stack ghci` and specifically with that domain, it was not working; however, when I did it with only `ghci` and loading the libraries within, everything worked as expected. 

The good news, now I am able to continue developing this OAuth app. Thanks for the follow up.

**Comment by rhvall** [comment]
It might be worth the sharing, after dealing with this issue, I was able to OAuth the app, for which I created a blog post:

http://mittrasw.blogspot.com/2016/05/oauth-10a-for-etrade-api-using-haskell.html

It might help others if they encounter similar issues, and thanks @snoyberg for creating the awesome OAuth haskell package.
