### ISSUE TITLE
http-client-tls connection to HTTPS site with invalid hostname

### ISSUE THREAD

**Issue by oherrala** [snoyberg/http-client#212]
This issue is copy & pasted from https://github.com/bos/wreq/issues/84 and example modified for `http-client-tls`.

badssl.com tests have wildcard certificate with common name `*.badssl.com` and Subject Alternative Names `badssl.com` and `*.badssl.com`. `http-client-tls` misinterpretes how wildcard certificates should be handled:

```
*Main> :m Network.HTTP.Client Network.HTTP.Client.TLS
Prelude> manager <- newManager tlsManagerSettings
Prelude> request <- parseRequest "https://wrong.host.badssl.com"
Prelude> httpLbs request manager
Response {responseStatus = Status {statusCode = 200, statusMessage = "OK"}, responseVersion = HTTP/1.1, responseHeaders = <reponse removed>...
```

[RFC2818](https://tools.ietf.org/html/rfc2818) states that:

> Matching is performed using the matching rules specified by [RFC2459].  If more than one identity of a given type is present in the certificate (e.g., more than one dNSName name, a match in any one of the set is considered acceptable.) Names may contain the wildcard character * which is considered to match any single domain name component or component fragment. E.g., *.a.com matches foo.a.com but not bar.foo.a.com. f*.com matches foo.com but not bar.com.

Chrome, Firefox and Safari don't allow connection to this test host.

This was found with TryTLS test tool: https://github.com/ouspg/trytls

**Comment by snoyberg** [comment]
Looks like a dupe of #207

**Comment by oherrala** [comment]
This has been fixed in https://github.com/vincenthz/hs-certificate/pull/75:

```diff
- FAIL wrong hostname in certificate [reject wrong.host.badssl.com:443]
-      output: 200 OK
+ PASS wrong hostname in certificate [reject wrong.host.badssl.com:443]
+      output: HandshakeFailed (Error_Protocol ("certificate rejected: [NameMismatch \"wrong.host.badssl.com\"]",True,CertificateUnknown))

- FAIL invalid wildcard certificate Common Name [reject wildcard.mismatch.badtls.io:11007]
-      output: 200 OK
+ PASS invalid wildcard certificate Common Name [reject wildcard.mismatch.badtls.io:11007]
+      output: HandshakeFailed (Error_Protocol ("certificate rejected: [NameMismatch \"wildcard.mismatch.badtls.io\"]",True,CertificateUnknown))
```
