### ISSUE TITLE
http-client-tls vulnerable to Logjam?

### ISSUE THREAD

**Issue by oherrala** [snoyberg/http-client#215]
[ssllabs.com](https://ssllabs.com) has test for [Logjam](https://weakdh.org/) in their [client tests](https://www.ssllabs.com/ssltest/viewMyClient.html). This is probably issue in Haskell's [tls](https://github.com/vincenthz/hs-tls) library instead of `http-client-tls`. Ping @vincenthz .

```
Prelude> import Network.HTTP.Client
Prelude> import Network.HTTP.Client.TLS
Prelude> manager <- newManager tlsManagerSettings
Prelude> request <- parseRequest "https://www.ssllabs.com:10445/"
Prelude> response <- httpLbs request manager
Prelude> print response
Response {responseStatus = Status {statusCode = 200, statusMessage = "OK"}, responseVersion = HTTP/1.1 ... <output cleaned>
```

I expect this simple test to throw exception or fail otherwise instead of succesful connection.

Chrome, Firefox and Safari don't allow connection to this test host.

This was found with TryTLS test tool: https://github.com/ouspg/trytls

**Comment by vincenthz** [comment]
logjam is very much a policy choice. tracking this at https://github.com/vincenthz/hs-tls/issues/157

**Comment by snoyberg** [comment]
Upstream issue, closing.
