### ISSUE TITLE
How to change socket chunk size for http-conduit?

### ISSUE THREAD

**Issue by plintX** [snoyberg/http-client#217]
Does the http-conduit api expose a way to change the default socket chunk size? I noticed in https://github.com/snoyberg/http-client/issues/71 you provide the helper function `rawConnectionModifySocket`; it seems in Connection/Client.hs you also have the function `rawConnectionModifySocketSize`, as here:
https://github.com/snoyberg/http-client/blob/master/http-client/Network/HTTP/Client/Manager.hs#L69-L77
 but it's currently commented out?

Edit: Fixed link

**Comment by snoyberg** [comment]
Your link is broken, but the idea is that you would use one of these connection functions and then override `managerRawConnection` in the `ManagerSettings`.

**Comment by plintX** [comment]
trying to override `managerRawConnection` in `ManagerSettings` directly is not possible as far as I can tell because `openSocketConnectionSize` is defined in `Network.HTTP.Client.Connection` which is a hidden module; the problem with `rawConnectionModifySocket` is that it calls `openSocketConnection` which in turn calls `openSocketConnectionSize 8192`, so you can't set the socket chunk size.

I think you just need to uncomment `rawConnectionModifySocketSize`. Have fixed the link above, and as below:
https://github.com/snoyberg/http-client/blob/master/http-client/Network/HTTP/Client/Manager.hs#L69-L77

**Comment by snoyberg** [comment]
Could you send a PR for the change you're looking for?

**Comment by plintX** [comment]
^^

**Comment by snoyberg** [comment]
Merging, thanks!
