### ISSUE TITLE
Missing Exception HttpException instance

### ISSUE THREAD

**Issue by bergmark** [snoyberg/http-client#220]
http-client-0.5.0 removed the `Exception HttpException ` instance. Was this done on purpose? If so, what should we be using instead of `Control.Exception.catch`? There are a number of examples incl. the http-conduit haddocks which no longer type check.

**Comment by snoyberg** [comment]
That instance is still present. The change was the addition of
HttpExceptionContent

**Comment by bergmark** [comment]
You are right of course, thanks!
