### ISSUE TITLE
Documentation bug: HttpException's constructors are not available "since 0.5"

### ISSUE THREAD

**Issue by edsko** [snoyberg/http-client#221]
The structure of `HttpException` has changed significantly in http-conduit-2.2, but the [docs still specify](http://hackage.haskell.org/package/http-conduit-2.2.0.1/docs/Network-HTTP-Conduit.html#t:HttpException) that the `HttpExceptionRequest` has been available "since version 0.5". I think this should be "since version 2.2"?

**Comment by snoyberg** [comment]
It's imported from http-client, where indeed it _is_ available since 0.5. There's not much we can do about this confusing documentation display, unless you know of some Haddock trick.

**Comment by bermanjosh** [comment]
This is also hanging out with all the parseRequest variations. Maybe it's worth adding up top what version of client and conduit correspond with one another? It won't be pretty, but at least the info will be there.

**Comment by snoyberg** [comment]
That sounds ugly but workable. I'd accept a PR for that if you have time.

**Comment by edsko** [comment]
Oh, I see. I had missed that, sorry. That's unfortunate; I've opened a Haddock ticket at https://github.com/haskell/haddock/issues/550 . Apologies for the noise.

**Comment by snoyberg** [comment]
No problem, it's confusing.
