### ISSUE TITLE
Optionally Pass in the ConnectionContext when creating the TLS Manager

### ISSUE THREAD

**Issue by jfischoff** [snoyberg/http-client#228]
For profiling purposes I need to create many (~1000) separate Managers. This is fine for HTTP, but if I need TLS I run into memory and performance issues due to the slow and expensive creation of the ConnectionContext.

I would like to be able to create a single certificate store and share it between Managers. 

One way to enable this would be to modify the current mkManagerSettings

```haskell
mkManagerSettings :: TLSSettings -> Maybe SockSettings -> Maybe ConnectionContext -> ManagerSettings
```

Alternatively a new function for creation could be added

```haskell
mkManagerSettingsWithContext :: TLSSettings -> Maybe SockSettings -> Maybe ConnectionContext -> ManagerSettings
```

**Comment by snoyberg** [comment]
Check out #227, which has a very similar flavor to this. That PR is blocked on some understanding around laziness of creation, but simply providing a `WithContext` ability could be done immediately if this is urgent.

**Comment by jfischoff** [comment]
I looked closer at the code and see the new `mkManagerSettingsContext` (https://github.com/snoyberg/http-client/pull/227/files#diff-289ca8a43a0c204643df4a048f8d4ddeR44) which is entirely sufficient for my purposes. 

I'm not currently blocked by this FWIW, but will either have to fork http-client temporarily or will become blocked in the next few weeks.

**Comment by snoyberg** [comment]
In that case, I may as well expose `mkManagerSettingsContext` on `master` and cut a release. We can deal with the rest of #227 after that.

**Comment by snoyberg** [comment]
I just pushed a commit to master with this, want to check it out before I release?

**Comment by jfischoff** [comment]
LGTM

**Comment by snoyberg** [comment]
Awesome, released. I'll rebase the other branch on top of this.
