### ISSUE TITLE
http-client-tls fails TLS handshake that works with Network.Connection

### ISSUE THREAD

**Issue by sdroege** [snoyberg/http-client#231]
When running https://gist.github.com/sdroege/8a8a1a5ab0e278cbfd66eaa625dc4536 it fails with
````
test: Error_Protocol ("bad SignatureRSA for ecdhparams",True,HandshakeFailure)
````
Doing the same thing directly with Network.Connection works fine though: https://gist.github.com/sdroege/70969e63fd09b695e503ed96babc93ef (ignore that it does a broken HTTP request :) )

If I read the code of http-client-tls correctly, it is creating a connection context with exactly the same TLS settings in both cases (i.e. the default ones). So it seems like a problem in http-client-tls somewhere.

**Comment by snoyberg** [comment]
If I upgrade your connection based code to a proper HTTP request, I get the same error message:

```haskell
{-# LANGUAGE OverloadedStrings #-}

import Data.Default
import Network.Connection
import qualified Data.ByteString as B
import Control.Monad

main :: IO ()
main = do
    ctx <- initConnectionContext
    conn <- connectTo ctx ConnectionParams
        {
                connectionHostname = "paste.debian.net"
              , connectionPort = 443
              , connectionUseSecure = Just def
              , connectionUseSocks = Nothing
        }

    connectionPut conn "GET / HTTP/1.1\r\nHost: paste.debian.net\r\n\r\n"

    forever $ do
        line <- connectionGetLine 1024 conn
        B.putStrLn line
```

**Comment by sdroege** [comment]
Interesting! But why would a TLS handshake fail after the connection is already established? I guess this should become a bug against TLS then. Thanks!
