### ISSUE TITLE
Https proxy:  TlsNotSupported

### ISSUE THREAD

**Issue by o1lo01ol1o** [snoyberg/http-client#234]
I'm getting a `TlsNotSupported` exception when I try to make an Https connection via an Https Proxy.  I've confirmed that the proxy (and a number of others) are able to serve as proxies in https requests by replicating the GET request in question with the proxy in a python script.  However, I have been able to make https requests with https proxies in the past (public proxies, now no longer extant using my current wreq configuration), is it possible that the tls connection is only succeeding for a handful of configurations?

.  

The proxies are not public but if a maintainer wants to replicate I can privately forward one.

**Comment by snoyberg** [comment]
If you can put together a minimal example using just http-client and http-client-tls that repros, and privately send me the proxy IP address to use, that would be very helpful. I'm fairly certain there's no support right now for making an HTTPS connection to proxy servers themselves, but perhaps that restriction can be relaxed easily.

**Comment by o1lo01ol1o** [comment]
Well, this was unexpected.  The following works:

```
{-# LANGUAGE OverloadedStrings #-}
import qualified Data.ByteString.Lazy.Char8 as L8
import qualified Network.HTTP.Client        as C
import           Network.HTTP.Client.TLS
import           Network.HTTP.Simple
import           Network.HTTP.Types.Status  (statusCode)

main :: IO ()
main = do
    manager <- C.newManager tlsManagerSettings

    let secureRequest = setRequestProxy (Just (Proxy "ip"	pt))
            $ setRequestHeader "Proxy-Authentication" ["usr:pass"]
            $ "https://xxx"

    response <- C.httpLbs secureRequest manager

    putStrLn $ "The status code was: "
            ++ show (statusCode $ C.responseStatus response)
    L8.putStrLn $ C.responseBody response
```

I guess I'll close this, then.  Would you know where I might look for an issue downstream?

**Comment by snoyberg** [comment]
Sorry, I'm not familiar with the wreq codebase.

**Comment by o1lo01ol1o** [comment]
No worries, then.  Thanks for the quick response!
