### ISSUE TITLE
Change TLS cyphers in Network.HTTP.Conduit

### ISSUE THREAD

**Issue by mb21** [snoyberg/http-client#236]
There's an open [issue over at hs-tls about "Error_EOF connecting to google domains"](https://github.com/vincenthz/hs-tls/issues/152) and apparently:

> The workaround is simple if the API you use gives control over TLS parameters `supportedHashSignatures` or `supportedCiphers`: you just need to enable ECDSA in one or disable it in the other.

So could this be changed in `Network.HTTP.Conduit` so that we can connect to google domains again over https?

Steps to reproduce:

```
λ> import Network.HTTP.Conduit
λ> let (Just req) = parseUrl "https://docs.google.com"
λ| 
λ> mgr <- newManager tlsManagerSettings
λ> res <- httpLbs req mgr
*** Exception: TlsExceptionHostPort (HandshakeFailed Error_EOF) "docs.google.com" 443
```

**Comment by snoyberg** [comment]
What about just changing `tlsManagerSettings` in http-client-tls? @vincenthz do you have any input?

**Comment by mb21** [comment]
`tlsManagerSettings` is of type [`ManagerSettings`](https://hackage.haskell.org/package/http-client-0.3.5/docs/src/Network-HTTP-Client-Types.html#ManagerSettings), right? I didn't see any option to set the SSL/TLS cyphers there...?

**Comment by snoyberg** [comment]
Please have a look at:

https://www.stackage.org/haddock/lts-7.5/http-client-tls-0.2.4.1/Network-HTTP-Client-TLS.html#v:mkManagerSettings

**Comment by mb21** [comment]
So I guess we should change the `def` [here](https://github.com/snoyberg/http-client/blob/87764751c62fa7183dec7307c5fb7eafb0ea88ce/http-client-tls/Network/HTTP/Client/TLS.hs#L93):

    -- | Default TLS-enabled manager settings
    tlsManagerSettings :: ManagerSettings
    tlsManagerSettings = mkManagerSettings def Nothing

which currently uses [this `def` from Network.Connection.Types](https://github.com/vincenthz/hs-connection/blob/master/Network/Connection/Types.hs#L80), I think, which is:

    def = TLSSettingsSimple False False False

Unfortunately, using the `TLSSettings` instead of the `TLSSettingsSimple` constructor is indeed anything but simple, there's even an [open issue about it](https://github.com/vincenthz/hs-connection/issues/20)... but the better I understand the issue, the more I think this should be fixed in `TLSSettingsSimple`, thus in `hs-tls`...

**Comment by ocheron** [comment]
It's ugly and not something you want to do in every program.

```haskell
module Main (main) where

import Data.Default.Class ( def )

import Network.Connection ( TLSSettings(..) )
import Network.HTTP.Conduit
import Network.TLS
import Network.TLS.Extra ( ciphersuite_all )

import System.X509 ( getSystemCertificateStore )

myHashSignatures :: [HashAndSignatureAlgorithm]
myHashSignatures =
    [ (HashSHA512, SignatureRSA)
    , (HashSHA384, SignatureRSA)
    , (HashSHA256, SignatureRSA)
    , (HashSHA224, SignatureRSA)
    , (HashSHA1,   SignatureRSA)
    , (HashSHA1,   SignatureDSS)
    , (HashSHA512, SignatureECDSA)
    , (HashSHA384, SignatureECDSA)
    , (HashSHA256, SignatureECDSA)
    , (HashSHA224, SignatureECDSA)
    , (HashSHA1,   SignatureECDSA)
    ]

main :: IO ()
main = do
    let (Just req) = parseUrl "https://docs.google.com"
    scs <- getSystemCertificateStore
    let cp = (defaultParamsClient undefined undefined)
                 { clientSupported = def
                     { supportedCiphers        = ciphersuite_all
                     , supportedHashSignatures = myHashSignatures
                     }
                 , clientShared    = def
                     { sharedCAStore         = scs
                     , sharedValidationCache = def -- or something better?
                     }
                 }
    mgr <- newManager $ mkManagerSettings (TLSSettings cp) Nothing
    httpLbs req mgr >>= print
```

**Comment by creichert** [comment]
@ocheron Just to be clear, 

```
 let cp = (defaultParamsClient undefined undefined)
```

If you use this or `defaultParamsClient "" ""`, are the proper SNI settings updated on each call to `makeTLSParams`:

https://github.com/vincenthz/hs-connection/blob/3db5a4924ca23516a49699d27ef376385c0ef819/Network/Connection.hs#L128

I need this customization to fix the bug on my end but it's not clear whether these parameters can be reliably set through `http-client-tls`.

**Comment by creichert** [comment]
For anyone else who stumbles upon this and wants to configure their TLS ciphers via http-client `Manager`, I've created a full example.

https://gist.github.com/creichert/4f8adbfcf165191e90c94c5bd1d2e4d9

**Comment by ocheron** [comment]
@creichert Yes before posting the example I verified SNI and it seemed to work correctly.

**Comment by sgronblo** [comment]
Is there a new release of http-client that uses the fixed version of hs-tls (1.3.9)?

**Comment by snoyberg** [comment]
http-client should work with tls 1.3.9. Are you looking for a Stackage snapshot that includes the latest tls? If so, you can use nightly-2017-01-07, or just add the latest tls to your extra-deps (though you'll likely need to pull in newer versions of a few other packages too).

**Comment by mb21** [comment]
Since this is in http-client nighly, I guess it's best to close this issue again...
