### ISSUE TITLE
Setting redirectCount to 0 with managerModifyRequest does not work

### ISSUE THREAD

**Issue by abailly** [snoyberg/http-client#243]
I am using stackage's lts-7.3 which pulls http-client 0.4.31.1 by default and setting redirectCount to 0 does not work as expected: Redirection is still followed. I can see this behaviour has been fixed by https://github.com/snoyberg/http-client/commit/11a9a6273375e67c157b4b0a8a359c73029512cb Would it be possible to backport it so that it is available using lts-7.X dependency set?

**Comment by snoyberg** [comment]
Would you be able to send a PR against the `maintain/0.4` branch with the desired changes?

**Comment by abailly** [comment]
Sure. Will do that later on today.

Le 22 nov. 2016 11:33, "Michael Snoyman" <notifications@github.com> a
écrit :

**Comment by snoyberg** [comment]
Awesome, merged.
