### ISSUE TITLE
tutorial: missing --package aeson?

### ISSUE THREAD

**Issue by huppmann** [snoyberg/http-client#247]
@christiantakle et al.:

it i try to run the first httpJSON examples that calls Yaml.encode, i get the below unless i add `--package aeson` to the stack command line

    $ stack !$
    stack /tmp/buck/tutorial.hs
    
    /tmp/buck/tutorial.hs:14:17:
        No instance for (Yaml.FromJSON Value)
          arising from a use of ‘httpJSON’
        In a stmt of a 'do' block:
          response <- httpJSON "http://httpbin.org/get"
        In the expression:
          do { response <- httpJSON "http://httpbin.org/get";
               putStrLn
               $ "The status code was: " ++ show (getResponseStatusCode response);
               print $ getResponseHeader "Content-Type" response;
               S8.putStrLn $ Yaml.encode (getResponseBody response :: Value) }
        In an equation for ‘main’:
            main
              = do { response <- httpJSON "http://httpbin.org/get";
                     putStrLn
                     $ "The status code was: " ++ show (getResponseStatusCode response);
                     print $ getResponseHeader "Content-Type" response;
                     .... }
    
    /tmp/buck/tutorial.hs:19:19:
        No instance for (Yaml.ToJSON Value)
          arising from a use of ‘Yaml.encode’
        In the second argument of ‘($)’, namely
          ‘Yaml.encode (getResponseBody response :: Value)’
        In a stmt of a 'do' block:
          S8.putStrLn $ Yaml.encode (getResponseBody response :: Value)
        In the expression:
          do { response <- httpJSON "http://httpbin.org/get";
               putStrLn
               $ "The status code was: " ++ show (getResponseStatusCode response);
               print $ getResponseHeader "Content-Type" response;
               S8.putStrLn $ Yaml.encode (getResponseBody response :: Value) }

**Comment by snoyberg** [comment]
That's... _very_ interesting. Are you running that from inside a project directory with anything interesting in the `stack.yaml`? Have you made modifications to the `stack.yaml` for the implicit global project?

The next version of Stack will hopefully include this feature, which will improve the script experience a bit: https://github.com/commercialhaskell/stack/issues/2805

**Comment by huppmann** [comment]
On Sat, Dec 03, 2016 at 07:51:30AM -0800, Michael Snoyman wrote:
> That's... _very_ interesting. Are you running that from inside a project
> directory with anything interesting in the `stack.yaml`?

no

Have you made
> modifications to the `stack.yaml` for the implicit global project?

don't know.  could be that i ran stack at some other point in some non-
project directory and it did stuff in my $HOME, if that's what you mean

i carried out the below, to try to obviate any such possible effects,
but i'm not sure it gets at the question you're asking (nor that you
couldn't easily do the same and prove it to yourself, if it was a legi-
timate concern and not some kind of aberration that you indicate is on
the road to oblivion in the below comment:

>
> The next version of Stack will hopefully include this
> feature, which will improve the script experience a bit:
> https://github.com/commercialhaskell/stack/issues/2805

)

at any rate, if it's just me, i won't suffer any heartbreak if you close
this issue, if it's something that should work for normal people

thanks for expressing an interest just the same.  and thanks for all
the great code, tools, and platform improvements and all the illuminating
writing you do, and, of course, for sharing it gratuitously with the rest
of us

--buck

$ ls -a
.  ..  tutorial.hs
$ env HOME=`pwd` stack tutorial.hs
Downloaded lts-5.13 build plan.
Updating package index Hackage (mirrored at https://github.com/commercialhaskell/all-cabal-
Fetched package index.
Populated index cache.
[1 of 1] Compiling Main             ( /tmp/stack7020/Setup.hs, /tmp/stack7020/Setup.o )
Linking /tmp/buck/.stack/setup-exe-cache/x86_64-linux/tmp-setup-Simple-Cabal-1.22.5.0-ghc-7.10.3 ...
Completed 42 action(s).

tutorial.hs:14:17:
    No instance for (Yaml.FromJSON Value)
      arising from a use of ‘httpJSON’
    In a stmt of a 'do' block:
      response <- httpJSON "http://httpbin.org/get"
    In the expression:
      do { response <- httpJSON "http://httpbin.org/get";
           putStrLn
           $ "The status code was: " ++ show (getResponseStatusCode response);
           print $ getResponseHeader "Content-Type" response;
           S8.putStrLn $ Yaml.encode (getResponseBody response :: Value) }
    In an equation for ‘main’:
        main
          = do { response <- httpJSON "http://httpbin.org/get";
                 putStrLn
                 $ "The status code was: " ++ show (getResponseStatusCode response);
                 print $ getResponseHeader "Content-Type" response;
                 .... }

tutorial.hs:19:19:
    No instance for (Yaml.ToJSON Value)
      arising from a use of ‘Yaml.encode’
    In the second argument of ‘($)’, namely
      ‘Yaml.encode (getResponseBody response :: Value)’
    In a stmt of a 'do' block:
      S8.putStrLn $ Yaml.encode (getResponseBody response :: Value)
    In the expression:
      do { response <- httpJSON "http://httpbin.org/get";
           putStrLn
           $ "The status code was: " ++ show (getResponseStatusCode response);
           print $ getResponseHeader "Content-Type" response;
           S8.putStrLn $ Yaml.encode (getResponseBody response :: Value) }
$ stack --version
Version 1.2.0 x86_64 hpack-0.14.0

**Comment by snoyberg** [comment]
Could you tell me the result of running the following?

```
cat ~/.stack/config.yaml
cat ~/.stack/global-project/stack.yaml
```

**Comment by huppmann** [comment]
On Mon, Dec 05, 2016 at 05:52:43AM -0800, Michael Snoyman wrote:
> Could you tell me the result of running the following?
> 
> ```
> cat ~/.stack/config.yaml
> cat ~/.stack/global-project/stack.yaml
> ```

my pleasure:

    $ cat ~/.stack/config.yaml
    # This file contains default non-project-specific settings for 'stack', used
    # in all projects.  For more information about stack's configuration, see
    # http://docs.haskellstack.org/en/stable/yaml_configuration/
    #
    {}
    $ cat ~/.stack/global-project/stack.yaml
    # This is the implicit global project's config file, which is only used when
    # 'stack' is run outside of a real project.  Settings here do _not_ act as
    # defaults for all projects.  To change stack's default settings, edit
    # '/home/buck/.stack/config.yaml' instead.
    #
    # For more information about stack's configuration, see
    # http://docs.haskellstack.org/en/stable/yaml_configuration/
    #
    flags: {}
    extra-package-dbs: []
    packages: []
    extra-deps: []
    $
    resolver: lts-7.4

**Comment by snoyberg** [comment]
Alright, I'm stumped. As much as I'd like to track this one down, I don't have any real leads on doing so, and I don't want to waste your time trying out a bunch of random things. The only other output request I can think of that might help is running the commands that both succeed and fail with `--verbose` and reviewing that output. Sorry I can't be more helpful here.

**Comment by huppmann** [comment]
On Tue, Dec 06, 2016 at 06:16:19AM -0800, Michael Snoyman wrote:
> Alright, I'm stumped. As much as I'd like to track this one down,
> I don't have any real leads on doing so, and I don't want to waste
> your time trying out a bunch of random things. The only other output
> request I can think of that might help is running the commands that
> both succeed and fail with `--verbose` and reviewing that output. Sorry
> I can't be more helpful here.

no problem

--verbose was as taciturn as prior attempts

i moved my ~/.stack out of the way, and still no go without --package aeson

i don't suppose it would hurt to just stick that in the tutorial for anybody
whose setup is as broken as mine, would it?

**Comment by snoyberg** [comment]
I'm OK with that, want to send a PR?

**Comment by snoyberg** [comment]
Pretty sure this was resolved already.
