### ISSUE TITLE
http-client blocks when making a request inside a Docker instance.

### ISSUE THREAD

**Issue by seanparsons** [snoyberg/http-client#251]
As per the title, I'm seeing a weird issue where http-client seemingly blocks on the request below while run from within a Docker instance. On my machine it works outside of the container without any issues and calls to other endpoints (and stuff like curl) also work, which is why I'm so bemused.

```
Request {
  host                 = "igdbcom-internet-game-database-v1.p.mashape.com"
  port                 = 443
  secure               = True
  requestHeaders       = [("Accept","application/json"),("X-Mashape-Key","<BIGAPIKEY>")]
  path                 = "/games/"
  queryString          = "?fields=%2A&limit=50&offset=0&order=release_dates.date%3Adesc"
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = Just (-3425)
  requestVersion       = HTTP/1.1
}
```

The above is captured from the console when using `managerModifyRequest` and just throwing a `show` in there.

Also in this case I'm building the Docker instance with `stack image container` and running it straight on my machine  I've tried both LTS-7.5 and LTS-7.5 with the latest http-client.

**Comment by snoyberg** [comment]
Sone questions:

Do non HTTPS connections work?
Do connections to a different domain work?
Are you able to strace the run and see the last system call?
Can you provide a minimal repro case?

**Comment by seanparsons** [comment]
To those questions:
Yes. 
Yes. 
Not sure. 
I'll try to bolt that together.

**Comment by seanparsons** [comment]
I'm gonna close this for now, weirdly it seems to work in my little repro project which makes me think something in the larger project is causing grief for reasons unknown.

**Comment by snoyberg** [comment]
OK, feel free to reopen if you get more info, and good luck. In case it
helps, my first guess was that there was some problem reading the
certificate file inside the Docker image, but the fact that other HTTPS
connections were working probably rules out that theory.

**Comment by seanparsons** [comment]
Yeah, it seems a bit weird as I've got virtually the same thing in the other project, but that works without any issues.
