### ISSUE TITLE
Dangling connection leak

### ISSUE THREAD

**Issue by agrafix** [snoyberg/http-client#257]
I'm using `http-client` with `http-client-tls` in my application, and the application heavily leaks connections. 

My manager configuration looks like this:

```haskell
do mgr <-
           C.newManager $
           C.tlsManagerSettings
           { C.managerConnCount = 4
           , C.managerIdleConnectionCount = 40
           }
```

My understand is, that with this configuration there are never more than 40 handles open? The manager is accessed concurrently (can this be a problem?).

After running for a while, the program accumulates more and more dead connections that should be closed, but are not (state: `CLOSE_WAIT`, seen with `lsof`). More than 500 connections are dangling atm:

```
my-app 30288  app   16u     IPv4 1234      0t0     TCP xxxxx.eu-central-1.compute.internal:45120->yyyyyyy.eu-central-1.compute.amazonaws.com:https (CLOSE_WAIT)

[...]

my-app 30288  app   501u     IPv4 1234      0t0     TCP xxxxx.eu-central-1.compute.internal:45594->yyyyyyy.eu-central-1.compute.amazonaws.com:https (CLOSE_WAIT)
```
(slightly modified due to privacy concerns ... )

In my applications logs I can see multiple `ResponseTimeout`/`ConnectionTimeout` exceptions, which are somewhat expected in my used case. I think that the root of this issue is that one of them is not correctly handled in `http-client`, but I can not show this (yet?). I've tried to build a minimal example for reproduction, but this does **not** show the behavior:

```haskell
{-# LANGUAGE ScopedTypeVariables #-}
module Main where

import Control.Exception
import Control.Monad
import Network.HTTP.Client
import Network.HTTP.Client.TLS

main :: IO ()
main =
    do mgr <-
           newManager $
           tlsManagerSettings
           { managerConnCount = 1
           , managerIdleConnectionCount = 10
           , managerResponseTimeout = Just (1000 * 1000)
           }
       forM_ [1..1000] $
           \idx ->
           do req <- parseRequest "https://httpbin.org/delay/3"
              res <- try $ httpLbs req mgr
              case res of
                Left (e :: SomeException) -> print e
                Right _ -> pure ()
              pure ()
```

Any pointers where too look?

**Comment by snoyberg** [comment]
http-client does not actually limit the number of open connections at all. It only limits how many idle open connections. I haven't looked into this example yet in detail, can you tell me if this comment changes your report at all?

I'd also be interested if you reproduce issues with this PR: https://github.com/snoyberg/http-client/pull/254

**Comment by agrafix** [comment]
The documentation of `managerConnCount` states `Number of connections to a single host to keep alive.`. So if I send out more than `managerConnCount` requests, they will all be processed but only `managerConnCount` connections will remain open to that specific host? This would match what I'm seeing, but still does not explain why the connections are never really closed. If I stop reusing the manager and create a new one for each batch of requests this get's even worse, so there must be something broken with detecting these connections that are closed on kernel level, but not on application level (= `CLOSE_WAIT`), and clearing them out.

I'll try out the PR and report back to you, thanks!

**Comment by agrafix** [comment]
The PR didn't improve the situation, rather made it worse. I've deployed it on one production machine and the number of handles is growing very fast. I've also tried switching to a single`Manager` for the whole application, but this still results in massive connections dangling in the `CLOSE_WAIT` state.

**Comment by Yuras** [comment]
I reproduced the issue (at least something similar to it). Basically it is an instance if this one: https://github.com/vincenthz/hs-connection/issues/27

I surrounded `conFct` in `Network.Connection.connectTo` with a `bracketOnError`, and now everything is OK:

```
connectTo cg cParams = do
    conFct <- getConFct (connectionUseSocks cParams)
    E.bracketOnError
      (conFct (connectionHostname cParams) (N.PortNumber $ connectionPort cParams))
      N.close
      (\h -> connectFromSocket cg h cParams)
```

@agrafix Could you please try with the patch above?

**Comment by Yuras** [comment]
Ah, @agrafix, please check that you have this one applied too: d7a22e2be4998db61c5faa1dea076d4f24b3ced9

**Comment by agrafix** [comment]
Perfect, that fixed the issue! Thank you very much!

**Comment by snoyberg** [comment]
Can you confirm which version of http-client you tested this with? It would be good to know if the STM manager didn't have any issues.

**Comment by agrafix** [comment]
@snoyberg the application currently is running with the STM manager patches and a patched `connection` package.

stack.yaml:
```
resolver: lts-7.15
packages:
  - .
# ...
  - location:
      git: https://github.com/agrafix/hs-connection.git
      commit: cba040a94f2f3a9a78eee9a9f2009df48cacde8d
    extra-dep: true
# ...
  - location:
      git: https://github.com/snoyberg/http-client
      commit: 2392c62a108a94e26723a39dbf928886e910f406
    extra-dep: true
    subdirs:
      - http-client
      - http-client-tls
      - http-conduit
```

**Comment by snoyberg** [comment]
Could you also test with the unpatched http-client so we get an idea if the STM manager fixed a bug or simply left things unchanged?

**Comment by agrafix** [comment]
@snoyberg I've now tested both with patched `connection` and they work equally well.

**Comment by snoyberg** [comment]
Awesome, thanks :+1:
