### ISSUE TITLE
Very rare deadlock

### ISSUE THREAD

**Issue by FPtje** [snoyberg/http-client#258]
On some server we have the following code running:

```haskell
import qualified "bytestring" Data.ByteString.Lazy  as BL
import qualified "http-client"      Network.HTTP.Client      as Http
import qualified "http-client-auth" Network.HTTP.Client.Auth as Http
import "lifted-base" System.Timeout.Lifted ( timeout )
import qualified "safe-exceptions" Control.Exception.Safe as SE
import qualified "text" Data.Text          as T
...

authedRequest
    :: (MonadIO m, MonadBaseControl IO m)
    => Http.Manager
    -> T.Text -- ^ user
    -> T.Text -- ^ password
    -> String -- ^ url
    -> ExceptT String m BL.ByteString
authedRequest mgr user password url = do
    request <- maybeToExceptT "invalid request" $ MaybeT $ pure $ Http.parseRequest url
    meResponse <- timeout 1800000000 $ mapExceptT liftIO $ SE.try $ maybeToExceptT "no response" $ Http.requestWithAuth
      (T.unpack user)
      (T.unpack password)
      (\req -> Http.httpLbs req mgr)
      request

    case meResponse of
      Nothing -> throwError $ "Failed request! (" <> show url <> "): Request seriously timed out!"
      Just (Left (SomeException err)) -> throwError $ "Failed request! (" <> show url <> "): " <> show err
      Just (Right response) -> pure $ Http.responseBody response
```

Where `Http.requestWithAuth` is defined in our fork of http-client-auth [here](https://github.com/LumiGuide/http-client-auth/blob/master/src/Network/HTTP/Client/Auth.hs#L455-L475).

This function is called *many* times, say thousands of times per hour, from multiple threads.

# The problem
Usually after two days of the server being up, the message `"Request seriously timed out!"` starts appearing in our log. That means that some (authed) request blocked for half an hour. Without the timeout, the request would block *indefinitely*. 

This timeout should never fire. After all, we leave the RequestTimeouts of both the `Request` and the `Manger` to default, which should mean it would timeout after 30 seconds.

# Some facts
- This bug is rare, *very* rare. I have no reliable way of reproducing it.
- There are only a couple of hundred *unique* requests (unique in URL and method). With the bug happening after two days or so, necessarily it must be on a request that has worked fine countless times before.
- The bug *appears* to happen consistently on requests that have a somewhat large response (e.g. an image), though I stress that I'm not certain of this.
- Other requests are unaffected by one request being blocked.
- All requests use the same `Manager`.
- We have a thread view of our server. Threads that are blocked on a buggy request show `blocked (MVar)`.
- I'm reporting this here rather than [`http-request-auth`](https://github.com/LumiGuide/http-client-auth/blob/master/src/Network/HTTP/Client/Auth.hs#L455-L475) because that library doesn't seem to have any blocking or even looping code. 
- We're running `http-client` version `0.5.5`.

I'm interested to see what would happen with the `STM-Based Manager` pull request. I will try to run that for a couple of days to see if that resolves the issue.

**Comment by snoyberg** [comment]
Thanks for the report. I'm also interested to hear if the STM based manager has any impact, please report back when you have more information. My gut says it shouldn't matter though: timeout handling is mostly outside of the manager.

**Comment by FPtje** [comment]
You're right, it happened twice yesterday and once two days ago, on the `STM-Based Manager` branch. Any idea where to look next?

**Comment by snoyberg** [comment]
The most useful thing to know would be what action inside http-client is timing out. I'd consider sprinkling around something like the following throughout http-client, compiling your code, and see what happens:

```haskell
traceOnException :: String -> IO a -> IO a
traceOnException msg action = action `Control.Exception.catch` \(e :: SomeException) -> do
    putStrLn $ msg ++ ": " ++ show e
    throwIO e
```

**Comment by FPtje** [comment]
The debug message in [this commit](https://github.com/LumiGuide/http-client/commit/d753025aa1dfbdf12a442d6d3cbbd9673c345354) are running on the machine that has this issue. I've seen the debug messages print on unrelated exceptions, so that's promising.

And now we wait a couple of days for it to happen again.

**Comment by FPtje** [comment]
```
brAddCleanup: <<timeout>>
brConsume: <<timeout>>
httpLbs: <<timeout>>
withResponse: Request {
  host                 = "<redacted>"
  port                 = 80
  secure               = False
  requestHeaders       = [<redacted Digest authentication>]
  path                 = "<redacted>"
  queryString          = "<redacted>"
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
: <<timeout>>
```

I'll add some more tracing on exception code to `withResponse`.

**Comment by FPtje** [comment]
```
brAddCleanup: brRead': <<timeout>>
brAddCleanup: <<timeout>>
brConsume: brRead': <<timeout>>
brConsume: go: <<timeout>>
brConsume: go: <<timeout>>
brConsume: go: <<timeout>>
brConsume: go: <<timeout>>
brConsume: go: <<timeout>>
brConsume: go: <<timeout>>
brConsume: go: <<timeout>>
brConsume: go: <<timeout>>
brConsume: go: <<timeout>>
brConsume: go: <<timeout>>
brConsume: <<timeout>>
httpLbs: <<timeout>>
withResponse: Request {
  host                 = "<redacted>"
  port                 = 80
  secure               = False
  requestHeaders       = [<redacted DIGEST auth>]
  path                 = "<redacted>"
  queryString          = "<redacted>"
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
: <<timeout>>
```

Some more output, with the debug prints from [this commit](https://github.com/LumiGuide/http-client/commit/0e5a30915e95961e39d3da4571e14151f9ddd567). Do you reckon this is enough information?

The "serious timeout" at the moment is twice the default timeout. With `ResponseTimeoutDefault` on both `Request`  and `Manager` that's 60 seconds.

**Comment by snoyberg** [comment]
This definitely helps, it's implying that the consumption of the response body itself is the part that's taking so long. And this makes sense as being unprotected by the timeout values, since the timeout values only apply up until the response headers are consumed (it can take an unbounded amount of time to get a response body, such as the case for long polling).

In other words, this may not at all be a bug, but simply a slow response from the server.

If you want to go one layer deeper, you could try tracing some of the socket code itself to confirm that it is, in fact, the `recv` call which is timing out.

**Comment by FPtje** [comment]
The explanation makes sense, as the request is always one that requests an image. I wouldn't be surprised if the server has some buggy implementation that sometimes just stops sending the body halfway. Before I added the half an hour timeout, we would find the request frozen for over a day.

The fact that the consumption of the response body is unprotected by a timeout is key in this case. Might I request this to be mentioned in the documentation of the request and/or manager timeout? Also, would it make sense to have some functionality that makes sure a request will not take longer than a given amount of time? This would make sense for requests that expect an answer within a reasonable time.

**Comment by snoyberg** [comment]
PRs for improving the docs are more than welcome. However, as mentioned, putting in a requirement that the response body be consumed in a given timeframe would not generally make sense, and protecting the body consumption with a timeout is a logical thing to do. The mechanism is specifically in place to protect against a slow connection process, not a slow download.

**Comment by FPtje** [comment]
Alright, I'll wrap a timeout around the HTTP requests.
