### ISSUE TITLE
Undefined symbols when linking on mac os Sierra

### ISSUE THREAD

**Issue by gbordyugov** [snoyberg/http-client#260]
Hi,

I'm getting the following error message when linking against http-client-0.5.5:

```
Undefined symbols for architecture x86_64:
  "_timezm1zi6zi0zi1_DataziTimeziClockziCTimespec_getCTimespec1_closure", referenced from:
      _S1ANG_srt in libHShttp-client-0.5.5-CJ2iYv4sQ8UFTJLSsSF0jG.a(Manager.o)
      _S1Nbn_srt in libHShttp-client-0.5.5-CJ2iYv4sQ8UFTJLSsSF0jG.a(Core.o)
  "_timezm1zi6zi0zi1_DataziTimeziClockziCTimespec_getCTimespec1_info", referenced from:
      _s1Ag4_info in libHShttp-client-0.5.5-CJ2iYv4sQ8UFTJLSsSF0jG.a(Manager.o)
      _c1Evr_info in libHShttp-client-0.5.5-CJ2iYv4sQ8UFTJLSsSF0jG.a(Manager.o)
      _s1MOA_info in libHShttp-client-0.5.5-CJ2iYv4sQ8UFTJLSsSF0jG.a(Core.o)
      _c1NfU_info in libHShttp-client-0.5.5-CJ2iYv4sQ8UFTJLSsSF0jG.a(Core.o)
      _c1Ncn_info in libHShttp-client-0.5.5-CJ2iYv4sQ8UFTJLSsSF0jG.a(Core.o)
      _c1Njz_info in libHShttp-client-0.5.5-CJ2iYv4sQ8UFTJLSsSF0jG.a(Core.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`gcc' failed in phase `Linker'. (Exit code: 1)
```

**Comment by snoyberg** [comment]
Please provide full information on how you're trying to build http-client (e.g., Stack command). I have been able to compile this version of the library on OS X, for instance (though I haven't tried Sierra).

**Comment by gbordyugov** [comment]
I ran into the trouble trying to build an example using gogol-* libraries. Yes, I'm compiling a stack-set `simple` project with `resolver: nightly-2017-02-07`, the only extraordinary thing being `gogol-*` libraries pulled from github. The error appears both upon invocation of `stack build` and `stack ghci`.

Please let me know what further details you need.

**Comment by gbordyugov** [comment]
addendum: it compiles and links fine if it appears on the `extra-deps:` list in my `stack.yaml`, otherwise it throws a linker error.

**Comment by snoyberg** [comment]
Can you try running `stack exec -- ghc-pkg unregister http-client --force`.
It's possible that a corrupted file made it into your package database
somehow, and forcing a recompile will recover.

**Comment by gbordyugov** [comment]
it did unregister, but on the next compile attempt it said `http-client-0.5.5: using precompiled package` though

**Comment by snoyberg** [comment]
Well, it's a big nuke, but you can try `rm -rf ~/.stack/snapshots` and try
again.

**Comment by gbordyugov** [comment]
Seems to have helped, thanks!
