### ISSUE TITLE
Using a different medium for communication

### ISSUE THREAD

**Issue by mzabani** [snoyberg/http-client#261]
This is a question, not a bug: I need to use http-client to send data to a previously opened TCP connection. The specific use case here is an already established WebSocket tunnel.
For this, I need to send a small header with every message to the other side and be able to supply http-client with incoming data myself.
Is this possible? If not, how hard would it be to implement with the current codebase?

**Comment by snoyberg** [comment]
It should be possible to fudge around with the manager settings to provide a different means of getting a `Connection` value. You may want to look at how `http-client-tls` does this.

**Comment by mzabani** [comment]
Thanks for the tip! I'm pretty new to Haskell myself, so could you tell me at least if I'm on the right path when I think I should implement my own `ManagerSettings`, making *managerRawConnection* and *managerTlsConnection* (and others if needed) point to functions that return my own `Connection`s (with altered functions as well). Then, all I need is to create a `Manager` and that's it?

**Comment by snoyberg** [comment]
Yup, that's what I'd recommend.

**Comment by mzabani** [comment]
Thank you very much for your help! I'm closing this issue, if that's ok with you.
