### ISSUE TITLE
http_proxy socks5 proxy InvalidProxyEnvironmentVariable

### ISSUE THREAD

**Issue by tiredpixel** [snoyberg/http-client#263]
[#153] adds support for `socks5://` and `socks5h://` protocols. But attempting to set `http_proxy=socks5h://proxy:1080` or `https_proxy=socks5h://proxy:1080` results in

```
InvalidProxyEnvironmentVariable "http_proxy" "socks5h://proxy:1080"
```

Might not this be because of the guard? (https://github.com/snoyberg/http-client/blob/master/http-client/Network/HTTP/Client/Manager.hs#L516)

p.s. I'm unsure of whether socks5 proxy support is intended for construction of `Proxy` itself passed to `Request`, rather than through environment variables. This doesn't work for me either, failing with `NoResponseDataReceived`; I can see no way of specifying `socks5h` rather than `http`, and `Proxy` only accepts `proxyHost`, `proxyPort`, rather than the scheme. If this sounds like it could be valid and you'd like me to file another ticket, please say. :)

cc @snoyberg, @RobertFischer, @ibukanov

**Comment by snoyberg** [comment]
Please see https://github.com/snoyberg/http-client/pull/264, which I just opened (I've been working on the automated tests since yesterday, when I noticed that #153 was broken).

**Comment by tiredpixel** [comment]
@snoyberg, thank you for replying so quickly! Yes, it looks like #264 should fix what I've found for the environment variables. If it passes your tests and your release, I'd be happy to test whether it fixes what I've found. I'd also be happy to test the use of `socks5h` proxy passed into `Request` itself using `Proxy`, if that is expected to work (although I see nothing regarding it…). Thanks!

**Comment by snoyberg** [comment]
Oh, I get your question now. It seems like the PR for #153 was completely misguided and should just be removed. You're right, setting `Proxy` does not work for socks proxies. We _can_ implement something like that via the connection package, but it's not done yet.

**Comment by tiredpixel** [comment]
@snoyberg, I see. Yes, that's what I'd thought; I did hope things would somehow magically work so tried it anyway ;) , but I didn't see code to support it. Okay, I understand, thank you nonetheless. :)

**Comment by RobertFischer** [comment]
Sad trombone.

**Comment by snoyberg** [comment]
This is far from unimplementable, it just needs to be handled elsewhere. Specifically, support can be added to http-client-tls to parse these variables and modify the SockSettings appropriately. If someone wants to take a crack at this, it would definitely speed up availability.

**Comment by snoyberg** [comment]
Alright, this should now be implemented on the 263-socks-proxy branch. I've tested this myself, but if someone else wants to confirm that would be appreciated.

**Comment by nh2** [comment]
The commit above fixes `InvalidProxyEnvironmentVariable` for `http-client-tls`.

Would it make sense to fix the `http_proxy` `socks5://` combination for `http-client` (non-TLS) as well?
