### ISSUE TITLE
Leaking HTTP connections with latest tls/connection and friends

### ISSUE THREAD

**Issue by MichaelXavier** [snoyberg/http-client#265]
Some context:
https://github.com/vincenthz/hs-tls/issues/190

Apologies for the lack of information here but I'm really not sure the exact cause of this issue, but it seems like it may be a bad interaction between http-client-tls and upgrading tls, connection, etc.

The short version: I upgraded to lts-8 in a large production app and noticed sockets leaking even though the application code hadn't changed. After debugging I found the last port the socket would connect to before leaking was 443. The leaks are characterized by large numbers of sockets showing up in `lsof` with a description of `can't identify protocol`. Pretty much anything that was doing https in haskell land would eventually leak, e.g. amazonka.

I set the following dependency resolutions over lts-8:

```yaml
- tls-1.2.18
- x509-1.5.1
- x509-store-1.5.0
- x509-system-1.5.0
- x509-validation-1.5.2
- asn1-parse-0.9.1
- connection-0.2.4
```

This immediately fixed the issue in production with absolutely no changes to anything else in the application. I've tried to create a minimal repro case but have yet to be successful. I was hoping somebody would have an inkling as to what could have changed along the way. I'm happy to help get to the bottom of this but given the only way for me to repro this is to rebuild my binaries and reintroduce a leak into production, I'm hesitant to go in blind.

Thanks!

**Comment by snoyberg** [comment]
If downgrading the version of tls or connection fixes the problem, I'm not sure how http-client-tls could be the culprit. In any event, I've pushed a branch verbose-open-close which adds some debug output each time a TLS connection is opened or closed. It should indicate if connections are never being closed. Can you try it out?

**Comment by MichaelXavier** [comment]
Just an update: promise I haven't forgotten about this, but I'm looking for a window where I'll be able to reintroduce this leak into production and monitor it.

**Comment by MichaelXavier** [comment]
I guess the culprit is somewhere else (perhaps the connection library?) I ran this in production yesterday and after many hours the counts reported by your output showed matching open/close number, yet if i ran `lsof -n | grep ghc | grep "Can't identify protocol"`, I was up to 12,000 leaked connections by the next day. The only way it could be http-client related I guess is if the act of closing the connection was reporting as successful but not succeeding to the degree that the fds were released.

Not really sure where to go from here. I'm on lts-8.2 and any further forces me to accept newer versions of these tls packages. Maybe I'll try slowly walking each dependency forward in version independently and see if I can narrow it down to a package in particular.

**Comment by snoyberg** [comment]
If you don't mind, I'd like to reopen the issue. I don't think the problem is in http-client-tls, but I'd like to debug this, and currently you have the only repro. I think the best bet is to look through the code in question, starting with the `connectionClose` call. Reviewing that myself, this immediately jumps out to me as possibly problematic:

```haskell
backendClose (ConnectionTLS ctx)  = TLS.bye ctx >> TLS.contextClose ctx
```

The usage of `>>` instead of `finally` means that, if `TLS.bye` throws an exception, `contextClose` will never be called. Can I ask you to try replacing that code with something like:

```haskell
backendClose (ConnectionTLS ctx)  =
    TLS.bye ctx `finally` TLS.contextClose ctx
  where
    bye' = TLS.bye ctx `catch` \e -> do
      putStrLn $ "Exception during bye: " ++ show (e :: SomeException)
      throwIO e
```

**Comment by MichaelXavier** [comment]
Sure, thanks for sticking with me! This certainly does seem plausible. I'm going to try this on Monday as a faint voice in my mind is telling me not to mess with production on a Friday :stuck_out_tongue:

**Comment by vincenthz** [comment]
that sounds plausible, the only relevant thing I can think of since the old version listed by @MichaelXavier is that we default from `Handle` to network `Socket` now. As only `Handle` autoclose, that sounds it could be it.

**Comment by iand675** [comment]
I want to chime in and say I'm trying to move my stack LTS version forward from 6.3 and am encountering this too. It appears that anything trying to use the http-client-tls is failing with errors such as:

```
HttpExceptionRequest Request {
   host                 = "api.rollbar.com"
   port                 = 443
   secure               = True
   requestHeaders       = []
   path                 = "/api/1/item/"
   queryString          = ""
   method               = "POST"
   proxy                = Nothing
   rawBody              = False
   redirectCount        = 10
   responseTimeout      = ResponseTimeoutDefault
   requestVersion       = HTTP/1.1
}
(ConnectionFailure getProtocolByName: does not exist (no such protocol name: tcp))
```

Interestingly I'm not able to repro it locally at the moment. Just production.

**Comment by snoyberg** [comment]
That looks unrelated to this issue. In my experience, it's always been because the /etc/protocols file is missing, and needs to be added (I forget the name of the Ubuntu package which provides it, but it's not installed by default).

**Comment by iand675** [comment]
Ah yes, you're totally right. Sorry for the stray unrelated issue. Thank you for the hint. It saved me from going down the rabbit hole even further. For any other confused souls who stumble into this issue, you'll probably also want to `apt-get install ca-certificates` as well.

**Comment by MichaelXavier** [comment]
Interestingly enough, in my file descriptor leak issue I would see these no such protocol issues too and I believed them to be related to file descriptors on the system being exhausted. I never made a change like installing netbase or ca-certificates, but restarting the processes would free the leaked fds and this issue would go away. Perhaps the issue was that the process was trying to open /etc/protocols, /etc/hosts, etc and couldn't because there were no spare fds.

BTW I plan on finally trying out the exception handling code today, I'll let you all know how that goes.

**Comment by MichaelXavier** [comment]
@snoyberg @vincenthz I think we have a winner! Thanks so much for the suggestion!

I applied Michael's patch to a locally vendored copy of `connection-0.2.7`'s `connectionClose` function. I've then rebuilt the binary, shipped it to production and let i run. It has run for about 15 minutes now and does not appear to be leaking connections. I can let it run longer. My observations:

`lsof -n | grep identify | grep ghc | wc -l` is staying steadily at 0, meaning no leak has appeared. In previous tests they would have appeared by now.

I'm seeing output slowly accumulate from the executable that looks like:
```
Exception during bye: sendBuf: resource vanished (Broken pipe)
Exception during bye: sendBuf: resource vanished (Broken pipe)
Exception during bye: sendBuf: resource vanished (Broken pipe)
Exception during bye: sendBuf: resource vanished (Broken pipe)
Exception during bye: sendBuf: resource vanished (Broken pipe)
```
I tried running a stopwatch to see if these happened with any regularity to maybe hint at some sort of connection pool timeout but I saw time ranges from 25 seconds to 1:10. It could certainly still be a timeout issue and that the actual workload on the box is obscuring the problem.

So what's the next step? Should this just be an update to `connection`, minus the putStrLn? Anything I should do?

**Comment by ocheron** [comment]
Alternatively we could change `bye` itself to make it safe. There's a [tryBye](https://github.com/vincenthz/hs-tls/blob/e2a906d8d6e6c1b92c29a10694cd350e73fa1a13/core/Network/TLS/Core.hs#L128) used internally.
Or at least point out in the documentation that `bye` can raise exceptions.

**Comment by snoyberg** [comment]
Regardless of modifications to `bye` itself, switching over to `finally` is a good move, so I'm going to go ahead with a PR for that. I don't believe the current behavior of `bye` is at all incorrect, so I'd be hesitant about saying it must be changed.
