### ISSUE TITLE
Support for Windows proxy settings

### ISSUE THREAD

**Issue by varosi** [snoyberg/http-client#268]
Currently proxy settings are get from HTTPS_PROXY and HTTP_PROXY env. variables which are not a standard in Windows OS. Every tool created with http-client under Windows is suffering from this problem. For every tool the developer have to ask users of the tool to set those env. variables if they have proxies which is inappropriate under Windows.
Standard places to set proxies there are under LAN settings accessible by any browser under Windows. 
Here are some info about how it could be extracted:
https://msdn.microsoft.com/en-us/library/windows/desktop/aa384095(v=vs.85).aspx
https://msdn.microsoft.com/en-us/library/aa384096(VS.85).aspx

**Comment by varosi** [comment]
Second method return proxy info for sure, at least on my Windows 8.

**Comment by varosi** [comment]
This could help, too
https://hackage.haskell.org/package/HTTP-4000.3.6/docs/Network-HTTP-Proxy.html#t:Proxy

it's returning correct value on my work station.

**Comment by snoyberg** [comment]
Would you be interested in sending a PR for this functionality?

**Comment by varosi** [comment]
Yes, I will try to next weeks.

**Comment by varosi** [comment]
Is it Okay for you to bring http://hackage.haskell.org/package/HTTP dependency to http-client, because of Network.HTTP.Proxy ?

**Comment by snoyberg** [comment]
No, we can't add that dep

**Comment by varosi** [comment]
Other way is to copy paste proxy reading from there, which is not beautiful.

**Comment by varosi** [comment]
Okay, I'll create a new library that is dealing with finding proxies, so this functionality could be reused.

**Comment by snoyberg** [comment]
I'd really rather the functionality go straight into http-client, I already
get people complaining regularly about any added dependencies. In principle
I agree with doing things as separate libraries, I'm just trying to find a
balance that makes the least number of people upset.

**Comment by snoyberg** [comment]
Addressed by #274.
