### ISSUE TITLE
Evil Servers: Timeouts & Max Lengths

### ISSUE THREAD

**Issue by tiredpixel** [snoyberg/http-client#269]
Firstly, thanks for such a brilliant library. :) I'm downloading data from potentially-evil servers, and want to have some protection with regards to resource usage. I've been digging through the documentation and code, but am still unclear about the following two points; I'd be grateful if you could enlighten me. :)

- The timeout in the manager protects against a server indefinitely hanging, unless I am mistaken. Does it also protect against super-slow responses, such as a few bytes every few minutes? Or is there some way to set a timeout across the entire request (other than wrapping the call within a non-library timeout)?

- I've been using `httpLbs`, which of course downloads the entire response. Is there a setting to limit the max length of the header and body processed in memory? I was looking at using a sink, but the functions I found there seemed to be to wait until a *minimum* of bytes returned, not to throw an exception at a *maximum*.

Much obliged, both for this and your continuing hard work across so many libraries. :) -- tiredpixel

**Comment by snoyberg** [comment]
* You're correct about slow response, at least as far as sending back response headers. But there's no built in support for slow response bodies. You'd have to add that protection yourself.
* There's no setting to limit what you get with `httpLbs`. There are certainly methods via a sink to throw an exception if more than a given number of bytes are received, though I'm not sure what you've attempted so far.

Thanks for the kind words.

**Comment by tiredpixel** [comment]
* I see. In that case, I'll likely add a timeout around that function. Do I have to worry about clean-up, in such a case?

* I've been attempting like the following, but it doesn't work; I suspect that's because I'm erroneously trying to use `take` as if it will consume a single byte, rather than an item in the stream. `take 0` works in that the response is empty, however. So, the aim is to read x bytes from a stream, and to throw an exception if there are more bytes in the stream, with no further attempt at reading, and clean-up happening properly. I'm aware this snippet doesn't attempt to throw an exception—but it doesn't limit the read as I'm trying, either…

```
makeRes :: HTTP.Manager -> HTTP.Request -> IO (HTTP.Response BSL.ByteString)
makeRes nC req = do
    runResourceT $ do
        res <- HTTP.http req nC
        bss <- HTTP.responseBody res $$+- do
            x <- CL.take 1
            CL.sinkNull
            return x
        return res {
            HTTP.responseBody = BSL.fromChunks bss
```

being a extension of the (working) consume-everything

```
makeRes :: HTTP.Manager -> HTTP.Request -> IO (HTTP.Response ByteString)
makeRes nC req = HTTP.httpLbs req nC
```

Any advice much appreciated! :)

**Comment by snoyberg** [comment]
Adding a timeout is perfectly safe and reasonable, resources will be cleaned up correctly.

As for `take`: I think you just need to switch to using the variant in `Data.Conduit.Binary`: https://www.stackage.org/haddock/lts-8.8/conduit-extra-1.1.15/Data-Conduit-Binary.html#v:take. This version works on bytes, as opposed to the variant in `Data.Conduit.List`, which will take a certain number of `ByteString`s, which will each be of an arbitrary size.

**Comment by tiredpixel** [comment]
Perfect, thanks for confirming.

Ah, brilliant—that makes sense! Switching to `Data.Conduit.Binary` as you suggest yields the desired behaviour for final results. However, I note that there is no `Binary.sinkNull`. I naïvely tried `List.sinkNull` thinking well it's null :P , but although that truncates correctly finally, attempting to download a huge field hangs and processes before truncation. Removing the `sinkNull` altogether appears to work perfectly, though. Is this safe? Do I need to sink the rest of the source, or will it clean up correctly?

**Comment by snoyberg** [comment]
You do not need to sink the rest of the response, just ignore it and the library will do the right thing.

**Comment by tiredpixel** [comment]
Brilliant. Thank you very much for your help! :)

**Comment by snoyberg** [comment]
No problem

**Comment by unhammer** [comment]
Hi, I think I'm in a similar situation, e.g. servers which do not close streams, giving IncompleteHeaders and such. Is the situation anno 2024 still that the recommended solution is to wrap calls in a timeout? Should perhaps the docs reflect this? 

I was trying to find out from the docs which HttpManager Timeout to fiddle with, but if there is none, it would be nice if the docs explained the limitations of ResponseTimeout and noted that you can safely wrap the request in `System.Timeout.timeout` if you need a timout that covers the whole call from start to finish.
