### ISSUE TITLE
function "newTlsManagerWith" does not take into account TLSSettings

### ISSUE THREAD

**Issue by Haskell-mouse** [snoyberg/http-client#289]
I just tried to test functions from my small project in ghci, and have found that function "newTlsManagerWith" from Network.HTTP.Client.TLS module  does not take into account TLSSettings. 

my actions in ghci: 
> tlsset = TLSSettingsSimple True False True  -- i disable certificate checking
> mnsett = mkManagerSettings tlsset Nothing
> manager2  <- newTlsManagerWith mnsett
> response <- Network.HTTP.Client.httpLbs req2 manager2 

and i got TLS error : 

"InternalException (HandshakeFailed (Error_Protocol ("certificate rejected: [NameMismatch \"192.168.5.46\",LeafNotV3]",True,CertificateUnknown)))" 

But when i tried to use function "newManagerSettings" from "Network.HTTP.Client.Conduit" it worked !

> manager2  <- newManagerSettings mnsett
> response <- Network.HTTP.Client.httpLbs req2 manager2 

And i got proper response without any errors. 
Version of http-client-tls is 0.3.5.1 from lts-8.22

I hope my report helps to someone =)

**Comment by snoyberg** [comment]
Pinging @ivan-m.

**Comment by ivan-m** [comment]
What is `req2` so I can try testing this myself?

The way I've used (and why I wrote `newTlsManagerWith`) was to make a change to `defaultManagerSettings` (specifically to increase the timeout), so I haven't tested before with a manager created completely from scratch.

**Comment by ivan-m** [comment]
Can you maybe try with `TLSSettingsSimple True False False`? That's closer to the default value of `TLSSettings` and could help rule this out.

Also, what about using `newTlsManager` directly with the default settings?  The issue may be with TLS itself rather than http-client-tls.

**Comment by Haskell-mouse** [comment]
Here is how i create req2 

defRequest <- parseRequest ("https://192.168.5.46:8443/cgi-bin/fwrules.cgi")
  let request = defRequest  
                { method = "POST", 
                  requestBody = crRulReqBody service,   -- this is a large piece of text
                  requestHeaders = [("Origin","https://192.168.5.46:8443"),
                                    ("Accept-Encoding","gzip, deflate, br"),
                                    ("Accept-Language","en-US,en;q=0.8"),
                                    ("Upgrade-Insecure-Requests","1"),
                                    ("Authorization", "Basic myAuthtoken"),
                                    ("Content-Type","application/x-www-form-urlencoded"),
                                    ("Accept","text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"),
                                    ("User-Agent","Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/58.0.3029.110 Chrome/58.0.3029.110 Safari/537.36"),
                                    ("Cache-Control","max-age=0"),
                                    ("Referer","https://192.168.5.46:8443/cgi-bin/fwrules.cgi"),
                                    ("Connection","keep-alive")],
                  secure = True
                }

**Comment by Haskell-mouse** [comment]
>TLSSettingsSimple True False False

I have just tried this and get the same error (

**Comment by Haskell-mouse** [comment]
>  newTlsManager 

It of cource get me the same error : 

"Error_Protocol ("certificate rejected: [NameMismatch \"192.168.5.46\",LeafNotV3]",True,CertificateUnknown)" 

And names really mismatch. So - i need to disable checking certificate at all.

**Comment by ivan-m** [comment]
I don't think this has anything to do with `newTlsManagerWith`, unless there's an option I should be explicitly handling that I'm not.

Can you please [debug TLS](https://github.com/vincenthz/hs-tls#tls-issues) to see if it's the problem?

**Comment by Haskell-mouse** [comment]
But why "newManagerSettings"  works well ?

**Comment by ivan-m** [comment]
Because it doesn't use TLS?

**Comment by Haskell-mouse** [comment]
I tried 
> tls-simpleclient -d -v https://192.168.5.46 8443 

and got Name mismatch  error. 
But this 

> tls-simpleclient -d -v --no-validation  https://192.168.5.46 8443 

does not take me any errors, as it shoud...

**Comment by Haskell-mouse** [comment]
> Because it doesn't use TLS?

It does.

**Comment by tfausak** [comment]
I also ran into this problem. 

``` hs
>>> import Network.HTTP.Client -- http-client 0.5.7.0
>>> import Network.HTTP.Client.TLS -- http-client-tls 0.3.5.1
>>> import Network.Connection -- connection 0.2.8
>>> request <- parseRequest "https://wrong.host.badssl.com"
>>> let settings = mkManagerSettings (TLSSettingsSimple True False False) Nothing
>>> goodManager <- newManager settings
>>> badManager <- newTlsManagerWith settings
>>> httpNoBody request goodManager
-- Response {responseStatus = Status {statusCode = 200, statusMessage = "OK"}, ...}
>>> httpNoBody request badManager
-- *** Exception: HttpExceptionRequest Request { ... }
-- (InternalException (HandshakeFailed (Error_Protocol ("certificate rejected: [NameMismatch \"wrong.host.badssl.com\"]",True,CertificateUnknown))))
```

I think this happens because `newTlsManagerWith` passes `def` to `mkManagerSettingsContext'`.

https://github.com/snoyberg/http-client/blob/9f6d1cb4231e072cfb139b522e12ffcd2fda77f1/http-client-tls/Network/HTTP/Client/TLS.hs#L195

The corresponds to the TLS settings.

https://github.com/snoyberg/http-client/blob/9f6d1cb4231e072cfb139b522e12ffcd2fda77f1/http-client-tls/Network/HTTP/Client/TLS.hs#L80

So when you pass the manager settings to `newTlsManagerWith`, it ignores the `TLSSettings` within an uses the default (which validates certificates) instead.

**Comment by sophie-h** [comment]
+1. @ivan-m are you planning to address this issue?

**Comment by ivan-m** [comment]
Sorry, this had slipped my mind.

I may be able to look at this during the next two weeks.

**Comment by crockeea** [comment]
@ivan-m 
It only took me several days to find this bug. The way I'm using http-client-tls is:
```
let tlssets = TLSSettings $ ClientParams{clientUseMaxFragmentLength = ..., ...}
    mgrsets = mkManagerSettings tlssets Nothing
mgr <- newTlsManagerWith mgrsets
```

`newTlsManagerWith` calls `mkManagerSettingsContext'` with `def::NC.TLSSettings`, which is NOT what I expect to be passed in, since I explicitly created the `ManagerSettings` with custom `TLSSettings`. At a first glance, there doesn't appear to be a way to extract the TLS settings from `ManagerSettings`, which IMO is a flaw in the http-client library, but `newTlsManagerWith` is still extremely misleading.
