### ISSUE TITLE
Is there a recommended way of manipulating URLs in combination with http-conduit?

### ISSUE THREAD

**Issue by mbwgh** [snoyberg/http-client#291]
After having worked through the tutorial, I decided to try writing a small webcrawler, using `html-conduit`, `http-conduit` and `xml-lens`, among others. While these libraries seem to work nicely together, actually manipulating URLs in a type-safe manner using one of the libraries on stackage always feels like I am doing it wrong, especially if I have to awkwardly convert to and fro between `Text`, `ByteString` and `String`, and every URL library seems to leave some aspect to be desired which is covered by yet another one. And in the end, none of them feel like they really 'fit together' with the types in the `http-conduit` package.

Another option, and this is the one I finally decided on, was to just manipulate the `Request` values themselves. But while building requests from scratch is possible, there is no function `getRequestHost`, while `setRequestHost` exists, for instance. Assuming this is a design decision, do the `http-client`/`http-conduit` libraries take a stance on how this kind of problem should be approached (I saw a `toURI` function in an Internal module somewhere, yielding a `URI` from the `urls` package, which uses `Strings` internally...)? This is probably abusing the `Request` type, and I was only able to serialize/deserialize them in an ad-hoc manner.

In any case, addressing this would in my opinion make a great addition to either this tutorial, an as of yet non-existent one on haskell-lang, or as an example in the API-docs.

Edit: For completeness' sake I should note that this is surely kind of a beginner (at least this is what I consider myself as, when it comes to web-client programming) question, and not a library "issue" per se. So hopefully I didn't choose the wrong place or format to ask this question.

**Comment by snoyberg** [comment]
The situations with URL types is a bit difficult. I think the most tactical answer I can give you is that there are more complete accessors for the fields within a `Request` in the `Network.HTTP.Client` module.

**Comment by mbwgh** [comment]
Indeed, this module seems to expose some of the functionality I was missing, especially the `getURI` function. I don't know if I am going to go this way, since I didn't find the various escaping functions of the `network-uri` package (I seem to have this mixed up with `urls` before) straightforward to work with. Maybe I'll try my way around with `req`, which seems to make a great deal of type-safe uri manipulation as well. Nevertheless I consider my question answered, since now I know there is a public escape hatch into a dedicated uri manipulation library. Thanks for your quick reply, I shall close this issue now if it's alright.
