### ISSUE TITLE
(ConnectionFailure Network.BSD.getProtocolByName: does not exist (no such protocol name: tcp))) when trashing connections

### ISSUE THREAD

**Issue by reactormonk** [snoyberg/http-client#292]
Point at a bucket with a lot of small files. I got a `(ConnectionFailure Network.BSD.getProtocolByName: does not exist (no such protocol name: tcp)))` pretty reliably.
https://gist.github.com/reactormonk/8106134ccb59190b9cdf8eedd2b66cff

Fixing the issue by moving the sampling one back: https://gist.github.com/reactormonk/8106134ccb59190b9cdf8eedd2b66cff/revisions

```
batch-s3: TransportError (HttpExceptionRequest Request {
  host                 = "s3.eu-central-1.amazonaws.com"
  port                 = 443
  secure               = True
  requestHeaders       = <censored>
  path                 = "<censored>"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 0
  responseTimeout      = ResponseTimeoutMicro 70000000
  requestVersion       = HTTP/1.1
}
 (ConnectionFailure Network.BSD.getProtocolByName: does not exist (no such protocol name: tcp)))
```

**Comment by snoyberg** [comment]
Can you provide a repro that uses only the http-client and http-client-tls libraries?

**Comment by rsarres** [comment]
I had this problem running a Haskell app on an Ubuntu docker image. Installing build-essential package solved the problem.

**Comment by kingxueyuf** [comment]
Having the same issue as well

**Comment by snoyberg** [comment]
No minimal repro, and this is likely a file descriptor issue from the sound. Closing.

**Comment by reactormonk** [comment]
Yeah, the code runs out of file descriptors. See https://github.com/snoyberg/http-client/issues/307

**Comment by creichert** [comment]
I believe @exarkun is right. I had this issue recently and had to install `netbase`. If the issue persists, check the `/etc/hosts` file of the to make sure it's sane. I believe at minimum:

```
$ cat /etc/hosts
127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters
```

**Comment by ketzacoatl** [comment]
Installing `netbase` fixed this for me, `build-essential` wasn't enough. Without `netbase`, I was unable to use `cache-s3` or `stack build` (and ghc installs failed). It was a mess. After installing `netbase`, caching and builds worked fine. Does anyone know why `netbase` fixes this problem?

**Comment by bradrn** [comment]
I was getting this same error on a Yesod app when deployed to AWS Elastic Beanstalk. Installing `netbase` fixed it for me as well.

**Comment by tomjaguarpaw** [comment]
Specifically, the file that seems to be required is `/etc/protocols`

**Comment by tomjaguarpaw** [comment]
Also seems to require `/lib/x86_64-linux-gnu/libnss_files.so.2`.
