### ISSUE TITLE
setRequestBodyJSON comment is incorrect about what it sets

### ISSUE THREAD

**Issue by Fuuzetsu** [snoyberg/http-client#293]
Notably in https://github.com/snoyberg/http-client/blame/master/http-conduit/Network/HTTP/Simple.hs#L320 it says it sets header `…; charset=utf8` while the code sets `charset=utf-8`. Only the latter is correct http://www.iana.org/assignments/character-sets/character-sets.xhtml (along with its alias `csUTF8`).

**Comment by snoyberg** [comment]
Can you send a PR to update the docs?

On Fri, Aug 18, 2017 at 5:48 PM, Mateusz Kowalczyk <notifications@github.com
