### ISSUE TITLE
Inability to finalize manager resources

### ISSUE THREAD

**Issue by mgsloan** [snoyberg/http-client#294]
`closeManager` and `withManager` seem to be deprecated because they don't do anything that `newManager` doesn't do.  This means that there's no good way to create many managers and many connections, because you cannot rely on GC promptly finalizing the manager.

Some functions in wreq create a new manager for every single request (https://github.com/bos/wreq/blob/228673a98137c8ef172a9fdc80e6bf416d96ad4f/Network/Wreq/Internal.hs#L103).  Now, one might argue that this is a bug in that package.  Perhaps it should use a global IORef hack to have a global connection pool.  However, I think it is a bug to not be able to manually finalize your connections.  This also means that it is much easier to leak resources by accidentally hanging on to a manager.  Figuring out why some object is kept alive is generally much more difficult than figuring out why a bracket-like finalizer never ran.

Aside from this example, consider if you had a test-suite that ran something like a `main` function when executing each test.  If this main function creates a new manager and uses it, you could easily run out of connections if no GC occurs.

**Comment by snoyberg** [comment]
This is definitely a big in wreq, http-client is behaving as advertised. I've commented on this being a reason not to use wreq in the past.
