### ISSUE TITLE
Expose getters/fields of Request

### ISSUE THREAD

**Issue by Fuuzetsu** [snoyberg/http-client#296]
`Network.HTTP.Client.Types` is a private module hiding fields of `Request`. The only getter lenses for requests I can find are `getRequestHeader` and `getRequestQueryString`. There is a `Show` instance but that doesn't allow us a choice of what fields we want to see and in what format.

The usecase is simple: we want to define some default request for our application and end up with

```
ourRequest :: Request
ourRequest = … $ defaultRequest
```

Now we may wish to write a function such as

```
sendJSON :: ToJSON a => a -> IO 
sendJSON x = do
  let req = setRequestBodyJSON x
  getResponseBody <$> httpJSONEither >>= \case
    Left jsonExc -> do
      logErr $ "Failed to decode JSON in reply to request: " ++ show req
    Right{} -> …
```

The problem is that we're forced to `show`: in general I'm only interested in some things: body, path. I would also like them in format suitable for a logging framework. As it is, the `show` output is hard to read when shoved into logger as a String.

Re-exporting `Request` from some Internal module or providing getter lenses for more fields would be great.

**Comment by snoyberg** [comment]
Please see the `Network.HTTP.Client` module.

**Comment by Fuuzetsu** [comment]
Oh! I don't know how I completely missed that multiple times I looked through the module. Great, sorry for the noise.
