### ISSUE TITLE
Certificate has unknown CA

### ISSUE THREAD

**Issue by dmjio** [snoyberg/http-client#31]
I'm running a snap-server over TLS. I receive this error when attemping to HTTPS-POST from a backend server to the snap-server. The certs I'm using are not self-signed but rather legit RapidSSL certs.

``` haskell
*** Exception: TlsException (HandshakeFailed (Error_Protocol ("certificate has unknown CA",True,UnknownCa)))
```

After googling around it seems this is a common problem but none of the solutions I read worked for me, except for this https://haskell.g.hatena.ne.jp/suztomo/20120311/1331478324, which suggests accepting all certs, which is fine, but the API has changed in `http-client` and I don't think that option is available anymore. It seems according to the tls package docs there are some utilities for testing SSL. After installing `tls`I couldn't seem to find them in my cabal in directory. Here's the code I'm using below.

``` haskell
sendPost :: Command -> IO ()
sendPost UnknownCommand = return ()
sendPost cmd = do
  runResourceT $ do
        manager <- io $ newManager conduitManagerSettings
        r <- io $ parseUrl "https://myurl.com:443"
        let req = r
                 { method = "POST"
                 , secure = True
                 , port = 443
                 , path = "updates"
                 , redirectCount = 0 -- don't follow redirects
                 , requestBody = RequestBodyLBS (encode cmd)
                 , checkStatus = \_ _ _ -> Nothing -- accept any status code
                 }
        res <- http req manager
        io $ print "done"
```

**Comment by cdupont** [comment]
Hello,
I have the same error. I'm deploying a ubuntu basic image. Is there any way to make this work without modifying the code? I was thinking some apt package might need to be installed.

**Comment by cdupont** [comment]
OK, the answer was pretty simple: install `ca-certificates`.

**Comment by bradrn** [comment]
I was getting this same error on a Yesod app when deployed to AWS Elastic Beanstalk. Installing `ca-certificates` fixed it for me as well.
