### ISSUE TITLE
Connecting to a server, which aborts the SSL handshake, causes the opaque "resource vanished" exception instead of something meaningful

### ISSUE THREAD

**Issue by nikita-volkov** [snoyberg/http-client#312]
Here's a CURL session

    $ curl -v https://bigcinema.to:443
    * Rebuilt URL to: https://bigcinema.to:443/
    *   Trying 78.108.179.111...
    * Connected to bigcinema.to (78.108.179.111) port 443 (#0)
    * Server aborted the SSL handshake
    * Closing connection 0
    curl: (35) Server aborted the SSL handshake

And here's the according GHCi session, using "http-client":

    Rebase.Prelude> import qualified Network.HTTP.Client as A
    Rebase.Prelude A> import qualified Network.HTTP.Client.TLS as A
    Rebase.Prelude A A> manager <- A.newTlsManager
    Rebase.Prelude A A> request <- A.parseRequest "https://bigcinema.to:443"
    Rebase.Prelude A A> A.httpNoBody request manager
    *** Exception: HttpExceptionRequest Request {
      host                 = "bigcinema.to"
      port                 = 443
      secure               = True
      requestHeaders       = []
      path                 = "/"
      queryString          = ""
      method               = "GET"
      proxy                = Nothing
      rawBody              = False
      redirectCount        = 10
      responseTimeout      = ResponseTimeoutDefault
      requestVersion       = HTTP/1.1
    }
     (ConnectionFailure Network.Socket.sendBuf: resource vanished (Broken pipe))

**Comment by nikita-volkov** [comment]
I'm guessing however that this could be an issue in the upstream dependencies. Either way, please, confirm and suggest something.

**Comment by snoyberg** [comment]
Please follow the debugging instructions at:
https://github.com/vincenthz/hs-tls#tls-issues

**Comment by nikita-volkov** [comment]
Thanks for the prompt response!

```
$ tls-simpleclient -d -v bigcinema.to 443
sending query:
GET / HTTP/1.0



debug: >> Handshake [ClientHello TLS12 (ClientRandom {unClientRandom = "\132\128\f\206\v\202\&9M\180h\240n\172\157\255\210\131\158)\150\144\202Z\229\158\237\243\234\b\DEL\STX\213"}) (Session Nothing) [49195,49196,49199,49200,158,159,49187,49188,49191,49192,103,107,49161,49162,49171,49172,51,57,156,157,61,60,53,47,56,50,10,5] [0] [ExtensionRaw 0 "000f00000c62696763696e656d612e746f",ExtensionRaw 65281 "00",ExtensionRaw 10 "0006001700180019",ExtensionRaw 11 "0100",ExtensionRaw 13 "001006010603050105030401040302010202"] Nothing]
debug: >> Alert [(AlertLevel_Fatal,InternalError)]
tls-simpleclient: Network.Socket.sendBuf: resource vanished (Broken pipe)
```

So, yes, apparently this comes from the "tls" package". However, until "tls" provides a more informative handling of this, can "resource vanished" during handshake be interpreted as some form of a clearer handshake failure in "http-client"?

**Comment by snoyberg** [comment]
I'm honestly not sure what you'd like it to do here. http-client is already
giving you an exception indicating exactly what request caused the
exception. What change are you proposing?

**Comment by nikita-volkov** [comment]
Nevermind. Looking at the code, I've realised that there's no way to implement a work around in "http-client". It needs to be fixed in either the "tls" or the "connection" package.

**Comment by ocheron** [comment]
This looks a lot to what was reported in vincenthz/hs-tls#250 and fixed in `tls` HEAD (so that the exception is correctly wrapped as a `HandshakeFailure`).
