### ISSUE TITLE
Connecting to application behind load balancer

### ISSUE THREAD

**Issue by andrewthad** [snoyberg/http-client#315]
Normally, the `defaultManagerSettings` work fine for almost everything I do. However, I just ran into a situation where I realized that the connection manager provided by `http-client`. I have a load balancer with around a dozen ElasticSearch nodes behind it. Since the `Manager` wants to keep connections alive, it ends up thwarting the load balancer. The most obvious workaround is just to call `newManager` every time I call `httpLbs`. But, I find this a little unsatisfying. I don't actually need a new `Manager` every time; I just need a `Manager` that doesn't keep connections open. Is there a way to create such a `Manager`?

I suspect that I can set `managerConnCount` to zero, but I'd like to make sure that doing so will actually have the right behavior.

**Comment by snoyberg** [comment]
I honestly don't know offhand, sorry. I _think_ you may also be able to use `managerModifyRequest` to add the `connection: close` request header.

**Comment by andrewthad** [comment]
I read through more of the code, and I'm pretty sure that setting `managerIdleConnectionCount` to zero will do what I need. I'll be testing it today.

**Comment by andrewthad** [comment]
Yeah, that's definitely the way to go. I've put up a [PR that documents this](https://github.com/snoyberg/http-client/pull/316).

**Comment by creichert** [comment]
@andrewthad I'm just curious, could this be explained by stickiness settings on the load balancer? I don't think you are wrong here, I just want to undrestand what happened for my own use-case. Can you clarify how you knew the connection thwarted the load balancer? thanks!

**Comment by andrewthad** [comment]
Stickiness was (and is) disabled on the load balancer. If it were on, it would have a devastating effect on the application. We have 12 worker nodes (running the haskell application) and 12 elasticsearch nodes, and we need to ensure that the worker do not continually target the same elasticsearch nodes. Even a one-to-one permanent mapping would be bad, since the worker nodes may not all do an equal amount on work. I am confident that there is no stickiness in play because I can see that the number of connections to each elasticsearch nodes fluctuates over time.

I knew that `http-client`'s default settings twarted the load balancer because `http-client` creates a pool of tcp connections that it reuses between different requests. A load balancer can only pick targets for newly established connections. That is, it cannot take an active TCP connection and switch out which host on the backend is receiving the traffic. Since `http-client` leaves connections open for a potentially long period of time, the worker nodes stayed connected to the same elasticsearch nodes of the back end as long as there wasn't a giant lull in the http traffic to elasticsearch.

**Comment by thomasjm** [comment]
This can be closed since #316 was merged, right?

**Comment by andrewthad** [comment]
Yes, closing.
