### ISSUE TITLE
http-client-tls-0.3.5.2 triggers `TlsNotSupported` in Stack

### ISSUE THREAD

**Issue by borsboom** [snoyberg/http-client#325]
See https://github.com/commercialhaskell/stack/issues/3848 for reports.

**Comment by borsboom** [comment]
@snoyberg I know you already reproduced this, just filing the issue to keep track.

**Comment by tfausak** [comment]
Oh dear. Sorry! I'll look into this.

**Comment by snoyberg** [comment]
I think I've got it... these functions are really becoming a mess though.

**Comment by tfausak** [comment]
Great! Let me know if I can help.
