### ISSUE TITLE
compile failure

### ISSUE THREAD

**Issue by hvr** [snoyberg/http-client#327]
see https://ci.appveyor.com/project/hvr/hackage-security/build/12/job/t4l3a6vkcss1yi7h#L1638

**Comment by snoyberg** [comment]
Thanks for the report. I'm unable to reproduce, but adding `FlexibleContexts` is a relatively benign change. I've pushed 24488e4a403b298f34d996fd11ae883bb29ecdb9, can you confirm if this fixes the problem for you?

**Comment by snoyberg** [comment]
From other PRs, it seems like this was in fact resolved by the commit I pushed, closing.
