### ISSUE TITLE
Unexpected TlsNotSupported when proxying through Fiddler

### ISSUE THREAD

**Issue by Porges** [snoyberg/http-client#337]
I was trying to route my requests through [Fiddler](https://www.telerik.com/fiddler) (Windows version) for debugging, but when I try that I get a `TlsNotSupported` (even though there's no TLS involved).

Using the TLS manager I get a header parse error.

I'm not sure where to start with this 🙁

**Comment by snoyberg** [comment]
I don't really know either, there's not enough information to understand the bug report. What URL is failing? Can you provide some kind of minimal repro of a request that fails?

If it's saying `TlsNotSupported`, I'm fairly certain that you _are_ trying to connect over TLS. It may be that you're getting redirected to a different URL.

**Comment by Porges** [comment]
Here's the non-TLS manager:

```
*** Exception: HttpExceptionRequest Request {
  host                 = "127.0.0.1"
  port                 = 10000
  secure               = False
  requestHeaders       = [("Authorization","<REDACTED>"),("Date","Mon, 05 Mar 2018 10:58:27 GMT"),("x-ms-version","2017-07-29")]
  path                 = "/devstoreaccount1"
  queryString          = "?comp=list"
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 TlsNotSupported
```

And the TLS manager:

```
*** Exception: HttpExceptionRequest Request {
  host                 = "127.0.0.1"
  port                 = 10000
  secure               = False
  requestHeaders       = [("Authorization","<REDACTED>"),("Date","Mon, 05 Mar 2018 10:59:20 GMT"),("x-ms-version","2017-07-29")]
  path                 = "/devstoreaccount1"
  queryString          = "?comp=list"
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (InternalException (HandshakeFailed (Error_Packet_Parsing "Failed reading: invalid header type: 72\nFrom:\theader\n\n")))
```

No redirects (count is still 10), I can hit `127.0.0.1:10000` in browser and it's definitely HTTP. `curl` is able to retrieve the page...

The error is similar to this one: https://github.com/snoyberg/http-client/issues/252#issuecomment-322585628

**Comment by Porges** [comment]
I think I'll need to spin up Wireshark 🙂

**Comment by Porges** [comment]
Actually, looking at the code perhaps non-TLS proxies are not supported?

**Comment by snoyberg** [comment]
Non-TLS proxies should definitely be supported.

**Comment by Porges** [comment]
I must be reading it wrong then 😁
