### ISSUE TITLE
Best way to mock a Response?

### ISSUE THREAD

**Issue by TobyGoodwin** [snoyberg/http-client#338]
This is more of a question than anything else.

`Response` is an opaque type, right? `N.H.C.Types` exports `Response (..)`, but is a hidden module. `N.H.Client` and `N.H.Conduit` reexport a plain `Response`.

I'm writing a library that interacts with a RESTful API, and for testing I want to mock what the server does. For simple cases it's sufficient to return just the response body, but for some of the more intricate interactions I need to access the status code and headers. It really would be handy to be able to construct my own `Response`.

The best idea I've come up with so far is to define

    data MyResponse = MyResponse Status ResponseHeaders LBS.ByteString

For the real case I can unpack the `Response` into `MyResponse`, and for the mocked case I can of course create whatever `MyResponse` values I like.

Is there a better approach?

**Comment by snoyberg** [comment]
You could reach into the Internal module and use the `Response` data constructor from there: https://www.stackage.org/haddock/lts-11.1/http-client-0.5.11/Network-HTTP-Client-Internal.html#t:Response

**Comment by TobyGoodwin** [comment]
Thanks! That works (of course) and makes the code look very much more sensible.
