### ISSUE TITLE
http-conduit: add Network.HTTP.Types.Query to Network.HTTP.Simple

### ISSUE THREAD

**Issue by rtentser** [snoyberg/http-client#340]
I currently working on a code that uses Network.HTTP.Simple for a requests and one of a common tasks is a generation of a query strings. I don't like that i need to import Network.HTTP.Types for Query or create a sinonym by myself. I think that including this type in Network.HTTP.Simple will make the module a little simpler for understanding and using.

**Comment by snoyberg** [comment]
If you're talking about just reexporting that type, no objection from me.
Want to send a PR?

**Comment by rtentser** [comment]
> If you're talking about just reexporting that type, no objection from me.
I also think about using it in type signatures of setRequestQueryString and getRequestQueryString.
> Want to send a PR?
I don't think i'll be able to compile git version of http-conduit any time soon, so feel free to commit.

**Comment by rtentser** [comment]
https://github.com/snoyberg/http-client/pull/343
