### ISSUE TITLE
`Managed` might be getting GC'd too early

### ISSUE THREAD

**Issue by bitemyapp** [snoyberg/http-client#351]
https://www.reddit.com/r/haskell/comments/8nh6ud/preventing_an_object_from_getting_gced_and/

From the thread,

>Currently, I'm trying to create a websocket client library supporting websocket connection via an HTTP proxy server. To implement the complex features such as referring http_proxy environment variable, I decided to combine the http-client package with the websockets package to reuse http-client's features related to proxy, TLS and so on.

>As an experiment, I've written an example to connect with websocket via an HTTP proxy server:
https://github.com/snoyberg/http-client/compare/master...igrep:proxied-connection-spike

>But the example program ws-sample sometimes successfully connects to the server over the proxy, and sometimes fails.

>According to my debug code, the connection gets closed before the application begins to write when it fails. Because the connection objects in http-client are attached with a finalizer to be closed automatically when their Managed object gets GCed. Then, the Managed object gets GCed before my example program finishes the connection.

Cf. https://github.com/gelisam/sodium/commit/4a16ab717dc4776cc87fc2270685344771534c24

>I once fixed a similar regression in sodium, presumably introduced by an improvement to the ghc optimizer allowing unused IORefs to be garbage collected early. This is usually a good thing, but not in the case in which you rely on the IORef getting garbage collected after a particular point in the program. At the time, the solution was to introduce a readIORef call at that point in the program, to make sure the IORef is still alive at that point. Since I don't see any such call in the http-client code you linked, I suspect http-client might have suffered from a similar regression.

**Comment by bitemyapp** [comment]
Looks like inserting a useless `readIORef` to keep the reference alive fixes it but I'm wondering if there's a cleaner way to do this.

**Comment by snoyberg** [comment]
It would be great to knock this down to a more minimal reproduction. I'm a bit concerned that this may not in fact be the source of the bug. I don't have the code in front of me right now, but I didn't think closing a Manager closed open connections.

**Comment by snoyberg** [comment]
Fairly certain this was related to #352, and wasn't actually a bug in the library, but someone's usage of its internals.
