### ISSUE TITLE
Alternative version of `httpLbs` which uses lazy I/O?

### ISSUE THREAD

**Issue by TerrorJack** [snoyberg/http-client#370]
Can we provide an alternative version of `httpLbs` which performs lazy I/O? I'm aware lazy I/O bites people sometimes, but this allows people to work with large response body (e.g. reading from a URL and immediately stream to a file) with improved memory footprint, without having to use conduit-based API.

If this sounds reasonable, I'll open a pull request.

**Comment by snoyberg** [comment]
It sounds pretty dangerous, and I'm not particularly convinced there's a real benefit. If people are conduit-averse, there are bindings for most other streaming libraries I believe. I'd be slightly more comfortable with a `withHttpLbs` style function, but still overall not in favor.

**Comment by TerrorJack** [comment]
I see, feel free to close this issue then. "Dangerous" indeed since I just found out it's tricky to make exception handling work nicely with `unsafeInterleaveIO`.
