### ISSUE TITLE
Allow to retrieve parse errors for URLs in a more typed way?

### ISSUE THREAD

**Issue by sol** [snoyberg/http-client#378]
Recently I ended up writing code along the lines of

```haskell
parseRequest_ :: String -> Either HttpException Request
parseRequest_ = first toHttpException . parseRequest
  where
    toHttpException :: SomeException -> HttpException
    toHttpException err = case fromException err of
        Just e -> e
        Nothing -> error "this should never happen"
```

@snoyberg do you think we want to better support this use case in `http-client`?

**Comment by snoyberg** [comment]
I'm OK with PRs for both of these. To be clear: I'm picturing your proposed `parseRequest_` kind of function would be a new, separate function from anything that currently exists, right?

**Comment by snoyberg** [comment]
Only objection would be that this is still a really big data type to return
as an error. Why not provide a more precise exception? Or more directly,
what's your goal here?

**Comment by sol** [comment]
> Only objection would be that this is still a really big data type to return as an error.

Yes, that is true and bothers me somewhat.  I was hopping a string works, however `InvalidUrlException` (the only value that is ever returned from `parseRequest`) takes two string arguments.  So either we will end up with a breaking change of some sort or we introduce a new type

```
data UrlParseError = UrlParseError String String
```

Actually, now that I look at it, an other option would be that we return a single string, the error reason which is the second argument to `InvalidUrlException` and rely on the fact that the caller already knows the first argument (the URL). That might still result in minor changes in how the URL is formatted in error messages, but may be ok with a major version bump.

**Comment by sol** [comment]
Hey, thanks for your reply.

> I'm not following what this other option would be or why it would require a major version bump.

In terms of code that would be something like https://github.com/snoyberg/http-client/commit/f31a49506bca5da6eff8bf1c59bed31e13b361eb.

It's a minor breaking change at the point we implement `parseRequest` in terms of `parseRequestEither` (https://github.com/snoyberg/http-client/commit/75e63ef661bd0a4c728c140b92b8434ebaf0f6bb).  Before the the URL in error messages (the first argument to `InvalidUrlException` might have gone through a `fmap show . parseURI . escapeURIString isAllowedInURI` cycle.  With this change the URL in error messages will always be what the user provided verbatim.

Now we could of course skip https://github.com/snoyberg/http-client/commit/75e63ef661bd0a4c728c140b92b8434ebaf0f6bb to keep it 100% backwards compatible if we care.

If you think this is a good idea then I'll finish it up + added documentation.  Note that with this approach `parseRequestEither` will not support HTTP verbs in front of the URL.

> I'm still not convinced I understand the use case here to be honest, given that the much larger HttpException type seems to be acceptable in place of SomeException.

My use case at hand is that URLs can be provided by the user.  On malformed URLs I need to produce suitable error messages that I can show to the user.  `HttpException` works for my use case as I already have a suitable format function for all of `HttpException`.  But yes, that type is larger than what we need.  So if we want to do something here then defining the domain accurately makes sense.

**Comment by sol** [comment]
If we think this is getting too messy, then as a middle ground, maybe let's just add `setUriEither` (https://github.com/snoyberg/http-client/pull/379).  With this it's easy to implement `parseRequestEither` the way I want.

**Comment by sol** [comment]
Closing in favor of https://github.com/snoyberg/http-client/pull/379.
