### ISSUE TITLE
Documentation for responseTimeout field out of date

### ISSUE THREAD

**Issue by masaeedu** [snoyberg/http-client#397]
The comment under the field [here](https://github.com/snoyberg/http-client/blob/74f29851e904b44a7225e80a877ff1b60d23d705/http-client/Network/HTTP/Client/Types.hs#L522) refers to the behavior of the request when you supply `Nothing` for this field, but the type is no longer `Maybe` anything. It's been changed to a custom `ResponseTimeoutDefault` datatype.

I don't use the library so I'm not sure, but I think mentions of `Nothing` should be replaced with `ResponseTimeoutDefault`; I don't know whether the rest of the comment is still correct.

**Comment by snoyberg** [comment]
Thanks! I've updated the documentation to be clearer
