### ISSUE TITLE
fails with InvalidHeader on url that is supported by curl and wget

### ISSUE THREAD

**Issue by joeyh** [snoyberg/http-client#398]
http-client fails to download the url https://datahub-khvul4ng.udes.genap.ca/ALL.chr10.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz , with an InvalidHeader exception. The same url can be downloaded by wget, curl, and firefox.

Examining the http response (with curl -v), it is indeed a bit broken:

         < Server: openresty/1.7.10.1
        < Date: Wed, 10 Apr 2019 13:57:10 GMT
        < Content-Type: application/octet-stream
        < Content-Length: 773788987
        < Connection: keep-alive
        < Last-Modified: Mon, 11 Mar 2019 16:35:02 GMT
        < ETag: "5c868e36-2e1f153b"
        < Accept-Ranges: bytes
        < Strict-Transport-Security: max-age=15768000; includeSubdomains;
        < preload
        < X-Frame-Options: DENY
        < X-Content-Type-Options: nosniff

In particular, the "preload" has somehow ended up on its own line, not part of the Strict-Transport-Security header.

Looks like the code that throws the exception is here:

    parseHeader :: S.ByteString -> IO Header
    parseHeader bs = do
        let (key, bs2) = S.break (== charColon) bs
        when (S.null bs2) $ throwHttp $ InvalidHeader bs
        return (CI.mk $! strip key, strip $! S.drop 1 bs2)

Since there's no colon, the snd is null.

In my application I'd rather that http-client applied Postel's law the same way that curl, wget, and firefox do, by not throwing an exception here, but ignoring (or somehow logging a problem with) the malformed header. 

One way to do it would be this, so when there's a missing colon, it still parses a Header, just one with an empty value.

    parseHeader :: S.ByteString -> IO Header
    parseHeader bs = do
        let (key, bs2) = S.break (== charColon) bs
        if S.null bs2
                then return (CI.mk $! strip key, bs2)
                else return (CI.mk $! strip key, strip $! S.drop 1 bs2)

(Of course that could be refactored.)

**Comment by snoyberg** [comment]
If the other HTTP libraries are accepting this, we may as well too. You up for sending a PR after confirming the change addresses your use case?

**Comment by joeyh** [comment]
I've confirmed the change works. Pr coon.
