### ISSUE TITLE
Requests to 127.0.0.1 shouldn’t fail just because there’s no v4 address assigned to some other interface

### ISSUE THREAD

**Issue by michalrus** [snoyberg/http-client#400]
I stumbled upon this after creating a systemd service, which started on boot, and called `http://127.0.0.1:8094/some-path`, which failed with:

```
Address family for hostname not supported
```
![Screenshot-20190428-154754](https://user-images.githubusercontent.com/4366292/56866881-9d085e80-69d6-11e9-9323-8b06cc4489b7.png)

This was because I forgot to set `After=network.target`, so interfaces other than `lo 127.0.0.1` didn’t have their IP set (yet).

Because of this line:
https://github.com/snoyberg/http-client/blob/c1c6ffa9e7bf3556f8577b12fc2ccb3e92b080a4/http-client/Network/HTTP/Client/Connection.hs#L149
… the whole thing failed, according to `man getaddrinfo`:

```
       If hints.ai_flags includes the AI_ADDRCONFIG flag, then IPv4
       addresses are returned in the list pointed to by res only if the
       local system has at least one IPv4 address configured, and IPv6
       addresses are returned only if the local system has at least one IPv6
       address configured.  The loopback address is not considered for this
       case as valid as a configured address.  This flag is useful on, for
       example, IPv4-only systems, to ensure that getaddrinfo() does not
       return IPv6 socket addresses that would always fail in connect(2) or
       bind(2).
```

But even then, calls to 127.0.0.1 shouldn’t fail.

Probably `http-client` shouldn’t even be setting `AI_ADDRCONFIG`. There is really no reason to be using it — e.g. `curl` doesn’t.

**Comment by michalrus** [comment]
Also, a few lines below, `http-client` is assuming IPv4 without looking at `HostAddress` family?
https://github.com/snoyberg/http-client/blob/c1c6ffa9e7bf3556f8577b12fc2ccb3e92b080a4/http-client/Network/HTTP/Client/Connection.hs#L159
But that’s probably for another issue?

**Comment by snoyberg** [comment]
The exact configuration here has been built up over years via some initial code a multiple PRs. I can't justify why all the different settings are as they are currently set. This specific flag seems to have come from:

https://github.com/snoyberg/http-conduit/commit/34d0e84f8aa4ca2429ded57c9ae109045bbe7849

And the pull request:

https://github.com/snoyberg/http-enumerator/pull/4

Unfortunately, due to lack of information in the original commit, I don't really know what use cases will be broken by making modifications here.

**Comment by snoyberg** [comment]
@kazu-yamamoto as the network maintainer, do you perhaps have some insights or recommendations here?

**Comment by kazu-yamamoto** [comment]
I guess that @michalrus is using Linux.
And I believe that `lo` has 127.0.0.1 already when `http-client` is used.
So, I don't understand why the error is returned with `AI_ADDRCONFIG`.
We have at least 127.0.0.1 at this moment.

**Comment by michalrus** [comment]
@kazu-yamamoto true, Linux.

It’s right there in the manual excerpt I cited:

```
       If hints.ai_flags includes the AI_ADDRCONFIG flag, then IPv4
       addresses are returned in the list pointed to by res only if the
       local system has at least one IPv4 address configured, and IPv6
       addresses are returned only if the local system has at least one IPv6
       address configured.  The loopback address is not considered for this
       case as valid as a configured address.  This flag is useful on, for
       example, IPv4-only systems, to ensure that getaddrinfo() does not
       return IPv6 socket addresses that would always fail in connect(2) or
       bind(2).
```

Esp. that part:

```
The loopback address is not considered for this case as valid as a configured address.
```

**Comment by kazu-yamamoto** [comment]
@snoyberg I looked into `AI_ADDRCONFIG` but I could not find any information. I guess `AI_ADDRCONFIG` is not so important recently. I would like to recommend you to remove it since @michalrus faces the problem.

**Comment by snoyberg** [comment]
In that case: @michalrus would you like to take a stab at a PR? It would be best if you wrote and tested it to confirm it addresses your issue.

@kazu-yamamoto I think similar logic is used in Warp implicitly right now via `streaming-commons`, we may want to look into whether changes are prudent there as well.

**Comment by kazu-yamamoto** [comment]
In the server side, it is unlikely that no address is configured when servers run.
But I don't have strong opinions.

**Comment by iliastsi** [comment]
Hey there, this is also failing on Debian (see [#962913](https://bugs.debian.org/962913)). Is there any progress with fixing it, or should we disable the tests?

**Comment by snoyberg** [comment]
I've opened #437. If CI passes, I'll merge and release.
