### ISSUE TITLE
`JSONParseException` when the response has trailing whitespace

### ISSUE THREAD

**Issue by madjar** [snoyberg/http-client#401]
When making a call to `Network.HTTP.Simple.httpJSON`, if the response is a valid json but has trailing whitespace, and the trailing whitespace is included in the Content-Length, a JSONParseException is raised.

For example:
```
> getResponseBody <$> httpLBS "http://urlecho.appspot.com/echo?status=200&Content-Type=text%2Fjson&body={}  "
"{}  "

> getResponseBody <$> httpJSON "http://urlecho.appspot.com/echo?status=200&Content-Type=text%2Fjson&body={}  " :: IO Value
JSONParseException ... (ParseError {errorContexts = [], errorMessage = "endOfInput", errorPosition = 1:3 (2)})
```

This does not happens if the whitespace is beyond the Content-Length (tested with nc).

This looks like it's a consequence of the fixes to #395.

**Comment by snoyberg** [comment]
My mistake in testing the original code, I thought I'd covered this case. I also had a bad assumption about how aeson parsing works. I've just pushed a commit to master (aa021b3e92734360424519661b2349d3e54eb061), would you mind testing it to confirm it works for you?

**Comment by madjar** [comment]
This works perfectly, thanks a lot!
