### ISSUE TITLE
Can't set both settingDisableCertificateValidation and ResponseTimeout

### ISSUE THREAD

**Issue by caphesuanong** [snoyberg/http-client#402]
Is it possible to adjust both settingDisableCertificateValidation and ResponseTimeout for the same connection? I'd like a TLS manager that does not do certificate validation and has fast timeouts. Looking at the API it appears I can have one or the other but not both. Am I missing something?

**Comment by snoyberg** [comment]
Can you give a code sample of what you've tried?

**Comment by caphesuanong** [comment]
Sure. I could write:
```
tlsManagerSettings { managerResponseTimeout = responseTimeoutMicro 1000000 }
```

or

```
mkManagerSettingsContext 
   Nothing
   (TLSSettingsSimple {
      settingDisableCertificateValidation = True,
      settingDisableSession = False,
      settingUseServerName = True
   })
   Nothing
```

Both return `ManagerSettings`.But it's not obvious how to get a managerSettings with `settingDisableCertificateValidation = True` and `managerResponseTimeout = responseTimeoutMicro 1000000`.

**Comment by snoyberg** [comment]
Does this work?

```haskell
mySettings =
  part1 { managerResponseTimeout = responseTimeoutMicro 1000000 }
  where
    part1 = mkManagerSettingsContext
       Nothing
       (TLSSettingsSimple {
          settingDisableCertificateValidation = True,
          settingDisableSession = False,
          settingUseServerName = True
       })
       Nothing
```

**Comment by caphesuanong** [comment]
Yes, works! Thank you.
