### ISSUE TITLE
Print requestBody on HttpException

### ISSUE THREAD

**Issue by googleson78** [snoyberg/http-client#404]
Looking at the `Show` instance for `Request` it has a commented out 

```haskell
--, "  requestBody          = " ++ show (requestBody x)
```

Would it be desirable to somehow print it anyway?

**Comment by snoyberg** [comment]
Yes, there are at least two reasons:

1. For many of the `RequestBody` constructors, there's no way to purely print the request body (those which use streaming)
2. There may be a security concern with including this information in error messages

**Comment by snoyberg** [comment]
Also, congrats on getting lucky number 404 🎈
