### ISSUE TITLE
parseRequest causes exception for valid input

### ISSUE THREAD

**Issue by SoonWonMoon** [snoyberg/http-client#409]
Hi. I found parseRequest throws `InvalidUrlException` when input url contains bracket (`'['` or `']'`).
I think parseRequest should treat brackets properly like parentheses.

**Comment by SoonWonMoon** [comment]
Oh, I noticed just now that It was due to network-uri package.

**Comment by snoyberg** [comment]
Please open up an issue upstream with network-uri, I don't intend to change
the behavior on http-client versus that package.

**Comment by SoonWonMoon** [comment]
Thanks. I just notices that too.
