### ISSUE TITLE
Open the internal API for `Manager`

### ISSUE THREAD

**Issue by symbiont-eric-torreborre** [snoyberg/http-client#414]
Hi, we have a use case where it would be nice to be able to access the `mResponseTimeOut` function on `Manager` in order to put `responseTimeoutNone` on _some_ requests.

In principle we could have a (not very pretty work-around) by using `managerModifyRequest`. We could set a dummy header `X-NoTimeout` on the `Request` and use this header as a flag to set no timeout using `managerModifyRequest`. Unfortunately we are currently using `http-client` through Servant and `servant` does not give us an easy access to the current `Request` headers (at this stage in our code we have `ClientM` calls).

If you think that opening up the API is a good idea I would be glad to open a PR. Thanks!

**Comment by snoyberg** [comment]
You can already set a response timeout per-request with [`responseTimeout`](https://www.stackage.org/haddock/nightly-2019-09-15/http-client-0.6.4/Network-HTTP-Client.html#v:responseTimeout). I prefer not exposing internals (especially with a stable API guarantee) unless we have to.

**Comment by symbiont-eric-torreborre** [comment]
Sorry, I actually didn't realize I could access the `Network.HTTP.Client.Internal` module. I thought I had tried that before and that didn't work. BTW I would have been fine with modifying requests directly but Servant does not give us a way to do this easily :-(.

**Comment by snoyberg** [comment]
No worries.
