### ISSUE TITLE
ResponseTimeout behaviour

### ISSUE THREAD

**Issue by defanor** [snoyberg/http-client#416]
Currently (in http-client 0.5.13, and apparently in the current master branch) the `ResponseTimeout` setting seems to only apply to reading response headers, and not response body. If it is the intended behaviour, perhaps it should be mentioned in the documentation.

**Comment by snoyberg** [comment]
It is intended, the client side can control that body timeout itself, and may intentionally read the body at a slower speed. PR for docs welcome!

**Comment by lyokha** [comment]
Just in case, I made a custom time-limited version of `brRead` and `httpLbs` (https://github.com/lyokha/http-client-brread-timeout) to apply the response timeout in between body read events. The implementation is very simple and straightforward. This is to mitigate my own issues with a buggy and unreliable HTTP server.
