### ISSUE TITLE
Add http-client-openssl back to stackage?

### ISSUE THREAD

**Issue by arianvp** [snoyberg/http-client#418]
I'm not sure if this is the right place to open this issue. I'm rather unfamiliar with the stackage packaging infrastructure.

At some point, http-client-openssl was in stackage, but it seems to have disappeared after `12.26` https://www.stackage.org/package/http-client-openssl/snapshots

I was wondering what the reason for that was and if we could add it back?

**Comment by snoyberg** [comment]
I'd recommend opening a PR against the Stackage repo itself to unblock this
package.

**Comment by juhp** [comment]
It is in lts-15 and 16 and nightly

**Comment by arianvp** [comment]
Great!
