### ISSUE TITLE
Add haskell tag to Github repo

### ISSUE THREAD

**Issue by epogrebnyak** [snoyberg/http-client#422]
I suggest the repo visibility will benefit with following tags in repo description:

- haskell
- http-client

[req](https://github.com/mrkkrp/req) library that uses `http-client` library provides these tags.

The Haskell resources are rather scarce on Github, so anything that increases visibility helps the users.

**Comment by snoyberg** [comment]
Added. Not saying I'll do this in general, since it would be a lot of effort to tag up all of my repos.
