### ISSUE TITLE
Add support for URL fragments

### ISSUE THREAD

**Issue by mrkkrp** [snoyberg/http-client#424]
Some users of `req` want to perform calls with URLs that contain fragments: https://github.com/mrkkrp/req/issues/73. I cannot support this in `req` if `http-client` doesn't support it. It would be nice to add this.

*(No, I myself don't have time to open a PR.)*

**Comment by geekingfrog** [comment]
After some digging (https://tools.ietf.org/html/rfc7230#section-5.3 and https://www.ctrl.blog/entry/recover-url-fragment-requests.html) it seems a client should not send any fragment. So http-client not sending anything is OK and nothing needs to be done. This issue can be closed.

**Comment by snoyberg** [comment]
Agreed
