### ISSUE TITLE
Cookie equality should not be replacabiltiy

### ISSUE THREAD

**Issue by fisx** [snoyberg/http-client#433]
As defined here:

https://github.com/snoyberg/http-client/blob/73abb278e6c326e924c96e1f0f3518b747b06a84/http-client/Network/HTTP/Client/Types.hs#L266-L271

This is useful as an equivalence relation, but it is very surprising when you're comparing two cookies for other reasons, and expect `Eq` to mean equality.

Loosely related: https://github.com/snoyberg/http-client/issues/410

Thanks!

**Comment by snoyberg** [comment]
Can you more clearly state what you're asking for?

**Comment by fisx** [comment]
See #435.  My motivation to bring this up is that it took us too much time to figure out that two cookies were not actually identical, but equivalent in the sense that one should overwrite the other.

I propose to add two functions: `equal :: Cookie -> Cookie -> Bool` (which does what I'm testing) and `equiv :: Cookie -> Cookie -> Bool` (which implements the `Eq` instance as it is now), and then debating whether `Cookie` should have an `Eq` instance at all, and which.

The downside of keeping the `Eq` instance as is is that more people may stumble the way we did.  The downside of changing it is that existing code will change behavior.

Propose to drop the `Eq` instance and force people to use `equal` or `equiv` to make their code less surprising to both them and their readers.

I understand that this is a disruptive change, but it's the best I could come up with.  Perhaps somebody has a better idea?

**Comment by fisx** [comment]
I feel I still haven't given you a good answer to the question "what problem do I want to solve", but "I" just thought of one (thanks @soenkehahn): `instance Eq Cookie` breaks [substitutivity](https://www.stackage.org/haddock/lts-15.4/base-4.13.0.0/Prelude.html#t:Eq): two cookies can be `==`, even though their `cookie_value`s are `/=`.

**Comment by snoyberg** [comment]
OK, got it, that's reasonable. I agree: these kinds of `Eq` instances aren't a good idea, I'm not sure why I added it in the first place. I'm OK with removing it, even if it's a breaking change. Would you be interested in sending a PR to do that?

**Comment by fisx** [comment]
I think I know now why it was done :).  It was a little less trivial to remove than I expected, but I made a suggestion here: #435.

- Ord could also use some more love, but I'd do that separately (see #410).
- I hope I got the Semigroup instance right.  It's still using the semantics of the old `Eq` instance, but I *think* that's ok here.
- Would you like to drop the Eq instance of `Response` as well in favor of a function `equalResponse`?  (I would not do the `equivResponse`, but no strong opinions.)
- I hope I got the style consistent, if not please let me know.

Looking forward to your suggestions!
