### ISSUE TITLE
setRequestBodyURLEncoded and urlEncodeBody adds newline word8 that is not a valid value

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [snoyberg/http-client#444]
When using `setRequestBodyURLEncoded` a newline is tacked onto the end and included in the `Content-Length` count.

`setRequestBodyURLEncoded [("abc","def"),("ghi","jkl")]` should have a content length of 12 but has 13 because the the newline that is added.

**Comment by snoyberg** [comment]
Do you have a repro of this behavior causing things to break?

**Comment by BebeSparkelSparkel** [comment]
Was trying to isolate this for a while and I was doing something stupid. Sorry to bother you.
