### ISSUE TITLE
Separating aeson

### ISSUE THREAD

**Issue by kazu-yamamoto** [snoyberg/http-client#448]
This is not a strong requirement.

But building `aeson` takes too much time. It would be nice if JSON stuffs are provided in another package, for instance, from `http-conduit-json`.

**Comment by snoyberg** [comment]
I hear that, but it will drastically limit the usability of http-conduit to do this, which is something I wouldn't want to do. And separating out an http-conduit-core isn't something I have a stomach to maintain either.

Overall I'd rather do nothing. But if it's a major issue, I'd be open to adding a feature flag to disable the `aeson` dep.

**Comment by kazu-yamamoto** [comment]
If you provided the flag to disable `aeson` dep, it would much help me to develop my network related projects.

**Comment by snoyberg** [comment]
I've just pushed a commit that adds an `aeson` flag, would you be able to give it a shot before I release to Hackage? 41e6f748fdc52ba9d024de8e0a94a760e82cc301

**Comment by kazu-yamamoto** [comment]
This works perfectly. Thanks!

**Comment by snoyberg** [comment]
NP releasing shortly
