### ISSUE TITLE
Convenience function for setting bearer authentication

### ISSUE THREAD

**Issue by MaxGabriel** [snoyberg/http-client#455]
Currently there is a helper function for `setRequestBasicAuth`. Would it be desired to have a similar function for adding Bearer auth? This would look something like the following:

`Authorization: Bearer <base64encodedvalue>`

Examples of APIs that use bearer authentication are [Front](https://dev.frontapp.com/docs/core-api-getting-started) and [Stripe](https://stripe.com/docs/api/authentication) (Stripe accepts basic and bearer)

**Comment by snoyberg** [comment]
No objection from me
