### ISSUE TITLE
Circular http-conduit documentation reference from tutorial

### ISSUE THREAD

**Issue by jerith666** [snoyberg/http-client#458]
Starting at https://github.com/snoyberg/http-client/blame/master/TUTORIAL.md#L12, we have this circular link sequence:

* https://www.stackage.org/lts-17.5/package/http-conduit-2.3.8
* * https://www.yesodweb.com/book/http-conduit
* * * https://www.fpcomplete.com/haskell/library/http-client/
* * * * https://github.com/snoyberg/http-client/blob/master/TUTORIAL.md

**Comment by snoyberg** [comment]
I've made relevant updates in repos. The fpcomplete.com updates will propagate when Gitlab.com is working again, and http-conduit's homepage will be updated at next upload to Hackage.
