### ISSUE TITLE
Allow secure cookies for localhost

### ISSUE THREAD

**Issue by mulderr** [snoyberg/http-client#459]
[Firefox 75](https://bugzilla.mozilla.org/show_bug.cgi?id=1618113) and [Chrome 89](https://bugs.chromium.org/p/chromium/issues/detail?id=1056543) now allow "Secure" cookies to be sent over plain http when set by localhost.

This is fully spec compliant, see both linked issues for details.

Should we consider a similar change for `http-client`?

It would require a little additional logic [here](https://github.com/snoyberg/http-client/blob/0a4056efb014766a3d6f099d0878c58d07144251/http-client/Network/HTTP/Client/Cookies.hs#L146).

The benefit is, in a lot of cases, you'd be able to just `{ setCookieSecure = True }` like one probably should, without having to disable it for testing and development.

This also affects downstream libraries like `wreq`.

**Comment by snoyberg** [comment]
Seems like a reasonable change, especially if a PR includes a reference to the relevant RFC.

**Comment by mulderr** [comment]
PR in the works. However, how do we feel about adding a dependency on [iproute](https://hackage.haskell.org/package/iproute) or another library that provides IP address parsing?

Determining if something is ["potentially trustworthy"](https://w3c.github.io/webappsec-secure-contexts/#is-origin-trustworthy) requires, among other things, checking if the host part:
* is IPv4 loopback address, anything from `127.0.0.0/8` is valid, or
* is IPv6 loopback address, `[::1]`, `[::0:0:1]` , `[0:0:0:0:0:0:0:1]`, `[0000:0000:0000:0000:0000:0000:0000:0001]` are just some example ways to write it

**Comment by snoyberg** [comment]
I’m ok with adding such a dependency
