### ISSUE TITLE
http-client-tls should allow specifying a custom CA certificate directory/file

### ISSUE THREAD

**Issue by flokli** [snoyberg/http-client#461]
Followup of https://github.com/snoyberg/http-client/issues/164.

It should be possible to specify the location to a custom SSL cacert file, without manually poking with `TLSSettings`.

I propose doing this like openssl does it: You can pass another location from which CA certificates are loaded by setting `SSL_CERT_DIR`/`SSL_CERT_FILE` - that way, one can temporarily use another trust store, without having to recompile - think about running a HTTP client binary against a HTTPS endpoint, signed with a testing CA.

**Comment by snoyberg** [comment]
I'd definitely be open to such an improvement. Would you be interested in taking a stab at a PR to add it?

**Comment by flokli** [comment]
I don't really do any haskell, sorry. I think switching to `http-client-openssl` seems to be the more reasonable choice, rather than reimplementing openssl's certificate handling in haskell.
