### ISSUE TITLE
Connections are not cleaned up before reuse

### ISSUE THREAD

**Issue by akshaymankar** [snoyberg/http-client#473]
I noticed this when my program was trying to start a websocket using `withConnection` right after making a call to the same server. The response before opening the websocket had returned the body using the chunked transfer encoding and the [chunked reader](https://github.com/snoyberg/http-client/blob/bc481fae6a8cf0d64ba9b4414e522e8c55c6309b/http-client/Network/HTTP/Client/Body.hs#L149-L224) doesn't read the final `CRLF` in the body. This makes the websocket client crash because it gets a `CRLF` instead of the status header. 

The problem goes away if I add `when (count == 0) $ requireNewline` [here](https://github.com/snoyberg/http-client/blob/bc481fae6a8cf0d64ba9b4414e522e8c55c6309b/http-client/Network/HTTP/Client/Body.hs#L163). But I think, in general it shouldn't be that a request is able to read (a part of) response for the previous request. So, it might be best to cleanup the connections before they go back into the pool for reuse.

Here is a little reproducer which shows this behaviour, I tested it with [this server](https://github.com/isaccanedo/http-transfer-encoding-chunked):

```haskell
module Main where

import Network.HTTP.Client
import Network.HTTP.Client.Internal
import qualified Data.ByteString.Char8 as BS

main :: IO ()
main = do
  mgr <- newManager defaultManagerSettings
  req1 mgr
  req2 mgr

req1 :: Manager -> IO ()
req1 mgr = do
  req <- parseRequest "GET http://localhost:3000"
  withResponse req mgr $ (\res -> do
                             bss <- brConsume (responseBody res)
                             BS.putStrLn $ BS.concat bss
                         )

req2 :: Manager -> IO ()
req2 mgr = do
  req <- parseRequest "GET http://localhost:3000"
  -- Read response without writing the request!
  withConnection req mgr $ (\conn -> print =<< connectionRead conn)
````

**Comment by akshaymankar** [comment]
> The problem goes away if I add `when (count == 0) $ requireNewline` [here](https://github.com/snoyberg/http-client/blob/bc481fae6a8cf0d64ba9b4414e522e8c55c6309b/http-client/Network/HTTP/Client/Body.hs#L163).

This is not a good idea because according to [RFC7230](https://datatracker.ietf.org/doc/html/rfc7230#section-4.1.3), there could be trailer fields here.

**Comment by Yuras** [comment]
@akshaymankar Just my 2c (feel free to ignore):
Can we consume the trailer instead? If I read the RFC correctly, we need to read lines til an empty one. Clearing the unread part IMO won't work because the last CRLF might be send as a separate TCP packet (it's unlikely, but possible.)
Also I wonder how it works with this bug for regular (non websocket) requests. I mean the extra CRLF is mandatory, so should get it when the subsequent response is received.

**Comment by akshaymankar** [comment]
> Can we consume the trailer instead? If I read the RFC correctly, we need to read lines til an empty one. Clearing the unread part IMO won't work because the last CRLF might be sent as a separate TCP packet (it's unlikely, but possible.)

Good point, I will change #474 to actually consume headers if available and then consume the CRLF.

> Also I wonder how it works with this bug for regular (non websocket) requests. I mean the extra CRLF is mandatory, so should should get it when the subsequent response is received.

I was trying to find code which somehow ignores this, but couldn't. I did some `print` debugging and found that the CRLF was definitely being consumed while reading the subsequent response.
