### ISSUE TITLE
Weak IORef results in too early release of connections

### ISSUE THREAD

**Issue by fatho** [snoyberg/http-client#489]
In a reverse proxy application we occasionally encountered a problem where forwarding a request would fail due to a `ConnectionClosed` error. I managed to track that down to a weak IORef finalizer closing the connection while it was still in used:

The `Managed` wrapper relies on an `IORef` with a weak reference and an attached finalizer to return connections to the pool (or close them, if the pool was configured as such) once they are garbage collected.

I've managed to (partially) reproduce this problem in:

https://github.com/fatho/http-client/commit/3c770069fa487b338a025151ec4f19dcf8ab389b

which consistently fails with 

```
  test/Network/HTTP/ClientSpec.hs:27:5:
  1) Network.HTTP.Client.Client keeps connection alive long enough
       uncaught exception: HttpException
       HttpExceptionRequest Request {
         host                 = "httpbin.org"
         port                 = 80
         secure               = False
         requestHeaders       = []
         path                 = "/"
         queryString          = ""
         method               = "GET"
         proxy                = Nothing
         rawBody              = False
         redirectCount        = 10
         responseTimeout      = ResponseTimeoutDefault
         requestVersion       = HTTP/1.1
         proxySecureMode      = ProxySecureWithConnect
       }
        ConnectionClosed
```

I cannot fully reproduce it under the same conditions as in our production application, since adding an explicit `responseClose` in the test keeps the connection alive long enough, while it doesn't in the reverse proxy, although we're guarding the connection with bracket there, too.

But I believe that is not the core of this issue: a lacking `responseClose` should only ever result in a connection to be closed later than it possibly could be, but never too early.

As a fix, I introduced a `keepAlive` call in the response cleanup function: https://github.com/fatho/http-client/commit/877d4bdc99191e7be05833e4755989b7b4fe8616

That way, as long as a `BodyReader` (which internally references `cleanup`, which in turn keeps the IORef alive) is live, the connection won't be collected.

With that change, the above test reliably passes.

Would that change be accepted as a PR?

---

As an aside, I still wonder what the best way to write a test for that would be. My reproducer works, but unfortunately is timing sensitive.

**Comment by snoyberg** [comment]
This is probably timing sensitive inherently, so your test case looks about as good as it gets (and thank you for writing it!).

Yes, I'd accept a PR with this change, it seems like a good solution. There may be a better correct-by-construction approach, but (1) I don't know what it would be and (2) it would involve a deeper change, which would make me nervous.

Thank you!

**Comment by fatho** [comment]
Thanks for your quick response, I've expanded the comments in my fix a bit and opened a PR: https://github.com/snoyberg/http-client/pull/490
