### ISSUE TITLE
Support for certificate pinning

### ISSUE THREAD

**Issue by meteficha** [snoyberg/http-client#72]
This was snoyberg/http-conduit#150, but it seems to be gone now. I find it's still a relevant improvement.

**Comment by snoyberg** [comment]
This is actually supported by the tls library, see [clientServerIdentification](http://haddock.stackage.org/nightly-2015-07-19/tls-1.3.1/Network-TLS.html#t:ClientParams), which can be accessed via [mkManagerSettings](http://haddock.stackage.org/nightly-2015-07-19/http-client-tls-0.2.2/Network-HTTP-Client-TLS.html).
