### ISSUE TITLE
Getting a value of a cookie by name

### ISSUE THREAD

**Issue by nikita-volkov** [snoyberg/http-client#96]
The `Network.HTTP.Client.Internal` API exposing the list of cookies, that underlies the `CookieJar`, is stated to be unstable "kitchen sink". How can I get a cookie the proper way?

**Comment by snoyberg** [comment]
I've never actually used the cookie API myself, but I think the (terribly named) [destroyCookieJar](http://www.stackage.org/haddock/nightly-2015-01-14/http-client-0.4.6.2/src/Network-HTTP-Client-Cookies.html#destroyCookieJar) function will give you that access. Can you confirm? I'm certainly not opposed to improving the API (including just giving a better function name).

**Comment by snoyberg** [comment]
Closing, please reopen if the advice above did not work.
