### ISSUE TITLE
performance comparision with http-streams

### ISSUE THREAD

**Issue by larskuhtz** [snoyberg/http-client#98]
Here are some benchmark results of comparing http-client performance with the performance of http-streams for making a large number of requests from (a moderately large number of) concurrent (but otherwise independent) threads:

https://gist.github.com/larskuhtz/d935b119f8b5790e2cda

I wonder what exactly the reasons are for the observed performance differences. I get similar results for POST requests for bodies of up to 64KB. In practice I observed http-streams doing about 3 times as many requests in a given time-frame as as http-client.

The performance differences between the http-streams benchmarks that use an `MVar` for storing the connection and the benchmarks that use an `IORef` seem to indicate that usage of mutable values in variables (for instance for managing connections) may play a role. (Interestingly the performance of the `IORef` version is similar to the `MVar` version when the connection is written back to the `IORef` after each usage, even if the connection wasn't reset.)

**Comment by snoyberg** [comment]
I don't have time to look into this in depth right now. But one thing that jumps out at me is: you're creating a new manager for each benchmark run, which is not recommended usage of http-client, and should not be done in any real-life application. The initial http-streams benchmarks did the same and claimed a performance advantage over http-client, but once that was corrected http-client was in fact faster.

**Comment by snoyberg** [comment]
Actually, looks like your tests are more complicated than that... anyway, original statement applies, I don't have time to dive into this now.

**Comment by larskuhtz** [comment]
I ran tests where a global manager was initialized in `main` and given to the benchmark. The results were similar, so I removed that case in favor of the simpler setting where the manager is created in the benchmark. (There seems to be a limit on how many benchmarks can be included in a single criterion HTML report.)

**Comment by larskuhtz** [comment]
When profiling an application that heavily uses `http-client` I noticed that almost 40% of the time is spent in calls to `System.Timeout.timeout`:

```
COST CENTRE                        MODULE                         %time %alloc

timeout                            Network.HTTP.Client.Response    19.3    4.2
timeout                            Network.HTTP.Client.Request     18.3    4.0
socketConnection                   Network.HTTP.Client.Connection  11.2   11.1
...
```

In the benchmarks I don't implement a timeout handler for `http-streams` [*]. I wonder if the usage of `timeout` could explain the observed differences in the performance of `http-client` and `http-streams`?

[*]  In fact when doing HTTP connections in the backend of HTTP servers we often wouldn't need a timeout handler because there is already a global timeout handler for the request thread.

**Comment by larskuhtz** [comment]
Explicitly setting `managerResponseTimeout = Nothing` almost doubled the number of requests per second in my application. It's not yet on a par with the version that uses `http-streams`, but much better.

**Comment by larskuhtz** [comment]
I wonder if it would be possible to use the same approach to timeout that `warp` uses, namely having a single global timeout handler (`Network.Wai.Handler.Warp.Timeout`)?

**Comment by snoyberg** [comment]
I haven't tested this seriously yet, but I've pushed some code to the faster-timeout branch that, when using the multithreaded runtime, using the event manager to hopefully be more efficient. Would you be able to test it out?

**Comment by larskuhtz** [comment]
I'll give it a try probably tomorrow.

**Comment by larskuhtz** [comment]
I linked the benchmarks against the `faster-timeout` branch. It seems to have little effect on the performance. 

I updated https://gist.github.com/larskuhtz/d935b119f8b5790e2cda with some new results (that use the faster-timeout branch) that include benchmarks for http-client with `managerResponseTimeout = Nothing`. That makes a big difference which may indicate the issue is not caused by the implementation of `timeout` in `System.Timeout` but is sitting deeper somewhere in `getSystemTimerManager` from `GHC.Event`.

**Comment by larskuhtz** [comment]
Here are some results from profiling some code that does makes 50000 requests from 50 threads with the `faster-timeout` branch:

```
COST CENTRE                        MODULE                         %time %alloc

E.registerTimeout                  Network.HTTP.Client.Util        18.5    3.3
timeoutMT                          Network.HTTP.Client.Util        15.7    2.6
socketConnection                   Network.HTTP.Client.Connection  11.2   11.3
...
```

**Comment by larskuhtz** [comment]
Here are two screenshots from threadscope. Both from an application that uses `http-client` to make HTTP requests through 32 concurrent threads using TCP 32 connections with `+RTS -N8`. 

The first screenshot is from a run with `managerResponseTimeout = Just 50000000`:

![threadscope-with-timeout](https://cloud.githubusercontent.com/assets/1369810/5891048/6e69c3ec-a433-11e4-827a-1afa15ba11f5.png)

The second screenshot is from a run with `managerResponseTimeout = Nothing`:

![threadscope-without-timeout](https://cloud.githubusercontent.com/assets/1369810/5891055/9902d698-a433-11e4-8249-4340918d7483.png)

The differences are quite obvious, though have no idea yet how the usage of `timeout` may be causing these differences in the behavior.

**Comment by larskuhtz** [comment]
In the event logs for the run with a timeout I noticed a lot of context switching due to apparent chains of threads being blocked on black holes owned by threads on different caps. 

I wonder if this could be related to `GHC.Event.TimerManager.registerTimeout` updating the timeout queue lazily. Even though the respective comment in the code disappeared in `base-4.8` maybe https://ghc.haskell.org/trac/ghc/ticket/3838 (or something similar) still is an issue? But I don't know enough about the details of the GHC RTS to really understand what is going on.

**Comment by snoyberg** [comment]
Just for the record, I'm not ignoring this issue, but my travel schedule
does not allow me time to focus on it right now.

**Comment by larskuhtz** [comment]
I did some benchmarking with `System.Timeout` (which just wraps the functions from `GHC.Event.TimerManager`). 

The `registerTimeout` function updates the timeout priority-queue that is shared between all threads (on the same capability, I think) through an `IORef`. It seems to me that this queue should always be fairly small (about the number of concurrent threads), so the computational overhead of the update should be only moderate. To figure out the overhead due to the synchronization I included scenarios where instead of calling timeout the threads globally synchronize through updating shared variables (`MVar`s or `IORef`s). While one definitely has to pay a price for the synchronization, it seems to me that this is not enough to fully explain the observed overhead of `timeout`. But at this point I have no idea what else could be causing the overhead and if it could be avoided.

I included all code that I used for benchmarking this issue into this repository: https://github.com/alephcloud/hs-service-benchmark-tool

The criterion results are available through the repository homepage: http://alephcloud.github.io/hs-service-benchmark-tool/

**Comment by gregwebs** [comment]
perhaps @kazu-yamamoto is interested in looking at this timeout issue.

**Comment by kazu-yamamoto** [comment]
I don't have time to dig this issue now. But seeing threadscope figures, I guess there is a global lock somewhere. 

General note:

- `MVar` is a lock
- Allocating big `ByteString` requires a lock (http://www.yesodweb.com/blog/2014/02/new-warp)

**Comment by snoyberg** [comment]
I've just pushed code to a new branch (98-alternate-timeout) which has a **very lightly tested** alternate implementation of `timeout`, which when I tested on my machine seemed to help the performance of this benchmark (thank you for such a solid benchmark by the way). Can you confirm my benchmark results? If in fact this *is* more efficient, I'll clean up the code a bit before releasing. It would also probably be worthwhile to report this as a bug to GHC.

**Comment by snoyberg** [comment]
@larskuhtz Have you had a chance to try out that branch?

**Comment by larskuhtz** [comment]
@snoyberg I read through the code and it looks good; but I haven't yet tried it. I'll try to get to it early this week.

**Comment by snoyberg** [comment]
@larskuhtz Any update on this?

**Comment by snoyberg** [comment]
I've gone ahead and released this to Hackage. If the problem persists, please reopen.

**Comment by larskuhtz** [comment]
@snoyberg sorry that it took me so long to respond. I ran the benchmarks with above branch. The results looked somewhat better, but not at the order that I would have expected. There is still a large penalty introduced by enabling the timeout. So I was wondering if I made a mistake when I did the build or changed something in the benchmark setup or environment (in the end I run the tests on my laptop which introduces quite a bit of noise).

In concrete I saw about ~25% improvement in in the criterion benchmarks for 8 and more threads for the cases with timeout enabled. But even with that the runtime for 16 threads and more is still about twice as much as for the case where there is no timeout.

The thread scope diagrams still show a low degree of parallel work. Here is a thread scope sample with timeout set to a large value:

![screen-shot 2015-03-02 at 9 35 32 am](https://cloud.githubusercontent.com/assets/1369810/6446568/ca7cbe2e-c0c0-11e4-8459-676d46957bfd.png)

Here is the corresponding sample without a timeout:

![screen-shot 2015-03-02 at 9 51 21 am](https://cloud.githubusercontent.com/assets/1369810/6446753/e8a1c9de-c0c1-11e4-89cf-ac406ba4ab43.png)

So next I'll check more carefully if my build actually used above branch before I do any further testing...

**Comment by larskuhtz** [comment]
I repeated the tests with http-client 0.4.7.2. The results match what I described in the previous comment. Here are some criterion results:

![screen-shot 2015-03-02 at 10 55 37 am](https://cloud.githubusercontent.com/assets/1369810/6447883/ec084784-c0ca-11e4-88b3-92e5c8c3b496.png)

**Comment by snoyberg** [comment]
I think it's clear now that the problem is in timeout implementations. I'd suggest as next step coming up with a benchmark that demonstrates the timeout slowdown on its own, and then we can talk to GHC HQ about trying to fix the RTS.

**Comment by larskuhtz** [comment]
I did some benchmarks of just the `timeout` from `System.Timeout`. It is exposing the low level of parallel work in the ThreadScope diagrams. 

The results are here: http://alephcloud.github.io/hs-service-benchmark-tool/

The benchmarks also compare the behavior of `timeout` in comparison with setups where all threads synchronize through `MVar`s and `IORef`s. The results indicate that there is a performance penalty on top of the usage of mutable synchronization variables in the implementation of `timeout`.

**Comment by snoyberg** [comment]
@kazu-yamamoto @AndreasVoellmy Do you think the information above from @larskuhtz would be useful as a GHC Trac ticket? Does it indicate a problem in the RTS?

**Comment by AndreasVoellmy** [comment]
Hi, @larskuhtz thanks for raising this and everyone for chasing this down. I haven't yet read through all the details yet, but I intend to do so soon.

**Comment by kazu-yamamoto** [comment]
Now I have read all comments and code carefully. My guess is that `timeout` causes huge contention on Priority Search Queue which is not striped. Note that IO Manager is using a striped callback table: `Array Int (MVar (IntTable [FdData]))`. (IO Manager has another striped structure: an IO manager is spawn for each core.)

**Comment by kazu-yamamoto** [comment]
But I don't understand why 84e054a2a9392b9c39bfe5b14e22e8990ee16ae1 does not improve the performance drastically.

**Comment by larskuhtz** [comment]
@kazu-yamamoto I haven't looked a the more low-level aspects of the IO manager. Why would that contention affect only the benchmarks with timeout, but not the benchmarks without? Does the excessive usage of timeout induce more expensive operations on that queue?

There is also a queue (`GHC.Event.PSQ`) used in `GHC.Event.TimeoutManager` to keep track of the timeouts. I tried to rule out the influence of that queue by comparing with a version of the benchmarks where all threads synchronize just through mutable variables instead of using a timeout. If the shared timeout queue would be the problem I would expect that the latter benchmarks would suffer from the same performance drawbacks, which they don't.

**Comment by kazu-yamamoto** [comment]
In your `Timeout.hs`, the number of contention in the mvar and IORef version is just 1000 while that of the timeout version is 1000 * 10000000. Note that `System.timeout` itself has the ciritical section (ie IORef to PSQ).

**Comment by larskuhtz** [comment]
Here is how I understand the code: there are exactly `threadN * 1000` calls to `timeout` and to `modifyMVar_`:

```haskell
-- | Run 'threadN' threads which each call 'getCurrentTime'
-- 1000 times with a timeout of 10 seconds (which never triggers).
--
run2 :: Int -> IO ()
run2 n = forkN threadN $
    replicateM_ 1000 . timeout 10000000 . replicateM_ n $ getCurrentTime

-- | All threads share an 'MVar' that each thread updates 1000 times.
--
run3 :: Int -> IO ()
run3 n = do
    mvar <- newMVar [0 :: Int]
    forkN threadN $
        replicateM_ 1000 $ do
            modifyMVar_ mvar (return . func)
            replicateM_ n $ getCurrentTime
```

In `GHC.Event.TimerManager` each call of `timeout` results in 

*   a call to `registerTimeout` and in turn to `editTimeout` which calls `atomicModifyIORef'` on the `TimerManager`,
*   (when the `replicateM_ n $ getCurrentTime` returns) a call to `unregisterTimeout` which again calls `editTimeout`, and
*   a call to `wakeManager` which triggers a call of `step` which in turn class `atomicModifyIORef` on the `TimerManger`.

These three calls happen sequentially. Howerver, I think, the trigger of `step` is asynchronous and may thus overlap with subsequent `timeout` calls or `timeout` calls from other threads. Maybe this overlapping can pile up and cause to many context switches?

**Comment by larskuhtz** [comment]
There is quite a bit of complexity involved in the implementation of `I.poll (emBackend mgr) (Just timeout) (handleControlEvent mgr)` which is called in `step`. This includes a call to [poll](http://hackage.haskell.org/package/base-4.7.0.2/docs/src/GHC-Event-Poll.html#poll) and possibly a call to [readControlMessage](http://hackage.haskell.org/package/base-4.7.0.2/docs/src/GHC-Event-Control.html#readControlMessage).
